/*
 * Warpdroid - a Warpnet Android client.
 * Copyright (C) 2026 Warpdroid contributors.
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
package site.warpnet.transport

/**
 * Initialisation parameters for the Warpnet native client.
 *
 * [privKeyHex] is the 64-byte libp2p-compatible Ed25519 private key in
 * lowercase hex (seed || public key). Persisted/generated by
 * [Ed25519IdentityStore] and forwarded verbatim to the AAR.
 *
 * [pskHex] is the hex-encoded shared key that scopes the libp2p private
 * network. Both desktop and mobile peers must hold the same 32-byte key.
 *
 * [bootstrapAddrs] is a list of libp2p multiaddr strings. Each must include
 * the peer ID segment (`/p2p/<peerid>`) so the Noise handshake can verify
 * identity. The AAR joins them with commas before dialling.
 *
 * [desktopPeerAddr] is the full multiaddr of the paired desktop node. The
 * transport calls `Connect()` with this value after init so every request
 * flows through one specific peer.
 *
 * [network] is the private-network label ("mainnet", "testnet", …) that
 * scopes the libp2p DHT protocol prefix. Supplied by the desktop node via
 * its QR handshake (`NodeInfo.network`); both ends must agree, there is no
 * discovery fallback.
 */
data class WarpnetConfig(
    val privKeyHex: String,
    val pskHex: String,
    val bootstrapAddrs: List<String>,
    val desktopPeerAddr: String,
    val network: String,
)
