/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

const defaultTheme = require("tailwindcss/defaultTheme");
const plugin = require("tailwindcss/plugin");

module.exports = {
  purge: { content: ["./public/**/*.html", "./src/**/*.vue"] },
  darkMode: 'class', // or 'media' or 'class'
  theme: {
    container: {
      center: true,
    },
    maxHeight: {
      full: "85%",
    },
    extend: {
      fontFamily: {
        sans: [...defaultTheme.fontFamily.sans],
      },
      colors: {
        // Light theme: aged parchment and sepia ink, with the same dried
        // blood accent and a darker bronze trim (brass has no contrast on
        // a pale ground). The names are the app's existing brand slots —
        // "blue" has been the primary accent since the Twitter-clone days.
        blue: "#8f1414",
        darkblue: "#6d0b0b",
        lightblue: "#ded0ae",
        dark: "#5c4a30",
        light: "#a9977a",
        lighter: "#e2d7bb",
        lightest: "#efe7d3",
        // Elevated light surfaces (inputs, modals, dropdowns): a shade above
        // the page so they read as raised without going stark white.
        paper: "#f7f2e4",
        // The dark theme is the grimdark one: blackened iron, bone text,
        // brass trim and dried blood as the accent. Key name kept because
        // components reference dark:bg-darktheme-card and friends.
        // Elevated surfaces (cards, inputs) stay darker than the text
        // colors, not lighter, so bone and white both keep contrast.
        darktheme: {
          background: "#14110e",
          foreground: "#2b2219",
          text: "#d6c7a1",
          secondary: "#f0e6d2",
          accent: "#9b1313",
          gold: "#a58a4a",
          input: "#1d1813",
          card: "#1d1813",
        },
      },
    },
    screens: {
      sm: "360px",
      // => @media (min-width: 360px) { ... }

      md: "768px",
      // => @media (min-width: 768px) { ... }

      lg: "1024px",
      // => @media (min-width: 1024px) { ... }

      xl: "1280px",
      // => @media (min-width: 1280px) { ... }

      "2xl": "1536px",
      // => @media (min-width: 1536px) { ... }
    },
  },
  // NOTE: `variants` is Tailwind v2 config and is ignored by the v3 in use
  // here, so it never registered a "mastodon:" variant — those utilities in
  // the templates compiled to nothing. Themes are applied by the hand-written
  // .dark selectors in tailwind.css instead.
  variants: {
    extend: {
      backgroundColor: ["dark"],
      textColor: ["dark"],
      borderColor: ["dark"],
    },
  },
  plugins: [
    plugin(({ addUtilities }) => {
      const newUtilities = {
        /* Hide scrollbar for Chrome, Safari and Opera */
        ".no-scrollbar::-webkit-scrollbar": {
          display: "none",
        },
        ".no-scrollbar": {
          "-ms-overflow-style": "none" /* IE and Edge */,
          "scrollbar-width": "none" /* Firefox */,
        },
      }; //

      addUtilities(newUtilities);
    }),
  ],
};
