# Turns `go build -gcflags=-m` diagnostics into a stack-vs-heap escape report.
#
#   go build -gcflags=-m ./... 2>&1 | awk -f .github/scripts/heap-escape-report.awk
#
# Only the module's own sources are counted: stdlib/toolchain sources (absolute
# paths), vendored dependencies and <autogenerated> wrappers are dropped, and a
# site reported once per generic shape is counted once.
#
# Optional: -v out=FILE appends the headline numbers as KEY=VALUE lines,
#           -v details=1 folds the per package / per file tables into <details>.

{
  raw = $1
  if (raw !~ /\.go:[0-9]+:[0-9]+:$/) next        # not a positioned diagnostic
  pos = raw
  sub(/^\.\//, "", pos)
  if (pos ~ /^\//) next                          # stdlib / toolchain sources
  if (pos ~ /^vendor\//) next                    # vendored dependencies
  msg = substr($0, length(raw) + 2)

  key = pos " " msg
  if (seen[key]++) next

  file = pos
  sub(/:[0-9]+:[0-9]+:$/, "", file)
  pkg = file
  if (pkg ~ /\//) sub(/\/[^\/]*$/, "", pkg); else pkg = "."

  if (msg ~ /^moved to heap: /)      { moved++;   heap[pkg]++; hfile[file]++ }
  else if (msg ~ /escapes to heap$/) { escaped++; heap[pkg]++; hfile[file]++ }
  else if (msg ~ /does not escape$/) { stayed++;  stack[pkg]++ }
  else if (msg ~ /^leaking param/)   { leaking++; next }
  else next
  pkgs[pkg] = 1
}

END {
  total = escaped + moved + stayed
  if (total == 0) {
    print "No escape analysis output was parsed - did the build produce `-gcflags=-m` diagnostics?"
    exit
  }
  heaped = escaped + moved
  rate = 100 * heaped / total

  print  "## Heap escape analysis"
  printf "\n**Escape rate: %.2f%%** - %d of %d analysed allocation sites end up on the heap.\n\n", \
         rate, heaped, total
  print  "| Metric | Count | Share |"
  print  "|---|---:|---:|"
  printf "| Escaped to heap (expressions) | %d | %.2f%% |\n", escaped, 100 * escaped / total
  printf "| Moved to heap (named locals) | %d | %.2f%% |\n", moved, 100 * moved / total
  printf "| Stayed on stack | %d | %.2f%% |\n", stayed, 100 * stayed / total
  printf "| **Total sites** | **%d** | **100%%** |\n", total
  printf "\nLeaking parameters (escape through the callee, not an allocation site): %d\n", leaking + 0

  if (details != "") print "\n<details>\n<summary>Breakdown by package and file</summary>"

  print  "\n### Per package\n"
  print  "| Package | Heap | Stack | Escape rate |"
  print  "|---|---:|---:|---:|"
  n = 0
  for (p in pkgs) ord[n++] = sprintf("%08d\t%s", heap[p] + 0, p)
  for (i = 0; i < n; i++)                        # descending by heap site count
    for (j = i + 1; j < n; j++)
      if (ord[j] > ord[i]) { t = ord[i]; ord[i] = ord[j]; ord[j] = t }
  for (i = 0; i < n; i++) {
    split(ord[i], parts, "\t"); p = parts[2]
    h = heap[p] + 0; s = stack[p] + 0
    printf "| `%s` | %d | %d | %.2f%% |\n", p, h, s, (h + s) ? 100 * h / (h + s) : 0
  }

  print  "\n### Top files by heap allocations\n"
  m = 0
  for (fp in hfile) ford[m++] = sprintf("%08d\t%s", hfile[fp], fp)
  for (i = 0; i < m; i++)
    for (j = i + 1; j < m; j++)
      if (ford[j] > ford[i]) { t = ford[i]; ford[i] = ford[j]; ford[j] = t }
  lim = (m < 15) ? m : 15
  for (i = 0; i < lim; i++) {
    split(ford[i], parts, "\t")
    printf "- `%s` - %d\n", parts[2], parts[1] + 0
  }

  if (details != "") print "\n</details>"

  if (out != "") {
    printf "escape_rate=%.2f\n", rate >> out
    printf "heap_sites=%d\n", heaped >> out
    printf "stack_sites=%d\n", stayed >> out
    printf "total_sites=%d\n", total >> out
  }
}
