FROM golang:1.24-ubuntu

COPY . /warpnet
WORKDIR /warpnet

ENV CGO_ENABLED=1

RUN go build -tags=llama -ldflags "-s -w" -gcflags=all=-l -mod=vendor -v -o warpnet cmd/node/moderator/main.go

CMD ["/warpnet/warpnet"]
