FROM golang:1.25 AS builder

COPY . /warpnet
WORKDIR /warpnet

ENV CGO_ENABLED=0

RUN go build -ldflags "-s -w" -gcflags=all=-l -mod=vendor -v -o warpnet cmd/node/bootstrap/main.go

CMD ["/warpnet/warpnet"]
