services:
  warpnet1:
    container_name: warpnet1
    image: ghcr.io/warp-net/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4001
      - NODE_HOST_V4=88.119.169.156
      - NODE_NETWORK=testnet
      - LOGGING_LEVEL=info
      - NODE_SEED=warpnet1

  warpnet2:
    container_name: warpnet2
    image: ghcr.io/warp-net/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4002
      - NODE_HOST_V4=88.119.169.156
      - NODE_NETWORK=testnet
      - LOGGING_LEVEL=info
      - NODE_SEED=warpnet2

  warpnet3:
    container_name: warpnet3
    image: ghcr.io/warp-net/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4003
      - NODE_HOST_V4=88.119.169.156
      - NODE_NETWORK=testnet
      - LOGGING_LEVEL=info
      - NODE_SEED=warpnet3

  warpnet-moderator:
    container_name: warpnet-moderator1
    image: ghcr.io/warp-net/warpnet-moderator:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4004
      - NODE_HOST_V4=88.119.169.156
      - NODE_NETWORK=testnet
      - LOGGING_LEVEL=info
      - NODE_SEED=warpnet-moderator1

