<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div class="mt-1">
    <video
        v-if="fetched"
        :src="fetched"
        controls
        playsinline
        preload="metadata"
        class="max-w-xs rounded-lg"
        @error="onVideoError"
    ></video>
    <div v-else-if="error" class="max-w-xs rounded-lg bg-lighter text-black text-xs p-3">
      {{ error }}
      <button type="button" @click="loadVideo" class="block mt-1 text-blue font-semibold">Try again</button>
    </div>
    <button
        v-else
        type="button"
        @click="loadVideo"
        :disabled="loading"
        class="relative block max-w-xs rounded-lg overflow-hidden"
        :class="poster ? 'bg-black' : 'bg-lighter hover:bg-lightblue py-8 px-10 text-dark'"
        :aria-label="loading ? 'Loading video' : 'Play video'"
    >
      <img v-if="poster" :src="poster" alt="Video preview" class="max-w-xs block" />
      <span
          class="flex flex-col items-center justify-center"
          :class="poster ? 'absolute inset-0' : ''"
      >
        <span
            class="flex flex-col items-center"
            :class="poster ? 'rounded-lg bg-black bg-opacity-80 px-3 py-2 text-white' : ''"
        >
          <i
              :class="loading ? 'fas fa-circle-notch fa-spin' : 'fas fa-play-circle'"
              class="text-3xl"
              aria-hidden="true"
          ></i>
          <span class="text-xs font-semibold mt-1">{{ loading ? 'Loading video…' : 'Play video' }}</span>
        </span>
      </span>
    </button>
  </div>
</template>

<script>
import {warpnetService} from "@/service/service";

export default {
  name: "ChatVideo",
  props: {
    videoKey: {type: String, default: ''},
    senderId: {type: String, default: ''},
    poster: {type: String, default: ''},
  },
  data() {
    return {
      fetched: '',
      loading: false,
      error: '',
    };
  },
  methods: {
    async loadVideo() {
      if (this.loading || this.fetched || !this.videoKey) return;
      this.error = '';
      this.loading = true;
      try {
        const video = await warpnetService.getVideo({
          userId: this.senderId,
          key: this.videoKey,
        });
        if (!video || !video.file) {
          this.error = "This video isn't available right now. The sender's node may be offline.";
          return;
        }
        this.fetched = video.file;
      } catch (err) {
        console.error(`failed to load message video [${this.videoKey}]`, err);
        this.error = 'Failed to load the video.';
      } finally {
        this.loading = false;
      }
    },
    onVideoError() {
      this.fetched = '';
      this.error = 'This video cannot be played. Your system may be missing the required video codec.';
    },
  },
};
</script>
