<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div
    class="fixed w-full h-full top-0 left-0 flex items-center justify-center"
  >
    <div
      class="absolute w-full h-full bg-gray-900 opacity-50"
      @click.prevent="requestClose"
    ></div>

    <div
      class="modal-main bg-white mx-auto rounded-lg z-50 overflow-y-auto no-scrollbar w-full max-w-lg"
      style="height:85%"
      role="dialog"
      aria-modal="true"
      aria-label="Edit profile"
    >
      <div class="pl-1 pr-4 py-1 h-16 border-b-2 border-lightblue">
        <button
          @click="saveProfile"
          :disabled="saving"
          class="rounded-full bg-blue font-bold text-white mt-2 p-1 px-4 relative right-0 float-right focus:outline-none hover:bg-darkblue"
          :class="saving ? 'opacity-60 cursor-default' : ''"
        >
          <span v-if="!saving">Save</span>
          <span v-else><i class="fas fa-circle-notch fa-spin mr-1" aria-hidden="true"></i>Saving…</span>
        </button>
        <div class="flex flex-row mt-1 ml-4 items-center">
          <button
            type="button"
            @click="requestClose"
            class="rounded-full bg-white p-2 px-3 hover:bg-lightblue mr-6 flex items-center justify-center"
            aria-label="Close"
          >
            <i class="fas fa-times text-blue text-2xl" aria-hidden="true"></i>
          </button>
          <p class="text-xl pt-1 font-bold">Edit profile</p>
        </div>
      </div>

      <div class="border-l-2 border-r-2 border-white">
        <!-- background image -->
        <div class="relative" style="height:200px; display:block">
          <!-- change background overlay -->
          <div
            class="absolute w-full max-w-full h-full max-h-full bg-gray-600 opacity-50"
          ></div>
          <button
            @click="openFileInput('backgroundFileInput')"
            class="absolute hover:bg-gray-800 p-3 rounded-full"
            style="margin-left: 45%; margin-top: 80px"
            type="button"
            aria-label="Change background image"
          >
            <i class="text-2xl fas fa-camera text-white" aria-hidden="true"></i>
            <input
              @change="fileChange('backgroundFileInput', 'background_image')"
              ref="backgroundFileInput"
              accept="image/*"
              type="file"
              class="hidden"
            />
          </button>

          <div v-if="background_image" class="h-full max-h-full">
            <img :src="background_image" class="h-full w-full object-cover" alt="Background" />
          </div>
          <div
            v-if="!background_image"
            class="bg-gray-400 h-full max-h-full"
          ></div>
        </div>

        <div class="p-3 flex flex-col">
          <!-- profile image -->
          <div
            style="margin-top:-80px"
            class="relative w-32 h-32 rounded-full mb-6"
          >
            <div
              class="absolute w-32 h-32 rounded-full bg-gray-600 opacity-50 border-4 border-white"
            ></div>
            <button
              @click="openFileInput('imageUrlFileInput')"
              class="absolute hover:bg-gray-800 p-3 rounded-full ml-10 mt-10"
              type="button"
              aria-label="Change profile picture"
            >
              <i class="text-2xl fas fa-camera text-white" aria-hidden="true"></i>
              <input
                @change="fileChange('imageUrlFileInput', 'avatar')"
                ref="imageUrlFileInput"
                accept="image/*"
                type="file"
                class="hidden"
              />
            </button>

            <img
              :src="avatar"
              class="w-32 h-32 rounded-full border-4 border-white"
              alt="Avatar"
            />
          </div>

          <div class="w-full bg-lightest border-b-2 border-dark mb-6 py-1 px-3">
            <label class="text-dark" for="username">Name</label>
            <input
              id="username"
              v-model.trim="username"
              class="w-full bg-lightest text-lg focus:outline-none"
              type="text"
              required
            />
          </div>
          <div class="w-full bg-lightest border-b-2 border-dark mb-6 py-1 px-3">
            <label class="text-dark" for="bio">Bio</label>
            <textarea
              id="bio"
              v-model.trim="bio"
              class="w-full bg-lightest text-lg focus:outline-none"
              placeholder="Add your bio"
            />
          </div>
          <div class="w-full bg-lightest border-b-2 border-dark mb-6 py-1 px-3">
            <label class="text-dark" for="website">Website</label>
            <input
              id="website"
              v-model.trim="website"
              class="w-full bg-lightest text-lg focus:outline-none"
              type="url"
              placeholder="Add your website"
            />
          </div>
          <div
            class="w-full bg-lightest border-b-2 border-dark mb-24 py-1 px-3"
          >
            <label class="text-dark" for="birthdate">Birth date</label>
            <input
              id="birthdate"
              v-model="birthdate"
              class="w-full bg-lightest text-lg focus:outline-none"
              type="date"
              placeholder="Add your birth date"
            />
          </div>
        </div>
      </div>
    </div>

    <ConfirmDialog
      :show="showDiscardConfirm"
      title="Discard changes?"
      message="You have unsaved changes. If you leave now they'll be lost."
      confirm-label="Discard"
      cancel-label="Keep editing"
      :destructive="true"
      @confirm="showDiscardConfirm = false; $emit('close')"
      @cancel="showDiscardConfirm = false"
    />
  </div>
</template>
<style scoped>
.modal-main {
  max-height: 90vh;
}

input[type="date"]::-webkit-calendar-picker-indicator {
  cursor: pointer;
}

textarea {
  resize: none;
}
</style>


<script>
import moment from "moment";
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";
import {toast} from "@/lib/toast";

export default {
  name: "EditProfileOverlay",
  components: {
    ConfirmDialog: defineAsyncComponent(() => import('./ConfirmDialog.vue')),
  },
  props: {
    showEditProfileModal: Boolean
  },
  data() {
    return {
      profile: {},
      username: undefined,
      background_image: undefined,
      avatar: undefined,
      bio: undefined,
      website: undefined,
      birthdate: undefined,
      saving: false,
      showDiscardConfirm: false,
      // Snapshot of the loaded values so we can detect unsaved edits.
      initial: {},
    };
  },
  computed: {
    isDirty() {
      const i = this.initial;
      return (
        this.username !== i.username ||
        this.bio !== i.bio ||
        this.website !== i.website ||
        this.birthdate !== i.birthdate ||
        this.avatar !== i.avatar ||
        this.background_image !== i.background_image
      );
    },
  },
  methods: {
    handleKeyup(event) {
      if (event.key === "Escape") {
        this.requestClose();
      }
    },
    // requestClose guards against silently discarding edits: it only closes
    // straight away when nothing changed.
    requestClose() {
      if (this.saving) return;
      if (this.isDirty) {
        this.showDiscardConfirm = true;
        return;
      }
      this.$emit("close");
    },
    openFileInput(ref) {
      this.$refs[ref].click();
    },
    async fileChange(ref, prop) {
      const file = this.$refs[ref].files[0];
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => this[prop] = reader.result;
      reader.onerror = (error) => {
        console.error("Error reading file:", error);
        toast.error("Couldn't read the selected image. Please try another file.");
      };
    },
    async saveProfile() {
      if (this.saving) return;
      this.saving = true;
      try {
        const p = {
          username: this.username,
          avatar_key: "",
          background_image_key: "",
          bio: this.bio,
          website: this.website,
          birthdate: this.birthdate ? moment(this.birthdate, "YYYY-MM-DD").format("YYYY-MM-DD") : null,
        };
        p.avatar_key = await warpnetService.uploadImage(this.avatar)
        p.background_image_key = await warpnetService.uploadImage(this.background_image)

        this.profile = await warpnetService.editMyProfile(p);
        const existingOwner = warpnetService.getOwnerProfile();
        if (existingOwner) {
          // Route the merge through setOwnerProfile: Object.assign on the raw
          // stateMap object bypasses Vue's proxies, so subscribers (SideNav)
          // never re-render and localStorage keeps the stale owner.
          warpnetService.setOwnerProfile({
            ...existingOwner,
            username: this.profile.username || existingOwner.username,
            avatar_key: this.profile.avatar_key || "",
          });
        }

        this.background_image = await warpnetService.getImage({userId:this.profile.user_id, key:this.profile.background_image_key});
        this.avatar = await warpnetService.getImage({userId:this.profile.user_id, key:this.profile.avatar_key})

        toast.success("Profile updated.");
        this.$emit("close");
      } catch (err) {
        console.error("Failed to save profile:", err);
        toast.error(err?.message || "Couldn't save your profile. Please try again.");
      } finally {
        this.saving = false;
      }
    },
  },
  mounted() {
    window.addEventListener("keyup", this.handleKeyup);
  },
  beforeUnmount() {
    window.removeEventListener("keyup", this.handleKeyup);
  },
  async created() {
    console.log("loading component:", this.$options.name);
    console.log(this.$options.name);
    // The in-memory owner stub only carries user_id/node_id/username, so
    // fetch the full profile — otherwise Bio/Website/avatar open blank and
    // saving would wipe them.
    this.profile = warpnetService.getOwnerProfile();
    try {
      const full = await warpnetService.getProfile(this.profile.user_id);
      if (full && !full.code && full.id) {
        this.profile = { ...this.profile, ...full };
      }
    } catch (err) {
      console.error("Failed to load full profile for editing:", err);
    }
    this.username = this.profile.username;
    this.background_image = await warpnetService.getImage({userId:this.profile.user_id, key:this.profile.background_image_key});
    this.avatar = await warpnetService.getImage({userId:this.profile.user_id, key:this.profile.avatar_key})
    this.bio = this.profile.bio;
    this.website = this.profile.website;
    this.birthdate = this.profile.birthdate;
    // Capture the loaded state so isDirty can tell real edits from a
    // straight open-and-close.
    this.initial = {
      username: this.username,
      bio: this.bio,
      website: this.website,
      birthdate: this.birthdate,
      avatar: this.avatar,
      background_image: this.background_image,
    };
  },
};
</script>
