<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div
    class="absolute z-50 w-72 rounded-lg border border-lighter bg-white shadow-lg"
    :class="dropUp ? 'bottom-full mb-2' : 'top-full mt-2'"
    role="dialog"
    aria-label="Choose an emoji"
  >
    <div class="flex items-center gap-2 p-2 border-b border-lighter">
      <input
        ref="search"
        v-model="query"
        type="text"
        placeholder="Search emoji"
        aria-label="Search emoji"
        class="flex-1 min-w-0 rounded-full border border-lighter px-3 py-1 text-sm focus:outline-none focus:ring-2 focus:ring-blue"
      />
      <div class="relative flex-none">
        <button
          type="button"
          @click="toneOpen = !toneOpen"
          class="w-8 h-8 rounded-full text-lg leading-none flex items-center justify-center hover:bg-lighter"
          :aria-label="'Skin tone: ' + activeTone.label"
          :title="'Skin tone: ' + activeTone.label"
          aria-haspopup="true"
        >{{ activeTone.swatch }}</button>
        <div
          v-if="toneOpen"
          class="absolute right-0 top-full mt-1 flex gap-1 p-1 rounded-full border border-lighter bg-white shadow-lg"
        >
          <button
            v-for="t in tones"
            :key="t.id"
            type="button"
            @click="pickTone(t.id)"
            class="w-7 h-7 rounded-full text-lg leading-none flex items-center justify-center hover:bg-lighter"
            :class="t.id === tone ? 'ring-2 ring-blue' : ''"
            :aria-label="t.label"
            :title="t.label"
          >{{ t.swatch }}</button>
        </div>
      </div>
    </div>

    <div v-if="!query" class="flex items-center border-b border-lighter px-1">
      <button
        v-for="tab in tabs"
        :key="tab.id"
        type="button"
        @click="active = tab.id"
        class="flex-1 py-1 text-lg leading-none rounded"
        :class="active === tab.id ? 'bg-lighter' : 'hover:bg-lighter'"
        :aria-label="tab.name"
        :title="tab.name"
        :aria-pressed="active === tab.id"
      >{{ tab.icon }}</button>
    </div>

    <div class="h-56 overflow-y-auto p-2">
      <p v-if="visible.length === 0" class="text-sm text-dark text-center py-8">
        {{ query ? 'No emoji found' : 'Nothing here yet' }}
      </p>
      <div v-else class="grid grid-cols-8 gap-1">
        <button
          v-for="entry in visible"
          :key="entry[0]"
          type="button"
          @click="pick(entry)"
          class="h-8 rounded text-xl leading-none flex items-center justify-center hover:bg-lighter"
          :aria-label="entry[1]"
          :title="entry[1]"
        >{{ display(entry) }}</button>
      </div>
    </div>
  </div>
</template>

<script>
import {dismissable} from "@/lib/modal.mixin";
import {
  EMOJI_CATEGORIES,
  SKIN_TONES,
  applyTone,
  loadRecent,
  loadTone,
  pushRecent,
  saveTone,
  searchEmojis,
} from "@/lib/emoji";

const RECENT_TAB = "recent";

export default {
  name: "EmojiPicker",
  mixins: [dismissable("close")],
  props: {
    // Composers pinned to the bottom of the viewport (the DM input) need the
    // panel above the button; anything higher up on the page opens downwards.
    dropUp: {type: Boolean, default: false},
  },
  emits: ["select", "close"],
  data() {
    const recent = loadRecent();
    return {
      query: "",
      tone: loadTone(),
      toneOpen: false,
      recent,
      active: recent.length > 0 ? RECENT_TAB : EMOJI_CATEGORIES[0].id,
      tones: SKIN_TONES,
    };
  },
  computed: {
    tabs() {
      const categories = EMOJI_CATEGORIES.map((c) => ({id: c.id, name: c.name, icon: c.icon}));
      if (this.recent.length === 0) return categories;
      return [{id: RECENT_TAB, name: "Recently used", icon: "🕘"}, ...categories];
    },
    activeTone() {
      return SKIN_TONES.find((t) => t.id === this.tone) || SKIN_TONES[0];
    },
    visible() {
      if (this.query.trim()) return searchEmojis(this.query);
      if (this.active === RECENT_TAB) return this.recent;
      const category = EMOJI_CATEGORIES.find((c) => c.id === this.active);
      return category ? category.emojis : [];
    },
  },
  methods: {
    // Recents are stored with their tone already baked in, so they carry no
    // tone flag and applyTone leaves them exactly as they were picked.
    display(entry) {
      return applyTone(entry[0], this.activeTone.modifier, entry[2]);
    },
    pick(entry) {
      const character = this.display(entry);
      this.recent = pushRecent([character, entry[1]]);
      this.$emit("select", character);
    },
    pickTone(id) {
      this.tone = id;
      this.toneOpen = false;
      saveTone(id);
    },
    onDocumentMouseDown(e) {
      // The button that opened the picker lives in the anchor wrapper; treating
      // it as "inside" lets its own click close the picker instead of this
      // handler closing it first and the click reopening it.
      const anchor = this.$el.closest ? this.$el.closest("[data-emoji-anchor]") : null;
      const root = anchor || this.$el;
      if (!root.contains(e.target)) this.$emit("close");
    },
  },
  mounted() {
    this.$refs.search.focus();
    document.addEventListener("mousedown", this.onDocumentMouseDown);
  },
  beforeUnmount() {
    document.removeEventListener("mousedown", this.onDocumentMouseDown);
  },
};
</script>
