<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <!-- Indeterminate bar: the login/sign-up call has no real percentage, so an
       honest looping animation beats a fake timer-driven counter. -->
  <div class="flex flex-col items-center justify-center w-full" role="status" aria-label="Loading">
    <div class="w-64 h-2 bg-lighter dark:bg-darktheme-input mastodon:bg-mastodon-input rounded-full overflow-hidden">
      <div class="h-full bg-blue rounded-full progress-indeterminate"></div>
    </div>
    <span class="sr-only">Loading…</span>
  </div>
</template>
<script>
  export default {
    name: "ProgressBarComponent",
  };
</script>
<style scoped>
.progress-indeterminate {
  width: 40%;
  animation: progress-slide 1.2s ease-in-out infinite;
}
@keyframes progress-slide {
  0%   { margin-left: -40%; }
  100% { margin-left: 100%; }
}
</style>