<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <!-- The gap above the button is padding rather than margin, so the
       element's box reaches the button and the pointer can travel onto the
       bar without leaving the hover area that opened it. -->
  <!-- Anchored right and sized to its content: the containing block is the
       quarter-width cell the reaction button lives in, so a left-anchored
       row runs off the column and a percentage-width one is squeezed into
       four cramped rows. w-max keeps one row, growing leftwards over the
       cells beside it. -->
  <div class="absolute bottom-full right-0 pb-2 z-40" data-reaction-bar>
    <div
      class="flex w-max items-center gap-1 rounded-full border border-lighter bg-white px-2 py-1 shadow-lg"
      role="menu"
      aria-label="React"
    >
      <button
        v-for="emoji in quickReactions"
        :key="emoji"
        type="button"
        role="menuitem"
        class="w-8 h-8 flex items-center justify-center rounded-full text-lg leading-none transition-transform hover:scale-125 flat-btn"
        :class="emoji === selected ? 'bg-lightblue' : ''"
        :aria-label="emoji === selected ? `Remove ${emoji} reaction` : `React with ${emoji}`"
        :title="emoji"
        @click.stop="$emit('select', emoji)"
      >{{ emoji }}</button>
      <!-- A text glyph, not a Font Awesome icon: the icons come from a CDN
           kit, so on a node without internet the whole row would lose its
           "more" affordance. -->
      <button
        type="button"
        role="menuitem"
        class="w-8 h-8 flex items-center justify-center rounded-full border border-lighter text-lg leading-none hover:bg-lightblue flat-btn"
        aria-label="More emoji"
        title="More emoji"
        :aria-expanded="showPicker"
        @click.stop="showPicker = !showPicker"
      >+</button>
    </div>
    <EmojiPicker
      v-if="showPicker"
      drop-up
      @select="pick"
      @close="showPicker = false"
    />
  </div>
</template>

<script>
import {defineAsyncComponent} from "vue";
import {QUICK_REACTIONS} from "@/lib/emoji";
import {dismissable} from "@/lib/modal.mixin";

export default {
  name: "ReactionBar",
  mixins: [dismissable("close")],
  components: {
    EmojiPicker: defineAsyncComponent(() => import('./EmojiPicker.vue')),
  },
  props: {
    // The reaction the viewer currently holds, highlighted in the row so
    // tapping it again reads as "remove", the way Telegram does it.
    selected: {type: String, default: ""},
  },
  emits: ["select", "close"],
  data() {
    return {
      quickReactions: QUICK_REACTIONS,
      showPicker: false,
    };
  },
  mounted() {
    this.__outsideHandler = (e) => {
      if (this.$el.contains && this.$el.contains(e.target)) return;
      this.$emit("close");
    };
    // Deferred: the very pointerup/click that opened the bar would
    // otherwise land on the document and close it again immediately.
    setTimeout(() => document.addEventListener("mousedown", this.__outsideHandler), 0);
  },
  beforeUnmount() {
    document.removeEventListener("mousedown", this.__outsideHandler);
  },
  methods: {
    pick(emoji) {
      this.showPicker = false;
      this.$emit("select", emoji);
    },
  },
};
</script>
