<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div
    class="fixed w-full h-full top-0 left-0 flex items-center justify-center"
  >
    <div
      class="absolute w-full h-full bg-gray-900 opacity-50"
      @click.prevent="this.$emit('close')"
    ></div>
    <div
      class="modal-main bg-white mx-auto rounded-lg z-50 overflow-y-auto w-full max-w-md"
      style="height:80%"
      role="dialog"
      aria-modal="true"
      aria-label="Set up profile picture"
    >
      <div class="pl-1 pr-4 py-1 h-12">
        <button
          v-if="newImage === null || newImage === '/default_profile.png'"
          @click="this.$emit('close')"
          class="rounded-full bg-white font-bold text-blue mt-2 p-1 px-3 relative right-0 float-right focus:outline-none hover:bg-lightblue"
        >
          Skip for now
        </button>
        <button
          v-if="newImage !== null && newImage !== '/default_profile.png'"
          @click="finishSetUpProfile"
          :disabled="saving"
          class="rounded-full bg-blue font-bold text-white mt-2 p-1 px-4 relative right-0 float-right focus:outline-none hover:bg-darkblue"
          :class="saving ? 'opacity-60 cursor-default' : ''"
        >
          <span v-if="!saving">Save</span>
          <span v-else><i class="fas fa-circle-notch fa-spin mr-1" aria-hidden="true"></i>Saving…</span>
        </button>
        <i
          class="relative fab text-blue text-2xl mt-2 mb-8"
          style="margin-left: 50%"
        ></i>
      </div>

      <div class="pt-5 px-8">
        <div class="flex justify-between items-center mb-5">
          <p class="text-2xl font-bold">Pick a profile picture</p>
        </div>
        <p class="text-dark">Have a favorite selfie? Upload it now.</p>

        <div class="mt-16 w-full flex items-center justify-center">
          <div class="relative">
            <div
              class="absolute w-32 h-32 rounded-full bg-gray-600 opacity-50"
            ></div>
            <button
              @click="openFileInput"
              class="absolute hover:bg-gray-800 p-3 rounded-full"
              style="left: 50%; top: 50%; transform: translate(-50%, -50%)"
              type="button"
              aria-label="Upload profile picture"
            >
              <i class="text-2xl fas fa-camera text-white" aria-hidden="true"></i>
              <input
                @change="fileChange"
                ref="fileInput"
                accept="image/*"
                type="file"
                class="hidden"
              />
            </button>
            <img 
              class="w-32 h-32 rounded-full" 
              :src="newImage"
              alt="Profile picture"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import {warpnetService} from "@/service/service";
import {toast} from "@/lib/toast";

export default {
  name: "SetUpProfileOverlay",
  props: ["showSetUpProfileModal"],
  data() {
    return {
      newImage: "/default_profile.png",
      profile: {},
      saving: false,
    };
  },
  methods: {
    handleKeyup(event) {
      if (event.key === "Escape" && !this.saving) {
        this.$emit("close");
      }
    },
    openFileInput() {
      this.$refs.fileInput.click();
    },
    async fileChange() {
      const file = this.$refs.fileInput.files[0];
      if (!file) return;
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => this.newImage = reader.result;
      reader.onerror = (error) => {
        console.error("Error reading file:", error);
        toast.error("Couldn't read the selected image. Please try another file.");
      };
    },
    async finishSetUpProfile() {
      if (this.saving) return;
      this.saving = true;
      try {
        const p = {
          username: this.profile.username,
          avatar_key: "",
        };

        p.avatar_key = await warpnetService.uploadImage(this.newImage)
        this.profile = await warpnetService.editMyProfile(p);
        const uid = this.profile.user_id || this.profile.id;
        this.newImage = await warpnetService.getImage({userId: uid, key: p.avatar_key})
        this.profile.avatar = this.newImage;
        // Notify owner subscribers (SideNav) so the new avatar shows without
        // a route change — mirrors EditProfileOverlay.
        const existingOwner = warpnetService.getOwnerProfile();
        if (existingOwner) {
          warpnetService.setOwnerProfile({
            ...existingOwner,
            username: this.profile.username || existingOwner.username,
            avatar_key: p.avatar_key || "",
          });
        }
        toast.success("Profile picture saved.");
        this.$emit("close");
      } catch (err) {
        console.error("Failed to save profile picture:", err);
        toast.error(err?.message || "Couldn't save your picture. Please try again.");
      } finally {
        this.saving = false;
      }
    },
  },
  mounted() {
    window.addEventListener("keyup", this.handleKeyup);
  },
  beforeUnmount() {
    window.removeEventListener("keyup", this.handleKeyup);
  },
  created() {
    // The username must ride along with the avatar save, so seed profile from
    // the current owner — otherwise editMyProfile would send a blank username.
    const owner = warpnetService.getOwnerProfile();
    if (owner) {
      this.profile = { ...owner };
    }
  },
};
</script>
