<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div>
    <QRCodeModal
      :show="qrModalOpen"
      :qrData="qrCode"
      @close="closeQR"
    />
  </div>

  <!-- Mobile bottom tab bar (visible below sm breakpoint, <360px per tailwind.config.js) -->
  <nav class="fixed bottom-0 left-0 right-0 z-50 bg-white border-t border-lighter flex justify-around items-center py-2 sm:hidden" role="navigation" aria-label="Mobile navigation">
    <button @click="open('Home')" :class="$route.name === 'Home' ? 'text-blue' : 'text-dark'" class="flex flex-col items-center p-2 flat-btn" aria-label="Home">
      <i class="fa fa-home text-xl" aria-hidden="true"></i>
      <span class="text-xs mt-0.5">Home</span>
    </button>
    <button @click="open('Notifications')" :class="$route.name === 'Notifications' ? 'text-blue' : 'text-dark'" class="flex flex-col items-center p-2 relative flat-btn" aria-label="Notifications">
      <i class="fa-bell text-xl" :class="$route.name === 'Notifications' ? 'fas' : 'far'" aria-hidden="true"></i>
      <span v-if="newNotifications > 0" class="absolute -top-0.5 right-0 inline-flex items-center justify-center w-4 h-4 rounded-full text-[10px] font-bold bg-blue text-white">{{ newNotifications }}</span>
      <span class="text-xs mt-0.5">Alerts</span>
    </button>
    <button @click="open('Chats')" :class="$route.name === 'Chats' || $route.name === 'Messages' ? 'text-blue' : 'text-dark'" class="flex flex-col items-center p-2 relative flat-btn" aria-label="Messages">
      <i class="fa-envelope text-xl" :class="$route.name === 'Chats' || $route.name === 'Messages' ? 'fas' : 'far'" aria-hidden="true"></i>
      <span v-if="newMessages > 0" class="absolute -top-0.5 right-0 inline-flex items-center justify-center w-4 h-4 rounded-full text-[10px] font-bold bg-blue text-white">{{ newMessages }}</span>
      <span class="text-xs mt-0.5">Chats</span>
    </button>
    <button @click="open('Profile')" :class="$route.name === 'Profile' ? 'text-blue' : 'text-dark'" class="flex flex-col items-center p-2 flat-btn" aria-label="Profile">
      <i class="fa-user text-xl" :class="$route.name === 'Profile' ? 'fas' : 'far'" aria-hidden="true"></i>
      <span class="text-xs mt-0.5">Profile</span>
    </button>
  </nav>

  <nav
    class="w-1/6 md:w-1/12 xl:w-1/6 border-r border-lighter lg:px-6 py-2 flex-col justify-between hidden sm:flex"
    role="navigation"
    aria-label="Main navigation"
  >
    <div>
      <button
        @click="open('Home')"
        class="h-12 w-12 hover:bg-lightblue text-blue rounded-full flex items-center justify-center"
        aria-label="Warpnet home"
      >
        <svg viewBox="0 0 100 100" class="w-7 h-7" fill="none" stroke="currentColor"
             stroke-width="12" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <path d="M25 36 L36.5 64 L50 50 L63.5 64 L75 36" />
        </svg>
      </button>
      <div>
        <button
          @click="open('Home')"
          :class="{ 'nav-active': $route.name === 'Home' }"
          class="hover:text-blue flex items-center px-4 py-2 hover:bg-transparent md:hover:bg-lightblue rounded-full mr-auto mb-1"
          aria-label="Home"
        >
          <i
            class="fa fa-home"
            :class="$route.name === 'Home' ? 'text-2xl' : 'text-xl'"
            aria-hidden="true"
          ></i>
          <p
            class="text-lg ml-4 text-left hidden xl:block"
            :class="$route.name === 'Home' ? 'font-bold' : ''"
          >
            Home
          </p>
        </button>
        <button
          @click="open('Notifications')"
          :class="{ 'nav-active': $route.name === 'Notifications' }"
          class="relative hover:text-blue flex items-center px-4 py-2 hover:bg-transparent md:hover:bg-lightblue rounded-full mr-auto mb-1"
          aria-label="Notifications"
        >
          <i
            class="fa-bell"
            :class="
              $route.name === 'Notifications' ? 'text-2xl fas' : 'text-xl far'
            "
            aria-hidden="true"
          ></i>
          <span v-if="newNotifications > 0" class="absolute -mt-6 ml-2">
            <div
              class="inline-flex items-center px-1.5 py-0.5 border-2 border-white rounded-full text-xs font-semibold leading-4 bg-blue text-white"
            >
              {{ newNotifications }}
            </div>
          </span>
          <p
            class="text-lg ml-4 text-left hidden xl:block"
            :class="$route.name === 'Notifications' ? 'font-bold' : ''"
          >
            Notifications
          </p>
        </button>
        <button
          @click="open('Chats')"
          :class="{ 'nav-active': $route.name === 'Chats' || $route.name === 'Messages' }"
          class="hover:text-blue flex items-center px-4 py-2 hover:bg-transparent md:hover:bg-lightblue rounded-full mr-auto mb-1"
          aria-label="Messages"
        >
          <i
            class="fa-envelope"
            :class="$route.name === 'Chats' ? 'text-2xl fas' : 'text-xl far'"
            aria-hidden="true"
          ></i>
          <span v-if="newMessages > 0" class="absolute -mt-6 ml-2">
            <div
              class="inline-flex items-center px-1.5 py-0.5 border-2 border-white rounded-full text-xs font-semibold leading-4 bg-blue text-white"
            >
              {{ newMessages }}
            </div>
          </span>
          <p
            class="text-lg ml-4 text-left hidden xl:block"
            :class="$route.name === 'Chats' ? 'font-bold' : ''"
          >
            Messages
          </p>
        </button>
        <button
          @click="$router.push({ name: 'Bookmarks' })"
          :class="{ 'nav-active': $route.name === 'Bookmarks' }"
          class="hover:text-blue flex items-center px-4 py-2 hover:bg-transparent md:hover:bg-lightblue rounded-full mr-auto mb-1"
          aria-label="Bookmarks"
        >
          <i
            class="fa-bookmark"
            :class="$route.name === 'Bookmarks' ? 'text-2xl fas' : 'text-xl far'"
            aria-hidden="true"
          ></i>
          <p
            class="text-lg ml-4 text-left hidden xl:block"
            :class="$route.name === 'Bookmarks' ? 'font-bold' : ''"
          >
            Bookmarks
          </p>
        </button>
        <button
          @click="open('Profile')"
          :class="{ 'nav-active': $route.name === 'Profile' }"
          class="hover:text-blue flex items-center px-4 py-2 hover:bg-transparent md:hover:bg-lightblue rounded-full mr-auto mb-1"
          aria-label="Profile"
        >
          <i
            class="fa-user"
            :class="$route.name === 'Profile' ? 'text-2xl fas' : 'text-xl far'"
            aria-hidden="true"
          ></i>
          <p
            class="text-lg ml-4 text-left hidden xl:block"
            :class="$route.name === 'Profile' ? 'font-bold' : ''"
          >
            Profile
          </p>
        </button>
        <button
          @click="$router.push({ name: 'Settings' })"
          :class="{ 'nav-active': $route.name && $route.name.startsWith('Settings') }"
          class="hover:text-blue flex items-center px-4 py-2 hover:bg-transparent md:hover:bg-lightblue rounded-full mr-auto mb-1"
          aria-label="Settings"
        >
          <i
            class="text-xl fas fa-cog"
            :class="$route.name && $route.name.startsWith('Settings') ? 'text-2xl' : 'text-xl'"
            aria-hidden="true"
          ></i>
          <p
            class="text-lg ml-4 text-left hidden xl:block"
            :class="$route.name && $route.name.startsWith('Settings') ? 'font-bold' : ''"
          >
            Settings
          </p>
        </button>
      </div>

      <button
        @click="openTweetCompose()"
        class="text-white bg-blue rounded-full font-semibold h-12 lg:h-auto w-12 xl:w-full hover:bg-darkblue p-3 overflow-hidden whitespace-nowrap text-ellipsis"
      >
        <p class="hidden xl:block truncate">Tweet</p>
        <i class="fas fa-plus xl:hidden"></i>
      </button>
    </div>
    <div v-if="profile" ref="accountMenu" class="xl:w-full relative mt-2 w-10 h-10">
      <button
        @click="dropdown = !dropdown"
        class="flex items-center w-full hover:bg-lightblue rounded-full"
        :aria-expanded="dropdown"
      >
        <img
          :src="profile.avatar || '/default_profile.png'"
          class="w-10 h-10 rounded-full object-cover bg-transparent"
        />
        <div class="hidden xl:block ml-4 truncate">
          <div class="text-left text-sm font-bold leading-tight truncate">
            {{ profile.username }}
          </div>
          <div class="text-left text-sm leading-tight text-dark truncate">
            {{ profile.user_id }}
          </div>
        </div>
        <i class="hidden xl:block fas fa-angle-down ml-auto text-lg"></i>
      </button>
      <div
        v-if="dropdown"
        class="absolute bottom-0 left-0 w-80 rounded-lg shadow-md border-lightest bg-white dark:bg-darktheme-card mastodon:bg-mastodon-card mb-16"
      >
        <button
          @click="dropdown = false"
          class="p-3 flex items-center w-full hover:bg-lightest"
        >
          <img
            :src="profile.avatar || '/default_profile.png'"
            class="w-10 h-10 rounded-full object-cover bg-transparent"
          />
          <div class="ml-4">
            <p class="text-left text-sm font-bold leading-tight">
              {{ profile.username }}
            </p>
            <p class="text-left text-sm leading-tight text-dark">
              {{ profile.user_id }}
            </p>
          </div>
          <i class="fas fa-check ml-auto text-blue"></i>
        </button>
        <button
          class="w-full text-left hover:bg-lightest border-t border-lighter p-3 text-sm"
          @click="toggleDarkMode"
        >
          Toggle Theme
        </button>
        <button
          @click="signInByQR"
          class="w-full text-left hover:bg-lightest border-t border-lighter p-3 text-sm"
        >
          Sign in by QR-code
        </button>
        <button
          @click="signOut"
          class="w-full text-left hover:bg-lightest border-t border-lighter p-3 text-sm text-red-600"
        >
          Sign out
        </button>
      </div>
    </div>
  </nav>
</template>

<script>
import QRCodeModal from "@/components/QRCodeModal.vue";
import {warpnetService} from "@/service/service";

export default {
  name: "SideNav",
  components: {
    QRCodeModal,
  },
  data() {
    return {
      dropdown: false,
      profile: {},
      newMessages: 0,
      newNotifications: 0,
      qrModalOpen: false,
      qrCode: "",
      unsubscribeNotifications: null,
      unsubscribeOwner: null,
    };
  },
  watch: {
    $route(to) {
      if (to && (to.name === 'Chats' || to.name === 'Messages')) {
        this.newMessages = 0;
        warpnetService.markMessageNotificationsRead().catch(() => {});
      }
    },
  },
  mounted() {
    const theme = localStorage.getItem("theme");
    if (theme === "dark" || (!theme && window.matchMedia("(prefers-color-scheme: dark)").matches)) {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
    // Close the account dropdown on outside click / Escape.
    this._onDocClick = (e) => {
      if (!this.dropdown) return;
      const menu = this.$refs.accountMenu;
      if (menu && !menu.contains(e.target)) {
        this.dropdown = false;
      }
    };
    this._onDocKeyup = (e) => {
      if (e.key === "Escape" && this.dropdown) {
        this.dropdown = false;
      }
    };
    document.addEventListener("click", this._onDocClick);
    window.addEventListener("keyup", this._onDocKeyup);
  },
  methods: {
    async open(target) {
      const current = this.$route.name;
      if (
        target !== current ||
        this.$route.params.id !== this.profile.user_id
      ) {
        this.$router.push({
          name: target,
          params: {
            id: this.profile.user_id,
          },
        });
      }
    },
    async openTweetCompose() {
      await this.$router.push({
        name: 'Home',
        query: { compose: Date.now().toString() },
      });
    },
    toggleDarkMode() {
      const html = document.documentElement;
      if (html.classList.contains("dark")) {
        html.classList.remove("dark");
        localStorage.setItem("theme", "light");
      } else {
        html.classList.add("dark");
        localStorage.setItem("theme", "dark");
      }
    },
    signInByQR() {
        // warpnetService.getQR() is a synchronous in-memory lookup,
        // no await needed.
        this.qrCode = warpnetService.getQR();
        this.qrModalOpen = true;
    },
    async closeQR() {
      this.qrModalOpen = false
    },
    async signOut() {
      this.dropdown = false;
      try {
        await warpnetService.logoutUser();
      } catch (err) {
        console.error('Failed to sign out:', err);
      }
      this.$router.push({ name: 'Root' });
    },
  },
  async created() {
    console.log("loading component:", this.$options.name);
    // Copy the owner object: the raw one lives in the service's non-reactive
    // stateMap and is shared; rendering it directly means profile edits that
    // touch that object bypass this component's reactivity.
    this.profile = { ...warpnetService.getOwnerProfile() };

    // Re-render on profile edits (username/avatar). setOwnerProfile notifies
    // subscribers; without this the sidebar keeps the pre-edit name/avatar
    // until the next route change.
    this.unsubscribeOwner = warpnetService.subscribeOwner(async (owner) => {
      if (!owner) return;
      const prevAvatarKey = this.profile?.avatar_key;
      this.profile = { ...this.profile, ...owner };
      if (owner.avatar_key && owner.avatar_key !== prevAvatarKey) {
        try {
          this.profile.avatar = await warpnetService.getImage({userId: this.profile.user_id, key: owner.avatar_key});
        } catch (e) {
          console.warn("sidenav: failed to refresh avatar:", e);
        }
      }
    });

    try {
      if (typeof sessionStorage !== "undefined" &&
          sessionStorage.getItem("warpnet:show-pairing-onboarding") === "1") {
        sessionStorage.removeItem("warpnet:show-pairing-onboarding");
        await this.signInByQR();
      }
    } catch (error) {
      console.error("Failed to open pairing onboarding:", error);
    }

    const fullProfile = await warpnetService.getProfile(this.profile.user_id);
    try {
      if (fullProfile && !fullProfile.code && fullProfile.avatar_key) {
        this.profile.avatar = await warpnetService.getImage({userId:this.profile.user_id, key:fullProfile.avatar_key});
      } else {
        this.profile.avatar = null;
      }
    } catch (error) {
      console.error("Failed to load full profile:", error);
      this.profile.avatar = null;
    }

    this.unsubscribeNotifications = warpnetService.subscribeNotifications((resp) => {
      const items = (resp && resp.notifications) || [];
      const unreadMessages = items.filter((n) => n && n.type === 'message' && !n.is_read).length;
      const onMessages = this.$route && (this.$route.name === 'Chats' || this.$route.name === 'Messages');
      this.newMessages = onMessages ? 0 : unreadMessages;
      this.newNotifications = Math.max(0, (resp.unread_count || 0) - unreadMessages);
    });

    await warpnetService.getNotifications(true)
  },
  beforeUnmount() {
    if (this.unsubscribeNotifications) {
      this.unsubscribeNotifications();
      this.unsubscribeNotifications = null;
    }
    if (this.unsubscribeOwner) {
      this.unsubscribeOwner();
      this.unsubscribeOwner = null;
    }
    if (this._onDocClick) {
      document.removeEventListener("click", this._onDocClick);
      this._onDocClick = null;
    }
    if (this._onDocKeyup) {
      window.removeEventListener("keyup", this._onDocKeyup);
      this._onDocKeyup = null;
    }
  },
};
</script>
