<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div v-if="deleted" class="hidden"></div>
  <div v-if="!deleted && tweet.retweeted_by && tweet.retweeted_by !== '' && !tweet.quoted_tweet_id">
    <!-- Retweet header. Quote-style retweets (those that carry
         quoted_tweet_id) render as the retweeter's own tweet with
         an embedded source preview below, so no "X Retweeted"
         header. -->
    <div class="pt-4 pl-4 flex flex-row">
      <div class="w-12 mr-4 flex justify-end">
        <i class="text-sm pt-1 fas fa-retweet text-dark"></i>
      </div>
      <p class="text-sm text-dark">{{ label }}</p>
    </div>
  </div>
  <div
      v-if="!deleted"
      ref="tweetRoot"
      class="w-full p-2 pt-1 pb-1 md:p-4 md:pt-2 md:pb-2 border-b hover:bg-lightest flex cursor-pointer"
      @click="onBodyClick"
  >
    <div class="flex-none mr-2 md:mr-4 pt-1">
      <button type="button" @click.stop="gotoProfile(tweet.user_id)" class="flat-btn" aria-label="View profile">
        <img
          :src="profile.avatar || '/default_profile.png'"
          class="h-12 w-12 rounded-full flex-none object-cover bg-transparent"
          :alt="`${tweet.username || 'User'} avatar`"
        />
      </button>
    </div>
    <div class="w-full">
      <div class="flex items-center w-full">
        <button type="button" @click.stop="gotoProfile(tweet.user_id)" class="font-semibold hover:underline flat-btn">
          {{ tweet.username || 'Anonymous' }}
        </button>
        <p class="hidden md:block text-sm text-dark ml-2">
          @{{ tweet.user_id }}
        </p>
        <p class="text-sm text-dark ml-2">·</p>
        <p class="text-sm text-dark ml-2">{{ $filters.timeago(tweet.created_at) }}</p>
        <span v-if="tweet.pinned" class="ml-2 text-xs text-blue" title="Pinned tweet">
          <i class="fas fa-thumbtack" aria-hidden="true"></i> Pinned
        </span>
        <div class="relative ml-auto">
          <button type="button" @click.stop="showDropdown = !showDropdown" class="rounded-full w-7 h-7 flex items-center justify-center hover:bg-lighter flat-btn" aria-label="Tweet options" :aria-expanded="showDropdown">
            <i class="fas fa-angle-down text-sm text-dark" aria-hidden="true"></i>
          </button>
          <div v-if="showDropdown" class="absolute right-0 mt-2 w-52 bg-white rounded-md shadow-lg py-1 z-10">
            <button type="button" @click.stop="toggleBookmark" class="block w-full text-left px-4 py-2 text-sm hover:bg-gray-100 flat-btn">
              {{ bookmarked ? 'Remove bookmark' : 'Bookmark' }}
            </button>
            <template v-if="isOwner">
              <button type="button" @click.stop="togglePin" class="block w-full text-left px-4 py-2 text-sm hover:bg-gray-100 flat-btn">
                {{ tweet.pinned ? 'Unpin from profile' : 'Pin to profile' }}
              </button>
              <button type="button" @click.stop="openEdit" class="block w-full text-left px-4 py-2 text-sm hover:bg-gray-100 flat-btn">Edit tweet</button>
              <button type="button" @click.stop="deleteTweet" class="block w-full text-left px-4 py-2 text-sm text-red-600 hover:bg-gray-100 flat-btn">Delete tweet</button>
            </template>
            <button v-if="!isOwner && !tweet.parent_id" type="button" @click.stop="openReport" class="block w-full text-left px-4 py-2 text-sm text-red-600 hover:bg-gray-100 flat-btn">Report tweet</button>
          </div>
        </div>
        <ReportDialog
          :show="showReportDialog"
          title="Report tweet"
          @submit="submitReport"
          @cancel="showReportDialog = false"
        />
      </div>
      <p v-if="!tweet.moderation || tweet.moderation?.is_ok" :key="tweet.text" class="pb-2" v-linkify>
        {{ tweet.text }}
      </p>
      <p v-else class="pb-2 bg-red-300">
        Moderated: {{ tweet.moderation.reason }}.
      </p>
      <div
        v-if="tweet.quoted_tweet_id"
        class="mb-2 border border-lighter rounded p-3 bg-lightest text-sm"
        :class="quotedUnavailable ? 'opacity-60' : 'hover:bg-lighter cursor-pointer'"
        @click.stop="onQuotedClick"
      >
        <template v-if="quotedUnavailable">
          <p class="font-bold text-dark italic">Quoted tweet unavailable</p>
          <p class="text-xs text-dark mt-1">The original tweet was edited after this quote was posted.</p>
        </template>
        <template v-else>
          <p class="font-bold">
            {{ quotedSourceUsername || 'Quoted tweet' }}
            <span class="text-dark font-normal ml-1">@{{ tweet.quoted_user_id }}</span>
          </p>
          <p v-if="quotedSourceText" class="mt-1 line-clamp-4">{{ quotedSourceText }}</p>
          <p v-else class="mt-1 text-dark italic">View quoted tweet</p>
        </template>
      </div>
      <div v-if="tweetImages.length === 1" class="mt-2">
        <img
            :src="tweetImages[0]"
            alt="Tweet image"
            class="rounded-lg max-w-full border border-lighter cursor-zoom-in"
            @click.stop="openImageView(tweetImages[0])"
        />
      </div>
      <div v-else-if="tweetImages.length === 2" class="mt-2 grid grid-cols-2 gap-1 rounded-lg overflow-hidden border border-lighter">
        <img v-for="(img, i) in tweetImages" :key="i" :src="img" alt="Tweet image" class="w-full h-48 object-cover cursor-zoom-in" @click.stop="openImageView(img)" />
      </div>
      <div v-else-if="tweetImages.length === 3" class="mt-2 grid grid-cols-2 gap-1 rounded-lg overflow-hidden border border-lighter" style="height:300px">
        <img :src="tweetImages[0]" alt="Tweet image" class="row-span-2 w-full h-full object-cover cursor-zoom-in" style="grid-row: span 2" @click.stop="openImageView(tweetImages[0])" />
        <img :src="tweetImages[1]" alt="Tweet image" class="w-full h-full object-cover cursor-zoom-in" @click.stop="openImageView(tweetImages[1])" />
        <img :src="tweetImages[2]" alt="Tweet image" class="w-full h-full object-cover cursor-zoom-in" @click.stop="openImageView(tweetImages[2])" />
      </div>
      <div v-else-if="tweetImages.length >= 4" class="mt-2 grid grid-cols-2 gap-1 rounded-lg overflow-hidden border border-lighter">
        <img v-for="(img, i) in tweetImages.slice(0, 4)" :key="i" :src="img" alt="Tweet image" class="w-full h-36 object-cover cursor-zoom-in" @click.stop="openImageView(img)" />
      </div>
      <div
        v-if="viewedImage"
        class="fixed inset-0 bg-black bg-opacity-80 z-50 flex items-center justify-center p-4 cursor-pointer"
        role="dialog"
        aria-modal="true"
        aria-label="Tweet image full view"
        @click.stop="closeImageView"
      >
        <img :src="viewedImage" alt="Tweet image (full size)" class="max-w-full max-h-full object-contain rounded" />
      </div>
      <div class="flex w-full mt-1">
        <div class="flex items-center text-sm text-dark w-1/4">
          <span
            class="mr-2 rounded-full w-9 h-9 flex items-center justify-center"
            aria-label="Replies"
            title="Replies"
          >
            <i class="far fa-comment" aria-hidden="true"></i>
          </span>
          <p v-if="getRepliesCount(tweet.id) > 0">{{ getRepliesCount(tweet.id) || '?' }}</p>
        </div>
        <div class="flex items-center text-sm text-dark w-1/4">
          <div class="relative">
            <button
              @click.stop="onRetweetClick"
              type="button"
              class="mr-2 rounded-full w-9 h-9 flex items-center justify-center hover:bg-green-100 transition-colors"
              :aria-label="retweeted ? 'Undo retweet' : 'Retweet'"
              :title="retweeted ? 'Undo retweet' : 'Retweet'"
            >
              <i
                class="fas fa-retweet"
                :class="retweeted ? 'text-green-500' : ''"
                aria-hidden="true"
              ></i>
            </button>
            <div
              v-if="showRetweetMenu"
              class="absolute left-0 mt-2 w-40 bg-white rounded-md shadow-lg py-1 z-10"
            >
              <button
                type="button"
                @click.stop="plainRetweet"
                class="block w-full text-left px-4 py-2 text-sm hover:bg-gray-100 flat-btn"
              >Retweet</button>
              <button
                type="button"
                @click.stop="openQuoteOverlay"
                class="block w-full text-left px-4 py-2 text-sm hover:bg-gray-100 flat-btn"
              >Quote</button>
            </div>
          </div>
          <button
            v-if="getRetweetsCount(tweet.id) > 0"
            type="button"
            class="hover:underline flat-btn"
            @click.stop="showRetweetersOverlay = true"
          >{{ getRetweetsCount(tweet.id) || '?'}}</button>
        </div>
        <div class="flex items-center text-sm text-dark w-1/4">
          <button
            @click.stop="like()"
            type="button"
            class="mr-2 rounded-full w-9 h-9 flex items-center justify-center hover:bg-red-100 transition-colors"
            :aria-label="liked ? 'Unlike' : 'Like'"
            :title="liked ? 'Unlike' : 'Like'"
          >
            <i class="fas fa-heart" :class="liked ? 'text-red-600' : ''" aria-hidden="true"></i>
          </button>
          <button
            v-if="getLikesCount(tweet.id) > 0"
            type="button"
            class="hover:underline flat-btn"
            @click.stop="showLikersOverlay = true"
          >{{ getLikesCount(tweet.id) }}</button>
        </div>
        <div class="flex items-center text-sm text-dark w-1/4">
          <span
            class="mr-2 rounded-full w-9 h-9 flex items-center justify-center"
            aria-label="Views"
            title="Views"
          >
            <i class="far fa-eye" aria-hidden="true"></i>
          </span>
          <p>{{ getViewsCount(tweet.id) }}</p>
        </div>
      </div>
    </div>
    <ReplyOverlay
        v-if="showReplyOverlay"
        :tweet="tweet" :profile="profile"
        :showReplyOverlay="showReplyOverlay"
        @close="showReplyOverlay = false"
        @replied="loadTweetStats(tweet.id, tweet.user_id)"
    />
    <LikersOverlay
        :show="showLikersOverlay"
        :tweetId="tweet.id"
        :ownerUserId="tweet.user_id"
        @close="showLikersOverlay = false"
    />
    <RetweetersOverlay
        :show="showRetweetersOverlay"
        :tweetId="tweet.id"
        :ownerUserId="tweet.user_id"
        @close="showRetweetersOverlay = false"
    />
    <EditTweetOverlay
        v-if="showEditOverlay"
        :show="showEditOverlay"
        :tweet="tweet"
        @close="showEditOverlay = false"
        @saved="onTweetEdited"
    />
    <QuoteOverlay
        v-if="showQuoteOverlay"
        :show="showQuoteOverlay"
        :tweet="tweet"
        @close="showQuoteOverlay = false"
        @posted="onQuotePosted"
    />
  </div>
</template>

<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";

export default {
  name: "Tweet",
  props: ["tweet"],
  components: {
    ReplyOverlay: defineAsyncComponent(() => import('./ReplyOverlay.vue')),
    LikersOverlay: defineAsyncComponent(() => import('./LikersOverlay.vue')),
    RetweetersOverlay: defineAsyncComponent(() => import('./RetweetersOverlay.vue')),
    EditTweetOverlay: defineAsyncComponent(() => import('./EditTweetOverlay.vue')),
    QuoteOverlay: defineAsyncComponent(() => import('./QuoteOverlay.vue')),
    ReportDialog: defineAsyncComponent(() => import('./ReportDialog.vue')),
  },
  data() {
    return {
      profile: {},
      showReplyOverlay: false,
      showLikersOverlay: false,
      showRetweetersOverlay: false,
      showEditOverlay: false,
      showQuoteOverlay: false,
      showDropdown: false,
      showReportDialog: false,
      showRetweetMenu: false,
      quotedSourceText: '',
      quotedSourceUsername: '',
      quotedUnavailable: false,
      deleted: false,
      isOwner: false,
      bookmarked: false,
      label: "You Retweeted",
      liked: false,
      retweeted: false,
      likesCount: new Map(),
      retweetsCount: new Map(),
      repliesCount: new Map(),
      viewsCount: new Map(),
      tweetImages: [],
      viewedImage: null,
      viewObserver: null,
      viewRecorded: false,
      viewInFlight: false,
      statsRetried: false,
    };
  },
  methods: {
    async refreshInteractionState() {
      const owner = warpnetService.getOwnerProfile();
      if (!owner) {
        this.liked = false;
        this.retweeted = false;
        return;
      }

      this.liked = await warpnetService.hasLiker(this.tweet.id, owner.user_id);
      this.retweeted = this.tweet.retweeted_by === owner.user_id
        || await warpnetService.hasRetweeter(this.tweet.id, owner.user_id);
    },
    gotoProfile(tweetUserId) {
      this.$router.push({
        name: "Profile",
        params: {
          id: tweetUserId,
        },
      });
    },
    openTweetPage() {
      this.$router.push({
        name: 'Tweet',
        params: { id: this.tweet.id },
        query: {
          u: this.tweet.user_id,
          // Pass parent/root so Tweet.vue can use getReply for non-root
          // entries (replies aren't stored as standalone tweets under
          // the user's TWEETS namespace, so getTweet returns 404).
          parent: this.tweet.parent_id || '',
          root: this.tweet.root_id || '',
        },
      });
    },
    onBodyClick() {
      if (this.showDropdown || this.showRetweetMenu) {
        this.showDropdown = false;
        this.showRetweetMenu = false;
        return;
      }
      this.openTweetPage();
    },
    // Retweet button drives a small popover that offers a plain
    // retweet vs. a quote retweet. When the user already retweeted
    // (or quoted) this tweet, clicking the button just toggles the
    // retweet off without showing the menu.
    onRetweetClick() {
      this.showDropdown = false;
      if (this.retweeted) {
        this.retweet();
        return;
      }
      this.showRetweetMenu = !this.showRetweetMenu;
    },
    async plainRetweet() {
      this.showRetweetMenu = false;
      if (!this.retweeted) {
        await this.retweet();
      }
    },
    async toggleBookmark() {
      this.showDropdown = false;
      try {
        if (this.bookmarked) {
          await warpnetService.unbookmarkTweet(this.tweet.id);
          this.bookmarked = false;
        } else {
          await warpnetService.bookmarkTweet(this.tweet.id, this.tweet.user_id);
          this.bookmarked = true;
        }
      } catch (err) {
        console.error(`failed to toggle bookmark on [${this.tweet.id}]`, err);
      }
    },
    async togglePin() {
      this.showDropdown = false;
      try {
        if (this.tweet.pinned) {
          await warpnetService.unpinTweet(this.tweet.id);
          this.tweet.pinned = false;
        } else {
          await warpnetService.pinTweet(this.tweet.id);
          this.tweet.pinned = true;
        }
      } catch (err) {
        console.error(`failed to toggle pin on [${this.tweet.id}]`, err);
      }
    },
    openEdit() {
      this.showDropdown = false;
      this.showEditOverlay = true;
    },
    openQuoted() {
      if (!this.tweet.quoted_tweet_id) return;
      this.$router.push({
        name: 'Tweet',
        params: { id: this.tweet.quoted_tweet_id },
        query: { u: this.tweet.quoted_user_id || '' },
      });
    },
    // Clicking an "unavailable" quoted preview is a no-op so the user
    // doesn't get bounced to a tweet that's been edited out from
    // under them.
    onQuotedClick() {
      if (this.quotedUnavailable) return;
      this.openQuoted();
    },
    async loadQuotedSource() {
      if (!this.tweet.quoted_tweet_id || !this.tweet.quoted_user_id) return;
      try {
        const src = await warpnetService.getTweet({
          tweetId: this.tweet.quoted_tweet_id,
          userId: this.tweet.quoted_user_id,
        });
        if (!src || !src.id) {
          this.quotedUnavailable = true;
          return;
        }
        // If the source has been edited *after* this quote was
        // posted, the quote no longer reflects what the user
        // actually quoted — mark it as unavailable.
        const sourceEdited = src.updated_at
          && this.tweet.created_at
          && new Date(src.updated_at) > new Date(this.tweet.created_at);
        if (sourceEdited) {
          this.quotedUnavailable = true;
          return;
        }
        this.quotedSourceText = src.text || '';
        this.quotedSourceUsername = src.username || '';
      } catch (err) {
        console.warn('failed to load quoted source:', err);
        this.quotedUnavailable = true;
      }
    },
    openQuoteOverlay() {
      this.showDropdown = false;
      this.showRetweetMenu = false;
      this.showQuoteOverlay = true;
    },
    async onQuotePosted() {
      try {
        await this.loadTweetStats(this.tweet.id, this.tweet.user_id);
      } catch (err) {
        console.error(`failed to refresh tweet stats [${this.tweet.id}]`, err);
      }
    },
    openImageView(img) {
      this.viewedImage = img;
      this._onLightboxKeyup = (e) => {
        if (e.key === "Escape") this.closeImageView();
      };
      window.addEventListener("keyup", this._onLightboxKeyup);
    },
    closeImageView() {
      this.viewedImage = null;
      if (this._onLightboxKeyup) {
        window.removeEventListener("keyup", this._onLightboxKeyup);
        this._onLightboxKeyup = null;
      }
    },
    onTweetEdited(updated) {
      if (updated && updated.text) {
        this.tweet.text = updated.text;
      }
    },
    async get() {
      let t = undefined
      if (!this.tweet.parent_id || this.tweet.parent_id === this.tweet.root_id) {
        const getObject = {
          userId: this.tweet.user_id,
          tweetId: this.tweet.id,
        }
        t =  await warpnetService.getTweet(getObject);
      } else {
        const getObject = {
          parentId: this.tweet.parent_id,
          rootId: this.tweet.root_id,
          replyId: this.tweet.id,
          userId: this.tweet.user_id,
        }
        t =  await warpnetService.getReply(getObject);
      }
      this.showReplyOverlay = true;
    },
    openReport() {
      this.showDropdown = false;
      this.showReportDialog = true;
    },
    async submitReport(reason) {
      try {
        // ModerationObjectType: tweets are type 1. Replies hide the
        // Report button entirely (the moderator side has no
        // reply-fetch wiring yet), so this only ever runs for root
        // tweets.
        const profile = await warpnetService.getProfile(this.tweet.user_id);
        await warpnetService.report({
          type: 1,
          objectId: this.tweet.id,
          targetUserId: this.tweet.user_id,
          targetNodeId: profile?.node_id || '',
          reason,
        });
      } catch (err) {
        console.error('Failed to send report:', err);
      } finally {
        this.showReportDialog = false;
      }
    },
    async deleteTweet() {
      this.showDropdown = false;
      try {
        if (!this.tweet.parent_id || this.tweet.parent_id === '') {
          await warpnetService.deleteTweet({
            userId: this.tweet.user_id,
            tweetId: this.tweet.id,
          });
        } else {
          await warpnetService.deleteReply({
            userId: this.tweet.user_id,
            parentId: this.tweet.parent_id,
            rootId: this.tweet.root_id,
            replyId: this.tweet.id,
          });
        }
        this.deleted = true;
      } catch (err) {
        console.error('Failed to delete tweet:', err);
      }
    },
    replyToTweet() {
      this.showReplyOverlay = true;
    },
    async retweet() {
      const owner = warpnetService.getOwnerProfile();
      if (!owner) return;
      const retweetObject = {
        tweetId: this.tweet.id,
        userId: this.tweet.user_id,
        username: this.tweet.username,
        text: this.tweet.text,
      }
      const alreadyRetweeted = this.retweeted
      try {
        if (!alreadyRetweeted) {
          await warpnetService.retweetTweet(retweetObject);
          await warpnetService.setRetweeter(this.tweet.id, owner.user_id, owner)
          this.tweet.retweeted_by = owner.user_id;
          this.retweeted = true;
        } else {
          await warpnetService.unretweetTweet(this.tweet.id);
          await warpnetService.deleteRetweeter(this.tweet.id, owner.user_id)
          this.tweet.retweeted_by = null;
          this.retweeted = false;
        }
      } catch (err) {
        console.error(`failed to retweet/unretweet tweet [${this.tweet.id}]`, err);
      }
      try {
        await this.loadTweetStats(this.tweet.id, this.tweet.user_id);
      } catch (err) {
        console.error(`failed to refresh tweet stats [${this.tweet.id}]`, err);
      }
    },
    async like() {
      if (this.tweet.network && this.tweet.network !== "warpnet") {
        return
      }
      const owner = warpnetService.getOwnerProfile();
      if (!owner) return;
      let likesNum = 0
      const alreadyLiked = this.liked
      try {
        if (!alreadyLiked) {
          likesNum = await warpnetService.likeTweet(this.tweet.id, this.tweet.user_id)
        } else {
          likesNum = await warpnetService.unlikeTweet(this.tweet.id, this.tweet.user_id)
        }
      } catch (err) {
        console.error(`failed to like/unlike tweet [${this.tweet.id}]`, err);
        await this.loadTweetStats(this.tweet.id, this.tweet.user_id);
        return;
      }
      if (!alreadyLiked) {
        await warpnetService.setLiker(this.tweet.id, owner.user_id, owner)
        this.liked = true;
      } else {
        await warpnetService.deleteLiker(this.tweet.id, owner.user_id)
        this.liked = false;
      }

      this.likesCount.set(this.tweet.id, likesNum);
    },
    getLikesCount(tweetId) {
      return this.likesCount.get(tweetId);
    },
    getRetweetsCount(tweetId) {
      return this.retweetsCount.get(tweetId);
    },
    getRepliesCount(tweetId) {
      return this.repliesCount.get(tweetId);
    },
    getViewsCount(tweetId) {
      return this.viewsCount.get(tweetId) || 0;
    },
    async loadTweetStats(tweetId, userId) {
      const stats = await warpnetService.getTweetStats(tweetId, userId);
      if (!stats || !stats.tweet_id) {
        // Transient handler/stream error surfaces as an empty body; a
        // single delayed retry keeps the counters from silently showing
        // zeros until the next full reload.
        if (!this.statsRetried) {
          this.statsRetried = true;
          this._statsRetryTimer = setTimeout(() => {
            this._statsRetryTimer = null;
            this.loadTweetStats(tweetId, userId).catch(() => {});
          }, 2500);
        }
        return;
      }

      this.likesCount.set(stats.tweet_id, stats.likes_count);
      this.retweetsCount.set(stats.tweet_id, stats.retweets_count);
      this.repliesCount.set(stats.tweet_id, stats.replies_count);
      // Views are monotonically non-decreasing: a stale read raced with
      // our own RecordView would otherwise clobber the higher value.
      const incoming = stats.views_count || 0;
      const current = this.viewsCount.get(stats.tweet_id) || 0;
      if (incoming > current) {
        this.viewsCount.set(stats.tweet_id, incoming);
      }
    },
    async recordView() {
      if (this.viewRecorded || this.viewInFlight) return;
      this.viewInFlight = true;
      try {
        const count = await warpnetService.viewTweet(this.tweet.id, this.tweet.user_id);
        // viewTweet returns `null` on any failure; only mark the view
        // recorded (and stop observing) when the backend confirms.
        if (count === null) return;
        // Monotonic: never regress a higher local count when a stale
        // loadTweetStats response lands after us.
        const current = this.viewsCount.get(this.tweet.id) || 0;
        if (count > current) {
          this.viewsCount.set(this.tweet.id, count);
        }
        this.viewRecorded = true;
        if (this.viewObserver) {
          this.viewObserver.disconnect();
          this.viewObserver = null;
        }
      } catch (err) {
        // Fail silently per spec - never break the page on a view miss.
        // Leave viewRecorded false so a later intersection retries.
        console.error(`failed to record view for tweet [${this.tweet.id}]`, err);
      } finally {
        this.viewInFlight = false;
      }
    },
    setupViewObserver() {
      if (typeof window === 'undefined' || typeof window.IntersectionObserver === 'undefined') {
        // Without IntersectionObserver fall back to recording immediately.
        this.recordView();
        return;
      }
      const target = this.$refs.tweetRoot;
      if (!target) return;

      // We want "the tweet is meaningfully on screen". Two signals
      // satisfy that:
      //   - at least half of the tweet itself is visible (short tweets), or
      //   - the visible slice of the tweet covers at least half of the
      //     viewport (tall tweets / multi-image — intersectionRatio
      //     against the tweet can never reach 0.5 when the tweet is
      //     more than 2× the viewport height).
      //
      // The observer callback only fires when intersectionRatio
      // crosses one of these thresholds, so the list must contain a
      // value at-or-below max(intersectionRatio) for any tweet we
      // expect to record. Compute a per-element low threshold from
      // the actual element/viewport heights so even a 200×-viewport-
      // tall tweet produces a callback at the fill-viewport point.
      const visibleFraction = 0.5;
      const targetHeight = target.getBoundingClientRect().height || 0;
      const viewportHeight = (typeof window !== 'undefined'
          && (window.innerHeight || (document && document.documentElement && document.documentElement.clientHeight)))
          || 0;
      const fillRatio = (targetHeight > 0 && viewportHeight > 0)
          ? (viewportHeight * visibleFraction) / targetHeight
          : 0;
      const thresholds = Array.from(new Set([
          0, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 0.75, 1,
          // For ultra-tall tweets the static list bottoms out at
          // 0.005; supplement with values around the actual fill
          // point so we never silently miss the crossing.
          ...(fillRatio > 0 && fillRatio < 0.005
              ? [Math.max(fillRatio / 2, 1e-6), fillRatio]
              : []),
      ])).filter(t => t >= 0 && t <= 1).sort((a, b) => a - b);
      this.viewObserver = new IntersectionObserver((entries) => {
        for (const entry of entries) {
          if (!entry.isIntersecting) continue;
          const root = entry.rootBounds;
          const fallbackHeight = (typeof window !== 'undefined' && window.innerHeight) || 0;
          const rootHeight = (root && root.height > 0) ? root.height : fallbackHeight;
          const fillsViewport = rootHeight > 0
              && (entry.intersectionRect.height / rootHeight) >= visibleFraction;
          if (entry.intersectionRatio >= visibleFraction || fillsViewport) {
            this.recordView();
            break;
          }
        }
      }, { threshold: thresholds });
      this.viewObserver.observe(target);
    },
  },
  async created() {
    console.log("loading component:", this.$options.name);
    console.log("loading tweet:", JSON.stringify(this.tweet));
    if (!this.tweet || !this.tweet.id || !this.tweet.user_id) {
      // Defensive: nothing to render against. Avoid firing
      // getProfile/getTweetStats with empty ids — the backend rejects
      // those and logs spurious errors.
      return;
    }
    // Profile/avatar/image loads may transiently fail (author node
    // unreachable); never let that abort the stats/interaction loads
    // below, or the row renders with zeroed counters until a reload.
    try {
      this.profile = await warpnetService.getProfile(this.tweet.user_id);

      if (this.tweet.retweeted_by && this.tweet.retweeted_by !== this.profile.id) {
        const retweeter = await warpnetService.getProfile(this.tweet.retweeted_by)
        this.label = `${retweeter.username} Retweeted`;
      }

      const imageKeys = (this.tweet.image_keys && this.tweet.image_keys.length > 0)
          ? this.tweet.image_keys
          : [];
      const loadedImages = await Promise.all(
          imageKeys.map(key => warpnetService.getImage({userId: this.tweet.user_id, key}))
      );
      this.tweetImages = loadedImages.filter(img => img);
      this.profile.avatar = await warpnetService.getImage({userId: this.profile.id, key: this.profile.avatar_key})
    } catch (err) {
      console.error(`failed to load tweet author assets [${this.tweet.id}]`, err);
    }

    console.log("final tweet:", JSON.stringify(this.tweet));

    const owner = warpnetService.getOwnerProfile();
    this.isOwner = owner && owner.user_id === this.tweet.user_id;

    try {
      await this.loadTweetStats(this.tweet.id, this.tweet.user_id);
      await this.refreshInteractionState();
    } catch (err) {
      console.error(`failed to load tweet stats [${this.tweet.id}]`, err);
    }

    if (this.tweet.quoted_tweet_id) {
      await this.loadQuotedSource();
    }
  },
  mounted() {
    this.$nextTick(() => this.setupViewObserver());
  },
  beforeUnmount() {
    if (this.viewObserver) {
      this.viewObserver.disconnect();
      this.viewObserver = null;
    }
    if (this._onLightboxKeyup) {
      window.removeEventListener("keyup", this._onLightboxKeyup);
      this._onLightboxKeyup = null;
    }
    if (this._statsRetryTimer) {
      clearTimeout(this._statsRetryTimer);
      this._statsRetryTimer = null;
    }
  },
};
</script>
