<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div>
    <div v-for="section in sections" :key="section.key" class="w-full rounded-lg bg-lightest my-4">
      <div class="p-3 flex items-center">
        <p class="text-lg font-bold">Who to follow</p>
        <img v-if="section.key === 'warpnet'" src="@/assets/logo-transparent.png" alt="Warpnet" class="w-5 h-5 ml-2 object-contain" />
        <i v-else class="fab fa-mastodon text-lg ml-2 text-[color:var(--gd-trim)]" role="img" aria-label="Mastodon"></i>
      </div>
      <!-- No v-if here: on one element Vue 3 evaluates v-if BEFORE v-for, so
           "profile" resolved to the component prop, not the loop item — the
           whole list was gated on an unrelated prop. -->
      <div v-for="profile in section.profiles" :key="profile.id" class="w-full flex hover:bg-lighter transition-colors duration-150 p-3 border-t border-lighter">
        <img
          @click="pushToProfilePage(profile.id)"
          :src="profile.avatar || '/default_profile.png'"
          class="w-12 h-12 rounded-full cursor-pointer object-cover bg-transparent"
          :alt="profile.username"
        />
        <div class="hidden lg:block ml-4 min-w-0">
          <p @click="pushToProfilePage(profile.id)" class="text-left text-sm font-bold leading-tight cursor-pointer truncate max-w-[9rem]">{{ profile.username }}</p>
          <p class="text-left text-sm leading-tight text-dark truncate max-w-[9rem]">{{ profile.id.slice(0, 8) }}...</p>
        </div>
        <button
          v-if="!isFollowing(profile.id)"
          @click="follow(profile.id)"
          :disabled="isPending(profile.id)"
          class="ml-auto text-sm text-blue font-bold px-4 py-1 rounded-full border border-blue m-2 disabled:opacity-50"
        >
          Follow
        </button>
        <button
            v-if="isFollowing(profile.id)"
            @click="unfollow(profile.id)"
            :disabled="isPending(profile.id)"
            class="ml-auto text-sm font-bold px-4 py-1 rounded-full border border-blue bg-blue text-white hover:bg-red-600 hover:border-red-600 m-2 disabled:opacity-50 group"
        >
          <span class="group-hover:hidden">Following</span>
          <span class="hidden group-hover:inline">Unfollow</span>
        </button>
      </div>
      <button
          @click="showMore()"
          class="p-3 w-full hover:bg-lighter text-left text-blue border-t border-lighter"
      >
        Show More
      </button>
    </div>
  </div>
</template>

<script>
import {warpnetService} from "@/service/service";
import {toast} from "@/lib/toast";
import {isMastodonUser} from "@/lib/network";

const sectionLimit = 5;

export default {
  name: 'WhoToFollow',
  props: ["profile"],
  data() {
    return {
      warpnetProfiles: [],
      mastodonProfiles: [],
      followingStatus: new Map(),
      pending: new Set(),
    };
  },
  computed: {
    sections() {
      return [
        {key: 'warpnet', profiles: this.warpnetProfiles},
        {key: 'mastodon', profiles: this.mastodonProfiles},
      ].filter(s => s.profiles.length > 0);
    },
  },
  methods: {
    async pushToProfilePage(profileId) {
      this.$router.push({
        name: "Profile",
        params: {
          id: profileId
        }
      });
    },
    isFollowing(profileId) {
      return this.followingStatus.get(profileId) || false
    },
    isPending(profileId) {
      return this.pending.has(profileId);
    },
    async follow(profileId) {
      if (this.pending.has(profileId)) return;
      this.pending.add(profileId);
      this.followingStatus.set(profileId, true); // optimistic
      try {
        await warpnetService.followUser(profileId);
      } catch (err) {
        console.error('Failed to follow:', err);
        this.followingStatus.set(profileId, false); // rollback
        toast.error(err?.message || "Couldn't follow this user. Please try again.");
      } finally {
        this.pending.delete(profileId);
      }
    },
    async unfollow(profileId) {
      if (this.pending.has(profileId)) return;
      this.pending.add(profileId);
      this.followingStatus.set(profileId, false); // optimistic
      try {
        await warpnetService.unfollowUser(profileId);
      } catch (err) {
        console.error('Failed to unfollow:', err);
        this.followingStatus.set(profileId, true); // rollback
        toast.error(err?.message || "Couldn't unfollow this user. Please try again.");
      } finally {
        this.pending.delete(profileId);
      }
    },
    // Avatars fill in per row; a hanging or failed blob only leaves its own
    // default in place instead of holding (or crashing) the whole block.
    loadAvatars(profiles) {
      for (const p of profiles) {
        warpnetService.getImage({userId: p.id, key: p.avatar_key})
            .then((avatar) => {
              if (!avatar) return;
              const group = isMastodonUser(p) ? this.mastodonProfiles : this.warpnetProfiles;
              const i = group.findIndex((x) => x && x.id === p.id);
              if (i !== -1) group.splice(i, 1, {...group[i], avatar});
            })
            .catch((err) => console.warn(`failed to load avatar for [${p.id}]:`, err));
      }
    },
    showMore() {
      this.$router.push({ name: "WhoToFollow" });
    },
   },
  async created() {
    console.log("loading component:", this.$options.name);
    // Who-to-follow is always scoped to the signed-in owner. The backend
    // returns both networks mixed, so keep paging (bounded) until each
    // section has its fill or the feed ends.
    let cursorReset = true;
    for (let round = 0; round < 5; round++) {
      const batch = await warpnetService.getWhoToFollow(cursorReset, sectionLimit * 2);
      cursorReset = false;
      if (!batch || batch.length === 0) {
        break;
      }
      for (const p of batch) {
        const group = isMastodonUser(p) ? this.mastodonProfiles : this.warpnetProfiles;
        if (group.length < sectionLimit) {
          group.push(p);
        }
      }
      if (this.warpnetProfiles.length >= sectionLimit && this.mastodonProfiles.length >= sectionLimit) {
        break;
      }
    }
    const profiles = [...this.warpnetProfiles, ...this.mastodonProfiles];
    this.loadAvatars(profiles);
    for (const p of profiles) {
      const status = await warpnetService.isFollowing(p.id);
      this.followingStatus.set(p.id, status);
    }
  },
};
</script>