services:
  push-gateway:
    container_name: push-gateway-testnet
    image: prom/pushgateway:latest
    network_mode: host
    command:
      - "--web.listen-address=:4091"
    restart: always

  warpnet:
    container_name: warpnet-testnet
    image: ghcr.io/warp-net/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4011
      - SOCKS5_PORT=4080
      - NODE_HOST_V4=130.94.88.38
      - NODE_NETWORK=testnet
      - LOGGING_LEVEL=info
      - LOGGING_FORMAT=json
      - NODE_SEED=warpnet-ru
      - NODE_METRICS_GATEWAY=127.0.0.1:4091

  echo:
    container_name: echo-testnet
    image: ghcr.io/warp-net/warpnet-echo:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4012
      - NODE_HOST_V4=130.94.88.38
      - NODE_NETWORK=testnet
      - LOGGING_LEVEL=info
      - LOGGING_FORMAT=json
      - NODE_SEED=echo
      - SOCKS5_ENABLED=false
      - DATABASE_PATH=/var/lib/warpnet
    volumes:
      - ${HOME}/warpnet-data/testnet/echo:/var/lib/warpnet



