/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.
 
 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

import {buildQRCode} from "@/lib/qr";
import {encodeQRPayload} from "@/lib/qr-payload";
import {generateUUID} from "@/lib/uuid";
import {Call, ConsumePendingDeepLink, IsFirstRun} from "../../wailsjs/go/main/App";

export const PUBLIC_GET_TWEET = "/public/get/tweet/0.0.0"
export const PUBLIC_GET_TWEET_STATS   = "/public/get/tweetstats/0.0.0"
export const PRIVATE_GET_TIMELINE = "/private/get/timeline/0.0.0"
export const PUBLIC_GET_TWEETS = "/public/get/tweets/0.0.0"
export const PRIVATE_GET_NOTIFICATIONS = "/private/get/notifications/0.0.0"
export const PRIVATE_GET_NOTIFICATION = "/private/get/notification/0.0.0"
export const PRIVATE_POST_NOTIFICATION_READ = "/private/post/notification/read/0.0.0"
export const PRIVATE_POST_BOOKMARK = "/private/post/bookmark/0.0.0"
export const PRIVATE_POST_UNBOOKMARK = "/private/post/unbookmark/0.0.0"
export const PRIVATE_GET_BOOKMARKS = "/private/get/bookmarks/0.0.0"
export const PUBLIC_POST_PIN = "/public/post/pin/0.0.0"
export const PUBLIC_POST_UNPIN = "/public/post/unpin/0.0.0"
export const PRIVATE_POST_BLOCK = "/private/post/block/0.0.0"
export const PRIVATE_POST_UNBLOCK = "/private/post/unblock/0.0.0"
export const PRIVATE_GET_BLOCKS = "/private/get/blocks/0.0.0"
export const PRIVATE_POST_MUTE = "/private/post/mute/0.0.0"
export const PRIVATE_POST_UNMUTE = "/private/post/unmute/0.0.0"
export const PRIVATE_GET_MUTES = "/private/get/mutes/0.0.0"
export const PUBLIC_GET_TWEET_LIKERS = "/public/get/tweet/likers/0.0.0"
export const PUBLIC_GET_TWEET_RETWEETERS = "/public/get/tweet/retweeters/0.0.0"
export const PRIVATE_POST_SUBSCRIBE_USER = "/private/post/subscribe/user/0.0.0"
export const PRIVATE_POST_UNSUBSCRIBE_USER = "/private/post/unsubscribe/user/0.0.0"
export const PRIVATE_POST_MEDIA_META = "/private/post/media/meta/0.0.0"
export const PRIVATE_GET_MEDIA = "/private/get/media/0.0.0"
export const PUBLIC_GET_USERS_SEARCH = "/public/get/users/search/0.0.0"
export const PRIVATE_POST_TWEET_EDIT = "/private/post/tweet/edit/0.0.0"
export const PRIVATE_GET_FOLLOW_REQUESTS = "/private/get/follow/requests/0.0.0"
export const PRIVATE_POST_FOLLOW_REQUEST_AUTHORIZE = "/private/post/follow/request/authorize/0.0.0"
export const PRIVATE_POST_FOLLOW_REQUEST_REJECT = "/private/post/follow/request/reject/0.0.0"
export const PRIVATE_GET_FILTER = "/private/get/filter/0.0.0"
export const PRIVATE_GET_FILTERS = "/private/get/filters/0.0.0"
export const PRIVATE_POST_FILTER = "/private/post/filter/0.0.0"
export const PRIVATE_POST_FILTER_UPDATE = "/private/post/filter/update/0.0.0"
export const PRIVATE_DELETE_FILTER = "/private/delete/filter/0.0.0"
export const PRIVATE_POST_FILTER_KEYWORD = "/private/post/filter/keyword/0.0.0"
export const PRIVATE_POST_FILTER_KEYWORD_UPDATE = "/private/post/filter/keyword/update/0.0.0"
export const PRIVATE_DELETE_FILTER_KEYWORD = "/private/delete/filter/keyword/0.0.0"
export const PUBLIC_POST_UNLIKE = "/public/post/unlike/0.0.0"
export const PRIVATE_POST_TWEET = "/private/post/tweet/0.0.0"
export const PUBLIC_POST_REPLY = "/public/post/reply/0.0.0"
export const PUBLIC_GET_FOLLOWINGS = "/public/get/followings/0.0.0"
export const PUBLIC_GET_REPLY = "/public/get/reply/0.0.0"
export const PRIVATE_GET_STATS = "/private/get/admin/stats/0.0.0"
export const PUBLIC_DELETE_REPLY = "/public/delete/reply/0.0.0"
export const PRIVATE_DELETE_TWEET = "/private/delete/tweet/0.0.0"
export const PRIVATE_POST_USER = "/private/post/user/0.0.0"
export const PUBLIC_POST_UNFOLLOW = "/public/post/unfollow/0.0.0"
export const PUBLIC_GET_USER = "/public/get/user/0.0.0"
export const PUBLIC_GET_USERS = "/public/get/users/0.0.0"
export const PUBLIC_GET_WHOTOFOLLOW = "/public/get/whotofollow/0.0.0"
export const PUBLIC_GET_REPLIES = "/public/get/replies/0.0.0"
export const PUBLIC_GET_FOLLOWERS = "/public/get/followers/0.0.0"
export const PUBLIC_POST_FOLLOW = "/public/post/follow/0.0.0"
export const PUBLIC_POST_LIKE = "/public/post/like/0.0.0"
export const PUBLIC_POST_RETWEET = "/public/post/retweet/0.0.0"
export const PUBLIC_POST_UNRETWEET = "/public/post/unretweet/0.0.0"
export const PUBLIC_POST_CHAT = "/public/post/chat/0.0.0"
export const PRIVATE_DELETE_CHAT = "/private/delete/chat/0.0.0"
export const PRIVATE_GET_CHATS = "/private/get/chats/0.0.0"
export const PRIVATE_GET_CHAT = "/private/get/chat/0.0.0"
export const PRIVATE_GET_MESSAGES = "/private/get/messages/0.0.0"
export const PUBLIC_POST_MESSAGE = "/public/post/message/0.0.0"
export const PRIVATE_GET_MESSAGE = "/private/get/message/0.0.0"
export const PRIVATE_DELETE_MESSAGE = "/private/delete/message/0.0.0"
export const PRIVATE_POST_UPLOAD_IMAGE = "/private/post/image/0.0.0"
export const PUBLIC_GET_IMAGE = "/public/get/image/0.0.0"
export const PRIVATE_POST_LOGIN = "/private/post/login/0.0.0"
export const PRIVATE_POST_LOGOUT = "/private/post/logout/0.0.0"
export const PUBLIC_POST_IS_FOLLOWING  = "/public/post/isfollowing/0.0.0"
export const PUBLIC_POST_IS_FOLLOWER   = "/public/post/isfollower/0.0.0"
export const PUBLIC_POST_VIEW          = "/public/post/view/0.0.0"
export const PUBLIC_POST_REPORT        = "/public/post/report/0.0.0"

const stateMap = new Map();
const notificationSubscribers = new Set();
let latestNotifications = { unread_count: 0, notifications: [] };

// In-memory mirror of the local block list, populated lazily so
// the UI can call isUserBlocked() synchronously across tweet
// renders without hitting the node per row.
const blockedIdsCache = new Set();
let blockedCachePrimed = false;
const defaultLimit = 20
const endCursor = "end"

// Tracks in-flight POST requests so duplicate submissions (e.g. a user
// double-clicking "Tweet") reuse the original promise and message id,
// turning duplicates into a single request. The backend additionally
// caches responses by message id, so any duplicate that still slips
// through receives the cached response instead of being processed twice.
const inflightPostRequests = new Map();

// POST routes whose bodies are too large to safely serialize as a Map key
// (e.g. base64 image uploads). Skipping dedup for them avoids an O(N)
// JSON.stringify on the hot path; duplicate suppression there is handled
// by the UI (disabled buttons during upload).
const dedupSkipPaths = new Set([
    PRIVATE_POST_UPLOAD_IMAGE,
]);

function isPostPath(path) {
    return typeof path === "string" && path.includes("/post/");
}

function postRequestKey(path, body) {
    if (dedupSkipPaths.has(path)) return null;
    try {
        return path + "|" + JSON.stringify(body ?? {});
    } catch (_) {
        return null;
    }
}

export const warpnetService = {
    setQR(qrData) {
        const key = `QR`;
        stateMap.set(key, qrData)
    },

    getQR() {
        const key = `QR`;
        return stateMap.get(key) || ""
    },

    setCursor(key, cursor) {
        const cacheKey = `${key}::cursor`;
        stateMap.set(cacheKey, cursor)
    },

    getCursor(key) {
        const cacheKey = `${key}::cursor`;
        return stateMap.get(cacheKey) || ""
    },

    setOwnerProfile(owner) {
        const key = `owner`;
        stateMap.set(key, owner)
    },

    getOwnerProfile() {
        const key = `owner`;
        return stateMap.get(key)
    },

    async isFirstRun() {
        return Boolean(await IsFirstRun());
    },

    // Returns the raw warpnet:// URL the OS handed to the desktop
    // binary (cold-start os.Args or macOS Mac.OnUrlOpen) and clears
    // it on the Go side, so a refresh doesn't re-trigger. Returns
    // the empty string when there's nothing pending.
    async consumePendingDeepLink() {
        try {
            const raw = await ConsumePendingDeepLink();
            return typeof raw === "string" ? raw : "";
        } catch (e) {
            console.warn("consumePendingDeepLink failed:", e);
            return "";
        }
    },

    async signInUser(form) {
        let request = {
            path: PRIVATE_POST_LOGIN,
            body: {
                username: form.username,
                password: form.password,
            }
        }
        const resp = await this.sendToNode(request);
        if (!resp) {
            throw new Error("Login failed: no response")
        }
        if (resp.code) {
            throw new Error(resp.message)
        }
        // Seed the owner profile from the flat AuthNodeInfo first so any
        // sendToNode call below has node_id/user_id available; getProfile
        // is fetched on a best-effort basis to back-fill the username.
        warpnetService.setOwnerProfile({
            user_id: resp.user_id,
            node_id: resp.node_id,
        })
        try {
            const profile = await this.getProfile(resp.user_id)
            if (profile && profile.username) {
                warpnetService.setOwnerProfile({
                    user_id: resp.user_id,
                    node_id: resp.node_id,
                    username: profile.username,
                })
            }
        } catch (err) {
            console.error("Failed to fetch owner profile:", err)
        }

        // The QR carries the full AuthNodeInfo envelope, gzip-compressed at
        // maximum level (9) and Base45-encoded so it fits in a QR alphanumeric
        // segment. The Android client reverses the same pipeline before the
        // pair handshake.
        const fullPayload = JSON.stringify(resp)
        let qrData = ""
        try {
            qrData = await encodeQRPayload(fullPayload)
        } catch (err) {
            console.error("Error encoding QR payload:", err)
        }
        resp.token = null // for security reasons

        const qrCode = await buildQRCode(qrData)
        warpnetService.setQR(qrCode)

        startRefreshNotifications()
    },

    async logoutUser() {
        // Tell the node to drop the session, then wipe local state so any
        // refresh lands back on the login screen. We swallow network errors
        // so a stuck session can still be cleared client-side.
        try {
            await this.sendToNode({ path: PRIVATE_POST_LOGOUT, body: {} })
        } catch (err) {
            console.error("Logout request failed (clearing local state anyway):", err)
        }
        stopRefreshNotifications()
        stateMap.clear()
        try {
            localStorage.removeItem(`first_run_seen`)
        } catch (e) {}
    },

    async getProfile(userId) {
        const request = {
            path: PUBLIC_GET_USER,
            body: {
                user_id: userId,
            },
        }

        return await this.sendToNode(request);
    },

    async getUsers({profileId, cursorReset}) {
        let cursor = this.getCursor('users')
        if (cursorReset) {
            cursor = ''
        }
        if (cursor === endCursor) {
            return []
        }

        const request = {
            path: PUBLIC_GET_USERS,
            body: {
                limit: defaultLimit,
                cursor: cursor,
                user_id: profileId,
            },
        }

        const usersResp = await this.sendToNode(request);
        if (!usersResp) {
            return []
        }
        this.setCursor('users', usersResp.cursor || "")
        if (!usersResp.users || usersResp.users.length === 0) {
            return []
        }

        usersResp.users = usersResp.users.filter(user => user.id !== profileId);

        return usersResp.users;
    },

    async getWhoToFollow(profileId, cursorReset) {
        let cursor = this.getCursor('whotofollow')
        if (cursorReset) {
            cursor = ''
        }
        if (cursor === endCursor) {
            return []
        }

        const owner = this.getOwnerProfile()

        if (!profileId || profileId === '') {
            profileId = owner.user_id
        }

        const request = {
            path: PUBLIC_GET_WHOTOFOLLOW,
            body: {
            limit: defaultLimit,
                cursor: cursor,
                user_id: profileId,
            },
        }

        const followResp = await this.sendToNode(request);
        if (!followResp || followResp.users.length === 0) {
            return []
        }
        this.setCursor('whotofollow', followResp.cursor || "")

        followResp.users = followResp.users.filter(user => !user.isOffline);

        return followResp.users;
    },

    async uploadImage(imgFile) {
        if (!imgFile) {
            return ''
        }
        const keys = await this.uploadImages([imgFile]);
        return keys.length > 0 ? keys[0] : '';
    },

    async uploadImages(imgFiles) {
        if (!imgFiles || imgFiles.length === 0) {
            return []
        }

        const request = {
            path: PRIVATE_POST_UPLOAD_IMAGE,
            timestamp: new Date().toISOString(),
            body: {
                image1: imgFiles[0] || "",
                image2: imgFiles[1] || "",
                image3: imgFiles[2] || "",
                image4: imgFiles[3] || "",
            },
        }

        const result = await this.sendToNode(request);
        const keys = [result.key1, result.key2, result.key3, result.key4]
            .filter(key => key && key.length > 0);
        return keys;
    },

    async getImage({userId, key}) {
        if (!key || key.length === 0) {
            return null
        }

        const cacheKey = `image::${key}`;
        const cached = stateMap.get(cacheKey);
        if (cached) {
            return cached;
        }

        const request = {
            path: PUBLIC_GET_IMAGE,
            body: {
                user_id: userId,
                key: key,
            }
        }

        const result = await this.sendToNode(request);
        if (!result || !result.file) {
            return null
        }
        stateMap.set(cacheKey, result.file);
        return result.file;
    },

    async getMyTimeline(cursorReset) {
        let cursor = this.getCursor('timeline')
        if (cursorReset) {
            cursor = ''
        }

        if (cursor === endCursor) {
            return []
        }

        const owner = this.getOwnerProfile()

        const request = {
            path: PRIVATE_GET_TIMELINE,
            body: {
                limit: defaultLimit,
                cursor: cursor,
                user_id: owner.user_id,
            },
        }

        const timelineResp = await this.sendToNode(request);
        if (!timelineResp) {
            return []
        }

        this.setCursor('timeline', timelineResp.cursor || 'end')
        if (!timelineResp.tweets || timelineResp.tweets.length === 0) {
            return []
        }

        return timelineResp.tweets;
    },

    async getNotifications(cursorReset) {
        let cursor = this.getCursor('notifications')
        if (cursorReset) {
            cursor = ''
        }
        if (cursor === endCursor) {
            return {unread_count:0, notifications: []};
        }
        const owner = this.getOwnerProfile()
        if (!owner) {
            return {unread_count:0, notifications: []};
        }

        const request = {
            path: PRIVATE_GET_NOTIFICATIONS,
            body: {
                limit: defaultLimit,
                cursor: cursor,
            },
        }

        const resp = await this.sendToNode(request);
        if (!resp) {
            return {unread_count:0, notifications: []};
        }
        this.setCursor('notifications', resp.cursor || 'end')
        latestNotifications = {
            unread_count: resp.unread_count || 0,
            notifications: resp.notifications || [],
        };
        for (const cb of notificationSubscribers) {
            cb(latestNotifications);
        }
        return resp;
    },

    async blockUser(targetUserId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        const resp = await this.sendToNode({
            path: PRIVATE_POST_BLOCK,
            body: {
                blocker_id: owner.user_id,
                blockee_id: targetUserId,
            },
        });
        // Mirror the write into the local cache so isUserBlocked
        // reports the new state immediately, without waiting for a
        // refetch.
        blockedIdsCache.add(targetUserId);
        return resp;
    },

    async unblockUser(targetUserId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        const resp = await this.sendToNode({
            path: PRIVATE_POST_UNBLOCK,
            body: {
                blocker_id: owner.user_id,
                blockee_id: targetUserId,
            },
        });
        blockedIdsCache.delete(targetUserId);
        return resp;
    },

    // isUserBlocked answers from the local cache. The first call lazily
    // pulls the full block list (a single page at a time until exhausted)
    // so we don't have to roundtrip per-tweet to know whether to hide it.
    async isUserBlocked(targetUserId) {
        if (!targetUserId) return false;
        await this.ensureBlockedCache();
        return blockedIdsCache.has(targetUserId);
    },

    async ensureBlockedCache() {
        if (blockedCachePrimed) return;
        const owner = this.getOwnerProfile()
        if (!owner) { blockedCachePrimed = true; return; }
        let cursor = '';
        const seen = new Set();
        try {
            while (true) {
                const resp = await this.sendToNode({
                    path: PRIVATE_GET_BLOCKS,
                    body: { user_id: owner.user_id, limit: defaultLimit, cursor },
                });
                const ids = resp?.ids || [];
                for (const id of ids) seen.add(id);
                const next = resp?.cursor || '';
                if (!next || next === endCursor || ids.length === 0) break;
                if (next === cursor) break;
                cursor = next;
            }
        } catch (err) {
            console.warn('failed to prime blocked-users cache:', err);
        }
        // Merge with anything blockUser() may have written before the
        // initial prime completed.
        for (const id of blockedIdsCache) seen.add(id);
        blockedIdsCache.clear();
        for (const id of seen) blockedIdsCache.add(id);
        blockedCachePrimed = true;
    },

    async getBlocks(cursorReset) {
        let cursor = this.getCursor('blocks')
        if (cursorReset) cursor = '';
        if (cursor === endCursor) return { ids: [], cursor: endCursor };
        const owner = this.getOwnerProfile()
        if (!owner) return { ids: [], cursor: endCursor };
        const resp = await this.sendToNode({
            path: PRIVATE_GET_BLOCKS,
            body: {
                user_id: owner.user_id,
                limit: defaultLimit,
                cursor,
            },
        });
        if (!resp) return { ids: [], cursor: endCursor };
        this.setCursor('blocks', resp.cursor || 'end')
        // Reflect this page into the local cache.
        for (const id of (resp.ids || [])) blockedIdsCache.add(id);
        if ((resp.cursor || endCursor) === endCursor) blockedCachePrimed = true;
        return resp;
    },

    // isUserBlockedSync returns the current cached answer without
    // touching the network. Callers that haven't awaited
    // ensureBlockedCache() may get a stale `false` immediately after
    // app start.
    isUserBlockedSync(targetUserId) {
        return !!targetUserId && blockedIdsCache.has(targetUserId);
    },

    async muteUser(targetUserId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_POST_MUTE,
            body: {
                muter_id: owner.user_id,
                mutee_id: targetUserId,
            },
        });
    },

    async unmuteUser(targetUserId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_POST_UNMUTE,
            body: {
                muter_id: owner.user_id,
                mutee_id: targetUserId,
            },
        });
    },

    async getMutes(cursorReset) {
        let cursor = this.getCursor('mutes')
        if (cursorReset) cursor = '';
        if (cursor === endCursor) return { ids: [], cursor: endCursor };
        const owner = this.getOwnerProfile()
        if (!owner) return { ids: [], cursor: endCursor };
        const resp = await this.sendToNode({
            path: PRIVATE_GET_MUTES,
            body: {
                user_id: owner.user_id,
                limit: defaultLimit,
                cursor,
            },
        });
        if (!resp) return { ids: [], cursor: endCursor };
        this.setCursor('mutes', resp.cursor || 'end')
        return resp;
    },

    async getFilter(filterId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_GET_FILTER,
            body: {
                user_id: owner.user_id,
                filter_id: filterId,
            },
        });
    },

    async getFilters(cursor) {
        const owner = this.getOwnerProfile()
        if (!owner) return { filters: [], cursor: 'end' };
        const resp = await this.sendToNode({
            path: PRIVATE_GET_FILTERS,
            body: {
                user_id: owner.user_id,
                limit: defaultLimit,
                cursor: cursor || '',
            },
        });
        return resp || { filters: [], cursor: 'end' };
    },

    async createFilter(filter) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_POST_FILTER,
            body: {
                user_id: owner.user_id,
                title: filter.title || '',
                context: filter.context || [],
                action: filter.action || 'warn',
                expires_at: filter.expires_at || null,
                keywords: filter.keywords || [],
            },
        });
    },

    async updateFilter(filter) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_POST_FILTER_UPDATE,
            body: {
                user_id: owner.user_id,
                id: filter.id,
                title: filter.title || '',
                context: filter.context || [],
                action: filter.action || '',
                expires_at: filter.expires_at || null,
                keywords: [],
            },
        });
    },

    async deleteFilter(filterId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_DELETE_FILTER,
            body: {
                user_id: owner.user_id,
                filter_id: filterId,
            },
        });
    },

    async addFilterKeyword(filterId, keyword, wholeWord) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_POST_FILTER_KEYWORD,
            body: {
                user_id: owner.user_id,
                filter_id: filterId,
                keyword: keyword,
                whole_word: !!wholeWord,
            },
        });
    },

    async updateFilterKeyword(keywordId, keyword, wholeWord) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_POST_FILTER_KEYWORD_UPDATE,
            body: {
                user_id: owner.user_id,
                keyword_id: keywordId,
                keyword: keyword,
                whole_word: !!wholeWord,
            },
        });
    },

    async deleteFilterKeyword(keywordId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_DELETE_FILTER_KEYWORD,
            body: {
                user_id: owner.user_id,
                keyword_id: keywordId,
            },
        });
    },

    async getFollowRequests(cursor) {
        const owner = this.getOwnerProfile()
        if (!owner) return { follower_ids: [], cursor: 'end' };
        const resp = await this.sendToNode({
            path: PRIVATE_GET_FOLLOW_REQUESTS,
            body: {
                user_id: owner.user_id,
                limit: defaultLimit,
                cursor: cursor || '',
            },
        });
        return resp || { follower_ids: [], cursor: 'end' };
    },

    async authorizeFollowRequest(followerId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_POST_FOLLOW_REQUEST_AUTHORIZE,
            body: {
                user_id: owner.user_id,
                follower_id: followerId,
            },
        });
    },

    async rejectFollowRequest(followerId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_POST_FOLLOW_REQUEST_REJECT,
            body: {
                user_id: owner.user_id,
                follower_id: followerId,
            },
        });
    },

    async editTweet(tweetId, text) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_POST_TWEET_EDIT,
            body: {
                tweet_id: tweetId,
                user_id: owner.user_id,
                text: text,
            },
        });
    },

    async searchUsers(query, cursor) {
        if (!query) return { users: [], cursor: 'end' };
        const resp = await this.sendToNode({
            path: PUBLIC_GET_USERS_SEARCH,
            body: {
                query: query,
                limit: defaultLimit,
                cursor: cursor || '',
            },
        });
        return resp || { users: [], cursor: 'end' };
    },

    async updateMediaMeta(key, description, focusX, focusY) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_POST_MEDIA_META,
            body: {
                user_id: owner.user_id,
                key: key,
                description: description || '',
                focus_x: focusX || 0,
                focus_y: focusY || 0,
            },
        });
    },

    async getMediaMeta(key) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_GET_MEDIA,
            body: {
                user_id: owner.user_id,
                key: key,
            },
        });
    },

    async subscribeUser(targetId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_POST_SUBSCRIBE_USER,
            body: {
                self_id: owner.user_id,
                target_id: targetId,
            },
        });
    },

    async unsubscribeUser(targetId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        return await this.sendToNode({
            path: PRIVATE_POST_UNSUBSCRIBE_USER,
            body: {
                self_id: owner.user_id,
                target_id: targetId,
            },
        });
    },

    async getTweetLikers(tweetId, ownerUserId, cursor) {
        const resp = await this.sendToNode({
            path: PUBLIC_GET_TWEET_LIKERS,
            body: {
                tweet_id: tweetId,
                owner_user_id: ownerUserId,
                limit: defaultLimit,
                cursor: cursor || '',
            },
        });
        return resp || { users: [], cursor: 'end' };
    },

    async getTweetRetweeters(tweetId, ownerUserId, cursor) {
        const resp = await this.sendToNode({
            path: PUBLIC_GET_TWEET_RETWEETERS,
            body: {
                tweet_id: tweetId,
                owner_user_id: ownerUserId,
                limit: defaultLimit,
                cursor: cursor || '',
            },
        });
        return resp || { users: [], cursor: 'end' };
    },


    async pinTweet(tweetId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        const request = {
            path: PUBLIC_POST_PIN,
            body: {
                user_id: owner.user_id,
                tweet_id: tweetId,
            },
        }
        return await this.sendToNode(request);
    },

    async unpinTweet(tweetId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        const request = {
            path: PUBLIC_POST_UNPIN,
            body: {
                user_id: owner.user_id,
                tweet_id: tweetId,
            },
        }
        return await this.sendToNode(request);
    },

    async bookmarkTweet(tweetId, ownerUserId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        const request = {
            path: PRIVATE_POST_BOOKMARK,
            body: {
                user_id: owner.user_id,
                tweet_id: tweetId,
                owner_user_id: ownerUserId,
            },
        }
        return await this.sendToNode(request);
    },

    async unbookmarkTweet(tweetId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;
        const request = {
            path: PRIVATE_POST_UNBOOKMARK,
            body: {
                user_id: owner.user_id,
                tweet_id: tweetId,
            },
        }
        return await this.sendToNode(request);
    },

    async getBookmarks(cursorReset) {
        let cursor = this.getCursor('bookmarks')
        if (cursorReset) {
            cursor = ''
        }
        if (cursor === endCursor) {
            return { items: [], cursor: endCursor };
        }
        const owner = this.getOwnerProfile()
        if (!owner) return { items: [], cursor: endCursor };
        const request = {
            path: PRIVATE_GET_BOOKMARKS,
            body: {
                user_id: owner.user_id,
                limit: defaultLimit,
                cursor: cursor,
            },
        }
        const resp = await this.sendToNode(request);
        if (!resp) return { items: [], cursor: endCursor };
        this.setCursor('bookmarks', resp.cursor || 'end')

        // Backend returns the bookmark index entries (tweet_id +
        // owner_user_id). Hydrate each into the full Tweet so the view
        // can render it inline like a timeline tweet.
        const rawItems = resp.items || [];
        const hydrated = await Promise.all(rawItems.map(async (b) => {
            if (!b || !b.tweet_id) return null;
            try {
                const tweet = await this.getTweet({
                    userId: b.owner_user_id || owner.user_id,
                    tweetId: b.tweet_id,
                });
                return tweet ? { ...b, tweet } : null;
            } catch (e) {
                console.warn('bookmark hydrate failed:', b, e);
                return null;
            }
        }));
        return { items: hydrated.filter(Boolean), cursor: resp.cursor || 'end' };
    },

    async getNotification(notificationId) {
        if (!notificationId) return null;
        const request = {
            path: PRIVATE_GET_NOTIFICATION,
            body: {
                notification_id: notificationId,
            },
        }
        const resp = await this.sendToNode(request);
        return resp || null;
    },

    async markNotificationRead(notificationId) {
        if (!notificationId) return null;
        const request = {
            path: PRIVATE_POST_NOTIFICATION_READ,
            body: {
                notification_id: notificationId,
            },
        }
        const resp = await this.sendToNode(request);

        // Optimistic local update so the SideNav badge ticks down
        // without waiting for the next poll. Flip the matching
        // notification's is_read and decrement unread_count.
        const target = latestNotifications.notifications.find(n => n && n.id === notificationId);
        if (target && !target.is_read) {
            target.is_read = true;
            latestNotifications = {
                unread_count: Math.max(0, (latestNotifications.unread_count || 1) - 1),
                notifications: latestNotifications.notifications,
            };
            for (const cb of notificationSubscribers) {
                cb(latestNotifications);
            }
        }
        return resp;
    },

    subscribeNotifications(callback) {
        notificationSubscribers.add(callback);
        callback(latestNotifications);
        return () => {
            notificationSubscribers.delete(callback);
        };
    },

    async getTweets({userId,cursorReset}) {
        let cursor = this.getCursor('tweets')
        if (cursorReset) {
            cursor = ''
        }
        if (cursor === endCursor) {
            return []
        }

        const request = {
            path: PUBLIC_GET_TWEETS,
            body: {
                limit: defaultLimit,
                cursor: cursor,
                user_id: userId,
            },
        }

        const tweetsResp = await this.sendToNode(request);
        if (!tweetsResp) {
            return []
        }
        this.setCursor('tweets', tweetsResp.cursor || 'end')
        if (!tweetsResp.tweets || tweetsResp.tweets.length === 0) {
            return []
        }

        return tweetsResp.tweets;
    },

    async createTweet({text, imageKeys}) {
        const owner = this.getOwnerProfile()

        const request ={
            path: PRIVATE_POST_TWEET,
            body: {
                user_id: owner.user_id,
                username: owner.username,
                text: text,
                image_keys: imageKeys || [],
                created_at: new Date().toISOString(),
            },
        }

        return await this.sendToNode(request);
    },

    async deleteTweet({userId, tweetId}) {
        const request = {
            path: PRIVATE_DELETE_TWEET,
            body: {
                user_id: userId,
                tweet_id: tweetId,
            },
        }

        return await this.sendToNode(request);
    },

    async getTweet({userId, tweetId}) {
        const request = {
            path: PUBLIC_GET_TWEET,
            body: {
                user_id: userId,
                tweet_id: tweetId,
            },
        }

        return await this.sendToNode(request);
    },

    async followUser(profileId) {
        const owner = this.getOwnerProfile()

        const request = {
            path: PUBLIC_POST_FOLLOW,
            body: {
                following_id: profileId,
                follower_id: owner.user_id,
            },
        }

        return await this.sendToNode(request);
    },

    async isFollowing(profileId) {
        const request = {
            path: PUBLIC_POST_IS_FOLLOWING,
            body: {
                user_id: profileId,
            },
        }

        const resp = await this.sendToNode(request);
        return resp?.is_following || false
    },

    async isFollower(profileId) {
        const request = {
            path: PUBLIC_POST_IS_FOLLOWER,
            body: {
                user_id: profileId,
            },
        }

        const resp = await this.sendToNode(request);
        return resp?.is_follower || false
    },

    async unfollowUser(profileId) {
        const owner = this.getOwnerProfile()

        const request = {
            path: PUBLIC_POST_UNFOLLOW,
            body: {
                following_id: profileId,
                follower_id: owner.user_id,
            },
        }

        return await this.sendToNode(request);
    },

    async getFollowers({userId, cursorReset}) {
        let cursor = this.getCursor('followers')
        if (cursorReset) {
            cursor = ''
        }
        if (cursor === endCursor) {
            return []
        }

        const request = {
            path: PUBLIC_GET_FOLLOWERS,
            body: {
                user_id: userId,
                cursor: cursor,
                limit: defaultLimit,
            },
        }

        const followersResp = await this.sendToNode(request);
        if (!followersResp) {
            return []
        }
        this.setCursor('followers', followersResp.cursor || 'end')
        if (!followersResp.followers || followersResp.followers.length === 0) {
            return []
        }
        followersResp.followers = followersResp.followers.filter(follower => follower !== userId);
        return followersResp.followers;
    },

    async getFollowings({userId, cursorReset}) {
        let cursor = this.getCursor('followings')
        if (cursorReset) {
            cursor = ''
        }
        if (cursor === endCursor) {
            return []
        }

        const request = {
            path: PUBLIC_GET_FOLLOWINGS,
            body: {
                user_id: userId,
                cursor: cursor,
                limit: defaultLimit,
            },
        }

        const followingsResp = await this.sendToNode(request);
        if (!followingsResp) {
            return []
        }
        this.setCursor('followings', followingsResp.cursor || 'end')
        if (!followingsResp.followings || followingsResp.followings.length === 0) {
            return []
        }
        followingsResp.followings = followingsResp.followings.filter(following => following !== userId);

        return followingsResp.followings;
    },

    async getTweetStats(tweetId, userId) {
        const request = {
            path: PUBLIC_GET_TWEET_STATS,
            body: {
                user_id: userId,
                tweet_id: tweetId,
            },
        }

        return await this.sendToNode(request);
    },

    // create reply
    async replyTweet({rootId, parentId, parentUserId, text}) {
        const owner = this.getOwnerProfile()

        const request = {
            path: PUBLIC_POST_REPLY,
            body: {
                root_id: rootId,
                parent_id: parentId,
                user_id: owner.user_id,
                username: owner.username,
                parent_user_id: parentUserId,
                text: text,
                created_at: new Date().toISOString(),
            },
        }
        return await this.sendToNode(request);
    },

    async getReplies({rootId, parentId, cursorReset}) {
        let cursor = this.getCursor('replies')
        if (cursorReset) {
            cursor = ''
        }
        if (cursor === endCursor) {
            return []
        }

        const request = {
            path: PUBLIC_GET_REPLIES,
            body: {
                root_id: rootId,
                parent_id: parentId,
                limit: defaultLimit,
                cursor: cursor,
            },
        }

        const repliesResp = await this.sendToNode(request);
        if (!repliesResp) {
            return []
        }
        this.setCursor('replies', repliesResp.cursor || 'end')
        if (!repliesResp.replies || repliesResp.replies.length === 0) {
            return []
        }
        // Backend ships a ReplyNode tree (`{ children, reply }`); the UI
        // wants plain Tweet records. Flatten one level — the top-level
        // replies are what's rendered; nested children would need a
        // dedicated thread view.
        return repliesResp.replies
            .map(node => (node && node.reply) ? node.reply : node)
            .filter(t => t && t.id);
    },

    async getReply({rootId, replyId, userId}) {
        const request = {
            path: PUBLIC_GET_REPLY,
            body: {
                root_id: rootId,
                reply_id: replyId,
                user_id: userId,
            },
        }

        return await this.sendToNode(request);
    },

    async deleteReply({userId, rootId, replyId}) {
        const request = {
            path: PUBLIC_DELETE_REPLY,
            body: {
                user_id: userId,
                root_id: rootId,
                reply_id: replyId,
            },
        }

        return await this.sendToNode(request);
    },

    async likeTweet(tweetId, userId) {
        const owner = this.getOwnerProfile()

        const request = {
            path: PUBLIC_POST_LIKE,
            body: {
                user_id: userId,
                tweet_id: tweetId,
                owner_id: owner.user_id,
            },
        }

        const likeResp = await this.sendToNode(request);
        return likeResp.count;
    },

    async unlikeTweet(tweetId, userId) {
        const owner = this.getOwnerProfile()

        const request = {
            path: PUBLIC_POST_UNLIKE,
            body: {
                user_id: userId,
                tweet_id: tweetId,
                owner_id: owner.user_id,
            },
        }

        const unlikeResp = await this.sendToNode(request);
        return unlikeResp.count;
    },

    // viewTweet returns the new view count on success, or `null` if
    // the request failed in any way (no owner, network/handler error,
    // malformed response). `null` is distinct from a legitimate count
    // of 0 so callers can decide whether to retry.
    async viewTweet(tweetId, authorId) {
        const owner = this.getOwnerProfile()
        if (!owner) return null;

        const request = {
            path: PUBLIC_POST_VIEW,
            body: {
                user_id: authorId,
                tweet_id: tweetId,
                viewer_id: owner.user_id,
            },
        }

        try {
            const resp = await this.sendToNode(request);
            if (resp && typeof resp.count === 'number') {
                return resp.count;
            }
            return null;
        } catch (err) {
            console.error(`failed to record view for tweet [${tweetId}]`, err);
            return null;
        }
    },

    // Report opens a moderation request to whichever moderator node is
    // listening on the global reports topic. `type` is the
    // ModerationObjectType enum; the backend currently accepts only
    // 0 (user profile) and 1 (tweet) — reply (2) and image (3) reports
    // are not wired end-to-end yet and will be rejected. `objectId` is
    // required for tweet reports and ignored for user reports.
    // `reason` is a free-form string capped at 256 chars by the
    // backend; the UI presents a fixed set of labels as a convenience,
    // but the server does not enforce that set.
    async report({ type, objectId, targetUserId, targetNodeId, reason }) {
        const request = {
            path: PUBLIC_POST_REPORT,
            body: {
                type: type,
                object_id: objectId || '',
                target_user_id: targetUserId,
                target_node_id: targetNodeId,
                reason: reason,
            },
        }
        return await this.sendToNode(request)
    },

    async setLiker(tweetId, profileId, profileObj) {
        const cacheKey = `liker::${tweetId}::${profileId}`; // order matters
        stateMap.set(cacheKey, profileObj)
        localStorage.setItem(cacheKey, "1")
    },

    async hasLiker(tweetId, profileId) {
        const cacheKey = `liker::${tweetId}::${profileId}`; // order matters
        if (stateMap.has(cacheKey)) {
            return true
        }
        return localStorage.getItem(cacheKey) === "1"
    },

    async getLiker(tweetId, profileId) {
        const cacheKey = `liker::${tweetId}::${profileId}`; // order matters
        return stateMap.get(cacheKey)
    },

    async deleteLiker(tweetId, profileId) {
        const cacheKey = `liker::${tweetId}::${profileId}`; // order matters
        stateMap.delete(cacheKey)
        localStorage.removeItem(cacheKey)
    },

    async retweetTweet({tweetId, userId, username, text, comment}) {
        const owner = this.getOwnerProfile()

        // The optional `comment` (when non-empty) turns the retweet
        // into a quote — a regular tweet authored by the retweeter
        // whose text is the comment and which carries quoted_tweet_id
        // / quoted_user_id pointing at the source. Without a comment
        // it's a plain retweet that just echoes the source.
        const hasComment = !!comment && !!comment.trim();
        if (hasComment) {
            return await this.sendToNode({
                path: PUBLIC_POST_RETWEET,
                body: {
                    id: tweetId,
                    user_id: owner.user_id,
                    username: owner.username || '',
                    text: comment.trim(),
                    retweeted_by: owner.user_id,
                    quoted_tweet_id: tweetId,
                    quoted_user_id: userId,
                    created_at: new Date().toISOString(),
                    root_id: "",
                },
            });
        }
        return await this.sendToNode({
            path: PUBLIC_POST_RETWEET,
            body: {
                id: tweetId,
                user_id: userId,
                username: username,
                text: text,
                retweeted_by: owner.user_id,
                created_at: new Date().toISOString(),
                root_id: "",
            },
        });
    },

    async unretweetTweet(tweetId) {
        const owner = this.getOwnerProfile()

        const request = {
            path: PUBLIC_POST_UNRETWEET,
            timestamp: new Date().toISOString(),
            body: {
                retweeter_id: owner.user_id,
                tweet_id: tweetId,
            },
        }

        return await this.sendToNode(request);
    },

    async setRetweeter(tweetId, profileId, profileObj) {
        const cacheKey = `retweeter::${tweetId}::${profileId}`; // order matters
        stateMap.set(cacheKey, profileObj)
        localStorage.setItem(cacheKey, "1")
    },

    async hasRetweeter(tweetId, profileId) {
        const cacheKey = `retweeter::${tweetId}::${profileId}`; // order matters
        if (stateMap.has(cacheKey)) {
            return true
        }
        return localStorage.getItem(cacheKey) === "1"
    },

    async getRetweeter(tweetId, profileId) {
        const cacheKey = `retweeter::${tweetId}::${profileId}`; // order matters
        return stateMap.get(cacheKey)
    },

    async deleteRetweeter(tweetId, profileId) {
        const cacheKey = `retweeter::${tweetId}::${profileId}`; // order matters
        stateMap.delete(cacheKey)
        localStorage.removeItem(cacheKey)
    },

    async createChat(otherUserId) {
        const owner = this.getOwnerProfile()

        const request = {
            path: PUBLIC_POST_CHAT,
            body: {
                owner_id: owner.user_id,
                other_user_id: otherUserId,
            },
        }

        return await this.sendToNode(request);
    },

    async getChat(chatId) {
        const request = {
            path: PRIVATE_GET_CHAT,
            body: {
                chat_id: chatId,
            },
        }

        return await this.sendToNode(request);
    },

    async getChats(cursorReset) {
        let cursor = this.getCursor('chats')
        if (cursorReset) {
            cursor = ''
        }
        if (cursor === endCursor) {
            return []
        }

        const owner = this.getOwnerProfile()

        const request = {
            path: PRIVATE_GET_CHATS,
            body: {
                user_id: owner.user_id,
                limit: defaultLimit,
                cursor: cursor,
            },
        }

        const chatsResp = await this.sendToNode(request);
        if (!chatsResp) {
            return []
        }
        this.setCursor('chats', chatsResp.cursor || 'end')
        if (!chatsResp.chats || chatsResp.chats.length === 0) {
            return []
        }

        return chatsResp.chats;
    },

    async deleteChat(chatId) {
        const request = {
            path: PRIVATE_DELETE_CHAT,
            body: {
                chat_id: chatId,
            },
        }

        return await this.sendToNode(request);
    },

    async sendDirectMessage({chatId, receiverId, text, imageKey}) {
        const owner = this.getOwnerProfile();
        const request = {
            path: PUBLIC_POST_MESSAGE,
            body: {
                sender_id: owner.user_id,
                receiver_id: receiverId,
                chat_id: chatId,
                text: text,
            },
        }

        return await this.sendToNode(request);
    },

    async getDirectMessages({chatId, cursorReset}) {
        let cursor = this.getCursor('messages')
        if (cursorReset) {
            cursor = ''
        }
        if (cursor === endCursor) {
            return []
        }

        const owner = this.getOwnerProfile();

        const request = {
            path: PRIVATE_GET_MESSAGES,
            body: {
                owner_id: owner.user_id,
                chat_id: chatId,
                limit: defaultLimit,
                cursor: cursor,
            },
        }

        const messagesResp = await this.sendToNode(request);
        if (!messagesResp) {
            return []
        }
        this.setCursor('messages', messagesResp.cursor || 'end')
        if (!messagesResp.messages || messagesResp.messages.length === 0) {
            return []
        }

        return messagesResp.messages;
    },

    async editMyProfile(newProfile) {
        const request = {
            path: PRIVATE_POST_USER,
            body: {
                bio: newProfile.bio,
                avatar_key: newProfile.avatar_key,
                username: newProfile.username,
                background_image_key: newProfile.background_image_key,
                website: newProfile.website,
                birthdate: newProfile.birthdate,
            },
        }

        return await this.sendToNode(request);
    },

    async getNodeInfo(){
        const request = {
            path: PRIVATE_GET_STATS,
            body: {},
        }

        return await this.sendToNode(request);
    },

    async sendToNode(request) {
        const owner = this.getOwnerProfile()

        const dedupKey = isPostPath(request.path)
            ? postRequestKey(request.path, request.body)
            : null;
        if (dedupKey && inflightPostRequests.has(dedupKey)) {
            return inflightPostRequests.get(dedupKey);
        }

        request.message_id = generateUUID()
        request.node_id = owner?.node_id || "Blank"
        request.timestamp = new Date().toISOString()

        const promise = (async () => {
            const result = await Call(request);
            if (!result) {
                throw new Error(`Unable to send ${request.message_id}`);
            }
            if (!result.body) {
                console.error(`${result.code}: ${result.message}`);
                return {};
            }
            return result.body;
        })();

        if (dedupKey) {
            inflightPostRequests.set(dedupKey, promise);
            const cleanup = () => inflightPostRequests.delete(dedupKey);
            promise.then(cleanup, cleanup);
        }

        return promise;
    }
}

let notificationInterval = null;
let notificationRefreshInFlight = false;

export function startRefreshNotifications() {
    if (notificationInterval) return;
    notificationInterval = setInterval(async () => {
        const owner = warpnetService.getOwnerProfile();
        if (!owner) {
            stopRefreshNotifications();
            return;
        }
        if (notificationRefreshInFlight) return;
        notificationRefreshInFlight = true;
        try {
            await warpnetService.getNotifications(true);
        } catch (err) {
            console.error('failed to refresh notifications', err);
        } finally {
            notificationRefreshInFlight = false;
        }
    }, 2000);
}

export function stopRefreshNotifications() {
    if (!notificationInterval) return;
    clearInterval(notificationInterval);
    notificationInterval = null;
    notificationRefreshInFlight = false;
}
