<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div id="app" class="w-full h-full">
    <router-view :key="$route.fullPath" />
  </div>
</template>

<script>
import {EventsOff, EventsOn} from "@/lib/transport";
import {parseDeepLink} from "@/lib/deeplink";
import {warpnetService} from "@/service/service";

const DEEP_LINK_EVENT = "deeplink:open";
const LOG = "[warpnet-deeplink]";

export default {
  name: "App",
  mounted() {
    // Hot-path: Go side fires "deeplink:open" when a second
    // process or macOS OnUrlOpen hands a warpnet:// URL to the
    // already-running app. Cold-start is still handled by Root /
    // Home polling ConsumePendingDeepLink in their own lifecycle.
    console.info(LOG, "subscribing to", DEEP_LINK_EVENT);
    EventsOn(DEEP_LINK_EVENT, async () => {
      console.info(LOG, "event received, pulling pending URL");
      try {
        const raw = await warpnetService.consumePendingDeepLink();
        if (!raw) {
          console.warn(LOG, "event fired but pending URL was empty");
          return;
        }
        console.info(LOG, "raw URL", raw);
        const link = parseDeepLink(raw);
        if (!link) {
          console.warn(LOG, "could not parse", raw);
          return;
        }
        console.info(LOG, "parsed", link);
        if (link.kind === "user") {
          console.info(LOG, "routing → Search q=" + link.id);
          this.$router.push({ name: "Search", query: { q: link.id } });
        } else {
          console.warn(LOG, "unhandled kind", link.kind);
        }
      } catch (e) {
        console.warn(LOG, "event handler threw", e);
      }
    });
  },
  beforeUnmount() {
    EventsOff(DEEP_LINK_EVENT);
  },
};
</script>
