<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div id="app" class="w-full h-full">
    <!-- Both global banners overlay the top of every view, so they share one
         stack instead of covering each other when shown together. -->
    <div class="fixed top-0 inset-x-0 z-[100]">
      <!-- Global node-connection banner: for a P2P app the local node can drop,
           so the user must always be able to see it and recover. -->
      <div
        v-if="connection.status !== 'online'"
        class="flex items-center justify-center gap-3 px-4 py-2 text-sm font-medium text-white"
        :class="connection.status === 'connecting' ? 'bg-dark' : 'bg-red-600'"
        role="status"
        aria-live="polite"
      >
        <span v-if="connection.status === 'connecting'">
          <i class="fas fa-circle-notch fa-spin mr-2" aria-hidden="true"></i>Connecting to your Warpnet node…
        </span>
        <template v-else>
          <span><i class="fas fa-plug mr-2" aria-hidden="true"></i>Your Warpnet node is unreachable.</span>
          <button type="button" class="underline font-semibold flat-btn" @click="reconnect">Reconnect</button>
        </template>
      </div>

      <!-- Experimental-network banner: the node reports its own network on
           login, and everything except production is throwaway. -->
      <div
        v-if="showNetworkBanner"
        class="flex items-center justify-center gap-2 px-4 py-1.5 text-sm font-medium text-white bg-blue"
        role="status"
      >
        <i class="fas fa-flask" aria-hidden="true"></i>
        <span>{{ networkLabel }} — data here is experimental and may be reset</span>
      </div>
    </div>

    <router-view :key="$route.fullPath" />
    <ToastHost />
  </div>
</template>

<script>
import {EventsOff, EventsOn} from "@/lib/transport";
import {parseDeepLink} from "@/lib/deeplink";
import {warpnetService} from "@/service/service";
import {connection} from "@/lib/connection";
import {isExperimentalNetwork} from "@/lib/network";
import ToastHost from "@/components/ToastHost.vue";

const DEEP_LINK_EVENT = "deeplink:open";
const LOG = "[warpnet-deeplink]";

export default {
  name: "App",
  components: { ToastHost },
  data() {
    return { connection, owner: warpnetService.getOwnerProfile(), unsubscribeOwner: null };
  },
  computed: {
    // Held back until the owner is known: before login the node has not
    // reported its network yet, and the login screen is not the place for it.
    // A session restored from a login that predates the cached network carries
    // no value at all - that is a client-side gap rather than a signal from
    // the node, so it stays quiet until the next login fills it in.
    showNetworkBanner() {
      if (!this.owner?.user_id || typeof this.owner.network !== "string") {
        return false;
      }
      return isExperimentalNetwork(this.owner.network);
    },
    networkLabel() {
      const network = (this.owner?.network || "").trim();
      if (!network) {
        return "Test network";
      }
      return network.charAt(0).toUpperCase() + network.slice(1);
    },
  },
  methods: {
    // A dropped WebSocket may leave the transport singleton (socket, aesKey,
    // pending map) wedged; a full reload is the reliable, documented reset.
    reconnect() {
      window.location.reload();
    },
  },
  mounted() {
    // The network arrives with the login response, so the banner has to react
    // to the owner profile rather than read it once at mount.
    this.unsubscribeOwner = warpnetService.subscribeOwner((owner) => {
      this.owner = owner;
    });

    // Hot-path: Go side fires "deeplink:open" when a second
    // process or macOS OnUrlOpen hands a warpnet:// URL to the
    // already-running app. Cold-start is still handled by Root /
    // Home polling ConsumePendingDeepLink in their own lifecycle.
    console.info(LOG, "subscribing to", DEEP_LINK_EVENT);
    EventsOn(DEEP_LINK_EVENT, async () => {
      console.info(LOG, "event received, pulling pending URL");
      try {
        const raw = await warpnetService.consumePendingDeepLink();
        if (!raw) {
          console.warn(LOG, "event fired but pending URL was empty");
          return;
        }
        console.info(LOG, "raw URL", raw);
        const link = parseDeepLink(raw);
        if (!link) {
          console.warn(LOG, "could not parse", raw);
          return;
        }
        console.info(LOG, "parsed", link);
        if (link.kind === "user") {
          console.info(LOG, "routing → Search q=" + link.id);
          this.$router.push({ name: "Search", query: { q: link.id } });
        } else {
          console.warn(LOG, "unhandled kind", link.kind);
        }
      } catch (e) {
        console.warn(LOG, "event handler threw", e);
      }
    });
  },
  beforeUnmount() {
    EventsOff(DEEP_LINK_EVENT);
    this.unsubscribeOwner?.();
  },
};
</script>
