/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.
 
 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

import "./lib/backend-mock"
import { createApp } from "vue";
import App from "./App.vue";
import "./assets/tailwind.css";
import router from "./router";
import directives from "./directives";
import filters from "./filters";
import { warpnetService } from "./service/service";

const app = createApp(App);

app.config.errorHandler = function (err, vm, info) {
    console.error("GLOBAL ERROR HANDLER:", err, info);
};

// Resume an existing session (owner profile + channel key) before the router
// runs, so a page reload stays on the current page instead of the login screen.
warpnetService.restoreSession();

app.use(router);
app.use(directives);
app.use(filters);

app.mount("#app");
