name: warpnet # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  WarpNet is a decentralized, peer-to-peer social network inspired by Twitter, built with Go. 
  It runs without central servers, using Noise protocol for inter-node communication and built-in local storage. 
  WarpNet is censorship-resistant, scalable, and fully open-source. 

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

platforms:
  amd64:

icon: cmd/node/member/icon.png

apps:
  warpnet:
    command: bin/warpnet
    extensions: [gnome]

layout:
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1

#package-repositories:
#  - type: apt
#    components: [main]
#    suites: [noble]
#    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
#    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  warpnet:
    plugin: nil
    source: .
    build-packages:
      - build-essential
      - libgtk-3-dev
      - libwebkit2gtk-4.1-dev
      - curl
      - ca-certificates
      - tar
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    build-environment:
      - CGO_ENABLED: "1"
      - PATH: "/usr/local/go/bin:/root/go/bin:${PATH}"
    override-build: |
      set -eux
      
      craftctl default
      
      GO_VERSION=1.24.2
      curl -fsSL "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz" -o go.tar.gz
      tar -C /usr/local -xzf go.tar.gz
      rm go.tar.gz

      /usr/local/go/bin/go install github.com/wailsapp/wails/v2/cmd/wails@v2.10.2

      cd cmd/node/member
      /root/go/bin/wails build -v 2 -tags webkit2_41

      install -D -m0755 build/bin/warpnet "$SNAPCRAFT_PART_INSTALL/bin/warpnet"
