// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Call(arg1) {
  return window['go']['main']['App']['Call'](arg1);
}

export function ConsumePendingDeepLink() {
  return window['go']['main']['App']['ConsumePendingDeepLink']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function SetPendingDeepLink(arg1) {
  return window['go']['main']['App']['SetPendingDeepLink'](arg1);
}
