<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->

<template>
  <div id="app" class="flex container h-full w-full" v-scroll:bottom="loadMore">
    <div class="flex container h-full w-full">
      <SideNav />

      <div class="w-full sm:w-1/3 md:w-1/2 lg:w-1/2 h-full overflow-y-scroll no-scrollbar hidden md:block">
        <div class="px-5 py-3 border-b border-lighter flex">
          <h1 class="text-xl font-bold flex-1">Chats</h1>
          <button type="button" disabled class="rounded-full w-9 h-9 flex items-center justify-center opacity-50 cursor-not-allowed flat-btn" aria-label="Chat settings (coming soon)" title="Coming soon">
            <i class="fas fa-cog text-xl text-blue" aria-hidden="true"></i>
          </button>
          <button type="button" @click="newMessage()" class="rounded-full w-9 h-9 flex items-center justify-center hover:bg-lightblue ml-1" aria-label="New message">
            <i class="fas fa-plus-circle text-xl text-blue" aria-hidden="true"></i>
          </button>
        </div>

        <!-- chats -->
        <Loader :loading="loading" />
        <div v-if="!loading">
          <div v-if="chats.length === 0" class="flex flex-col items-center justify-center w-full pt-10">
            <div class="w-3/4 flex flex-col items-center justify-center text-center">
              <p class="font-bold text-lg">No messages yet</p>
              <p class="text-sm text-dark">Start a conversation with someone you follow.</p>
              <button
                @click="newMessage()"
                class="mt-4 h-10 px-4 text-white font-semibold bg-blue hover:bg-darkblue rounded-full"
              >New Message</button>
            </div>
          </div>
          <div v-for="chat in chats" :key="chat.id">
            <div v-if="(getUser(chat.other_user_id))">
              <div class="cursor-pointer">
                <div class="w-full p-2 pt-1 pb-1 md:p-4 md:pt-2 md:pb-2 border-b hover:bg-lightest flex"
                  @click="selectChat(chat)">
                  <div class="flex-none mr-2 md:mr-4 pt-1">
                    <a :href="`#/${chat.other_user_id}`">
                      <img :src="getUser(chat.other_user_id).avatar || '/default_profile.png'"
                           class="flex-none w-12 h-12 rounded-full"  />
                    </a>
                  </div>
                  <div class="w-full truncate">
                    <div class="flex items-center w-full">
                      <p class="font-semibold truncate min-w-0">{{ getUser(chat.other_user_id).username || 'Anonymous' }}</p>
                      <p class="text-sm text-dark ml-auto whitespace-nowrap flex-none pl-2">
                        {{ $filters.timeago(chat.updated_at) }}
                      </p>
                    </div>
                    <p class="pb-2 truncate" v-linkify>{{ chat.last_message || "" }}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="w-full border-l border-r border-lighter h-screen flex items-center justify-center">
        <div class="text-center px-6">
          <h2 class="text-2xl font-bold mb-2">Your messages</h2>
          <p class="text-dark mb-4">Choose a chat from the list, or start a new conversation.</p>
          <button
            @click="newMessage()"
            class="h-10 px-4 text-white font-semibold bg-blue hover:bg-darkblue rounded-full"
          >New Message</button>
        </div>
      </div>

      <NewMessageOverlay
        v-if="showNewMessageModal"
        v-model:showNewMessageModal="showNewMessageModal"
        :profileId="profileId"
        @selected="selected"
      />
    </div>
  </div>
</template>

<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";

export default {
  name: "Chats",
  components: {
    NewMessageOverlay: defineAsyncComponent(() => import('../components/NewMessageOverlay.vue')),
    Loader: defineAsyncComponent(() => import('../components/Loader.vue')),
    SideNav: defineAsyncComponent(() => import('../components/SideNav.vue')),
  },
  data() {
    return {
      loading: true,
      showNewMessageModal: false,
      chats: [],
      profileId: "",
      usersMap: new Map(),
      otherUser: undefined,
      refreshTimer: null,
      refreshInFlight: false,
    };
  },
  methods: {
    newMessage() {
      this.showNewMessageModal = true;
    },
    async selectChat(chat) {
      console.log("select chat", JSON.stringify(chat))

      if (!chat || !chat.id) {
        return
      }
      this.$router.push({
        name: 'Messages',
        params: {
          id: this.$route.params.id,
          chatId: chat.id,
        },
      });
    },
    async selected(user) {
      console.log("selected converstions user", JSON.stringify(user))

      if (!user || !user.id) {
        console.error("conversations: cannot select absent user", JSON.stringify(user))
        return;
      }
      this.showNewMessageModal = false;

      // Check if chat already exists
      const existingChat = this.chats.find(
        conv => conv.other_user_id === user.id
      );

      if (existingChat) {
        await this.selectChat(existingChat);
        return;
      }
      // Create new chat
      const newChat = await warpnetService.createChat(user.id);
      if (!newChat || !newChat.id) {
        console.error("conversations: cannot create new chat", JSON.stringify(user))
      }
      await this.selectChat(newChat);
    },
    getUser(userId) {
      return this.usersMap.get(userId);
    },
    async loadChatUser(userId) {
      if (!userId || userId.length === 0) {
        return
      }

      const u = await warpnetService.getProfile(userId)
      u.avatar = await warpnetService.getImage({userId:u.id, key:u.avatar_key})
      this.usersMap.set(u.id, u)
    },
    async loadMore() {
      const chats = await warpnetService.getChats(false);
      for (const chat of chats) {
        await this.loadChatUser(chat.other_user_id)
        await this.loadChatUser(chat.owner_id)
      }
      const known = new Set(this.chats.map((c) => c.id));
      this.chats = [...this.chats, ...chats.filter((c) => !known.has(c.id))];
    },
    // Poll-driven live updates (no server push on the bridge): re-fetch
    // page 1 of the chat list and merge by id so new incoming chats and
    // last-message previews appear without a manual page reload. The
    // pagination cursor is saved/restored so loadMore isn't reset.
    async refreshChats() {
      if (this.refreshInFlight || this.loading) return;
      this.refreshInFlight = true;
      try {
        warpnetService.markMessageNotificationsRead().catch(() => {});
        const savedCursor = warpnetService.getCursor('chats');
        const chats = await warpnetService.getChats(true);
        warpnetService.setCursor('chats', savedCursor);
        for (const chat of chats) {
          if (!this.usersMap.has(chat.owner_id)) await this.loadChatUser(chat.owner_id);
          if (!this.usersMap.has(chat.other_user_id)) await this.loadChatUser(chat.other_user_id);
          if (chat.owner_id !== this.profileId) {
            [chat.owner_id, chat.other_user_id] = [chat.other_user_id, chat.owner_id];
          }
        }
        if (chats.length > 0) {
          const freshIds = new Set(chats.map((c) => c.id));
          this.chats = [...chats, ...this.chats.filter((c) => !freshIds.has(c.id))];
        }
      } catch (err) {
        console.error('Failed to refresh chats:', err);
      } finally {
        this.refreshInFlight = false;
      }
    },
  },

  async created() {
      console.log("loading component:", this.$options.name);
      this.profileId = this.$route.params.id
      warpnetService.markMessageNotificationsRead().catch(() => {});
      await this.loadChatUser(this.profileId)

      const chats = await warpnetService.getChats(true);

      for (const chat of chats) {
        await this.loadChatUser(chat.owner_id)
        await this.loadChatUser(chat.other_user_id)

        if (chat.owner_id !== this.profileId) {
          [chat.owner_id, chat.other_user_id] = [chat.other_user_id, chat.owner_id];
        }
      }
      this.chats = chats;
      this.loading = false;

      this.refreshTimer = setInterval(() => this.refreshChats(), 3000);
    },
  beforeUnmount() {
    if (this.refreshTimer) {
      clearInterval(this.refreshTimer);
      this.refreshTimer = null;
    }
  },
};
</script>
