<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div id="app" class="flex container h-screen w-full">
    <div class="flex container h-screen w-full">
      <SideNav />

      <div class="w-full h-full overflow-y-scroll no-scrollbar" v-scroll:bottom="loadMore">
        <div class="px-5 pt-3 flex items-center">
          <button
            @click="gotoProfile()"
            class="rounded-full p-3 px-4 focus:outline-none hover:bg-lightblue"
          >
            <i class="fas fa-arrow-left text-blue"></i>
          </button>
          <div class="lg:block ml-4">
            <h1 class="text-xl font-bold">{{ profile?.username }}</h1>
            <p class="text-left text-sm leading-tight text-dark">
              @{{ profile?.id }}
            </p>
          </div>
        </div>

        <div class="flex flex-row justify-evenly mt-2">
          <button
            class="w-1/2 text-dark font-bold border-b-2 border-blue px-10 py-4 hover:bg-lightblue"
          >
            Followers
          </button>
          <button
            @click="goToFollowing()"
            class="w-1/2 text-dark font-bold border-b-2 px-10 py-4 hover:bg-lightblue"
          >
            Following
          </button>
        </div>

        <Loader :loading="loading" />
        <div
          v-if="!loading && profiles.length === 0"
          class="flex flex-col items-center justify-center w-full pt-10 px-6 text-center"
        >
          <p class="font-bold text-lg">No followers yet</p>
          <p class="text-sm text-dark">When someone follows {{ profile?.username || 'this user' }}, they'll show up here.</p>
        </div>
        <Users v-if="profiles.length" :users="profiles" :loading="loading" />
      </div>

      <div
        class="hidden md:block w-1/3 z-0 h-full border-l border-lighter px-6 py-2 overflow-y-scroll no-scrollbar relative"
      >
        <SearchBar />
      </div>
    </div>
  </div>
</template>

<script>
import SideNav from "../components/SideNav.vue";
import SearchBar from "../components/SearchBar.vue";
import Users from "../components/Users.vue";
import Loader from "../components/Loader.vue";
import {warpnetService} from "@/service/service";

export default {
  name: "Followers",
  components: {
    SideNav,
    SearchBar,
    Users,
    Loader,
  },
  data() {
    return {
      loading: true,
      profile: undefined,
      profiles: [],
      pendingProfiles: new Set(),
    };
  },
  methods: {
    gotoProfile() {
      this.$router.push({
        name: "Profile",
        params: {
          id: this.profile.id,
        },
      });
    },
    goToFollowing() {
      this.$router.push({
        name: "Following",
        params: {
          id: this.profile.id,
        },
      });
    },
    // Each row hydrates independently: the profile replaces its placeholder
    // when it arrives, the avatar updates the entry separately, and a
    // hanging peer only leaves its own placeholder in place.
    async hydrateProfile(id) {
      if (!id || this.pendingProfiles.has(id)) return;
      this.pendingProfiles.add(id);
      try {
        let u;
        try {
          u = await warpnetService.getProfile(id, this.profile?.node_id);
        } catch (err) {
          console.error('failed to load follower profile:', id, err);
        }
        const i = this.profiles.findIndex((p) => p && p.id === id);
        if (i === -1) return;
        if (!u || !u.id) {
          this.profiles.splice(i, 1);
          return;
        }
        this.profiles.splice(i, 1, u);
        try {
          const avatar = await warpnetService.getImage({userId: id, key: u.avatar_key});
          if (avatar) {
            const j = this.profiles.findIndex((p) => p && p.id === id);
            if (j !== -1) this.profiles.splice(j, 1, {...u, avatar});
          }
        } catch (err) {
          console.warn('failed to load follower avatar:', id, err);
        }
      } finally {
        this.pendingProfiles.delete(id);
      }
    },
    seedProfiles(ids) {
      const fresh = [];
      for (const id of ids || []) {
        if (!id || this.profiles.some((p) => p && p.id === id)) continue;
        this.profiles.push({ id });
        fresh.push(id);
      }
      return Promise.all(fresh.map((id) => this.hydrateProfile(id)));
    },
    async loadMore() {
      const followers = await warpnetService.getFollowers({userId:this.profile.id, cursorReset: false})
      this.seedProfiles(followers);
    },
  },
  async created() {
    console.log("loading component:", this.$options.name);
    try {
      const profileId = this.$route.params.id;
      if (!profileId) {
        throw new Error('Profile ID is required');
      }

      this.profile = await warpnetService.getProfile(profileId);

      const followers = await warpnetService.getFollowers({userId: profileId, cursorReset: true})
      await Promise.race([
        this.seedProfiles(followers),
        new Promise((resolve) => setTimeout(resolve, 1000)),
      ]);
    } catch (err) {
        console.error("loading component:", this.$options.name, err)
    } finally {
      this.loading = false;
    }
  },
};
</script>
