<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div id="app" class="flex container h-screen w-full">
    <!-- side navigation -->
    <SideNav />

    <!-- timeline -->
    <div
      class="w-full h-full overflow-y-scroll no-scrollbar"
      v-scroll:bottom="loadMore"
    >
      <div
        class="px-5 py-3 border-b border-lighter flex items-center justify-between"
      >
        <h1 class="text-xl font-bold">Home</h1>
        <button
            @click="toggleInfo"
            class="text-xl text-blue cursor-pointer hover:bg-lighter rounded-full w-9 h-9 flex items-center justify-center"
            aria-label="Show node info"
            type="button"
        >
          <i class="fas fa-info-circle" aria-hidden="true"></i>
        </button>
      </div>
      <div
        class="px-5 py-3 border-b-8 border-lighter flex"
        @dragover.prevent
        @drop.prevent="onImageDrop"
      >
        <div v-if="profile" class="flex-none mr-4">
          <img
            :src="profile.avatar || '/default_profile.png'"
            class="flex-none w-12 h-12 rounded-full object-cover bg-transparent"
          />
        </div>
        <div class="w-full">
          <label for="compose-tweet" class="sr-only">Compose a tweet</label>
          <textarea
            id="compose-tweet"
            ref="composeTweet"
            v-model="tweet.text"
            maxlength="2000"
            placeholder="What's happening?"
            class="w-full focus:outline-none mt-3 pb-3"
          ></textarea>
          <div class="text-right text-xs text-dark">{{ tweet.text.length }} / 2000</div>
          <div v-if="imageAttachments.length > 0" class="flex flex-wrap gap-2 mt-2 mb-2">
            <div v-for="(img, index) in imageAttachments" :key="img" class="relative inline-block">
              <img
                  :src="img"
                  alt="Image preview"
                  class="w-32 h-32 object-cover rounded border border-lighter"
              />
              <button
                  v-if="imageKeys[index]"
                  @click="openAltModal(index)"
                  type="button"
                  class="absolute bottom-1 left-1 bg-white bg-opacity-90 rounded px-2 py-0.5 text-xs font-semibold text-dark hover:bg-blue hover:text-white"
                  title="Edit alt text"
              >
                ALT
              </button>
              <button
                  @click="removeImageAttachment(index)"
                  type="button"
                  class="absolute top-0 right-0 mt-1 mr-1 bg-white bg-opacity-75 rounded-full p-1 hover:bg-red-500"
                  title="Remove image"
              >
                <i class="fas fa-times text-red-600 hover:text-white"></i>
              </button>
            </div>
          </div>
          <div class="flex items-center justify-between border-t border-lighter pt-2">
            <div class="flex items-center">
              <button
                  @click="openFileInput('imageUrlFileInput')"
                  class="text-lg text-blue mr-3 rounded-full w-9 h-9 flex items-center justify-center hover:bg-lightblue"
                  :class="{'opacity-50 cursor-not-allowed': imageAttachments.length >= 4}"
                  type="button"
                  :disabled="imageAttachments.length >= 4"
                  aria-label="Attach image"
                  :title="imageAttachments.length >= 4 ? 'Maximum 4 images' : 'Attach image'"
              >
                <i class="far fa-image" aria-hidden="true"></i>
              </button>
              <input
                  @change="fileChange('imageUrlFileInput')"
                  ref="imageUrlFileInput"
                  accept="image/*"
                  type="file"
                  multiple
                  class="hidden"
              />
              <button type="button" disabled class="text-lg text-blue mr-3 rounded-full w-9 h-9 flex items-center justify-center opacity-50 cursor-not-allowed" aria-label="Attach video (coming soon)" title="Coming soon">
                <i class="fas fa-film" aria-hidden="true"></i>
              </button>
              <button type="button" disabled class="text-lg text-blue mr-3 rounded-full w-9 h-9 flex items-center justify-center opacity-50 cursor-not-allowed" aria-label="Add poll (coming soon)" title="Coming soon">
                <i class="far fa-chart-bar" aria-hidden="true"></i>
              </button>
              <button type="button" disabled class="text-lg text-blue mr-3 rounded-full w-9 h-9 flex items-center justify-center opacity-50 cursor-not-allowed" aria-label="Add emoji (coming soon)" title="Coming soon">
                <i class="far fa-smile" aria-hidden="true"></i>
              </button>
            </div>
            <button
              @click="addNewTweet"
              type="button"
              class="h-10 px-4 text-white font-semibold bg-blue hover:bg-darkblue rounded-full"
              :class="(tweet.text.trim() && pendingReads === 0) ? '' : 'opacity-50 cursor-not-allowed'"
              :disabled="!tweet.text.trim() || pendingReads > 0"
            >
              Tweet
            </button>
          </div>
        </div>
      </div>

      <!-- timeline -->
      <Loader :loading="loading" />
      <div
        v-if="!loading && timeline.length === 0"
        class="flex flex-col items-center justify-center w-full pt-10 px-6"
      >
        <p class="font-bold text-lg">Welcome to Warpnet!</p>
        <p class="text-sm text-dark text-center">
          This is the best place to see what's happening in your world. Find
          some people and topics to follow now.
        </p>
        <button
          @click="showImportModal = true"
          class="text-white bg-blue rounded-full font-semibold mt-4 px-4 py-2 hover:bg-darkblue"
        >
          <p class="hidden lg:block">Import tweets from X</p>
          <i class="fas fa-file-import lg:hidden"></i>
        </button>
      </div>
      <Tweets :tweets="timeline" />
    </div>
    <InfoOverlay
        :visible="showInfo"
        :content="infoContent"
        :position="infoPosition"
    />
    <!-- Toast notifications -->
    <div v-if="toastMessage" class="toast-container">
      <div :class="['toast', toastType === 'error' ? 'toast-error' : 'toast-success']" role="alert">
        <i :class="toastType === 'error' ? 'fas fa-exclamation-circle' : 'fas fa-check-circle'" aria-hidden="true"></i>
        {{ toastMessage }}
      </div>
    </div>
    <!-- default right bar -->
    <DefaultRightBar
        :profile="profile"
    />

    <AltTextModal
        v-if="altModalIndex >= 0 && imageKeys[altModalIndex]"
        :show="altModalIndex >= 0"
        :imageKey="imageKeys[altModalIndex]"
        :previewUrl="imageAttachments[altModalIndex] || ''"
        @close="altModalIndex = -1"
    />

    <ImportTweetsModal
        :show="showImportModal"
        @close="showImportModal = false"
        @imported="onTweetsImported"
    />
  </div>
</template>

<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";
import {parseDeepLink} from "@/lib/deeplink";

export default {
  name: "Home",
  components: {
    SideNav: defineAsyncComponent(() => import('@/components/SideNav.vue')),
    DefaultRightBar: defineAsyncComponent(() => import('@/components/DefaultRightBar.vue')),
    Tweets: defineAsyncComponent(() => import('@/components/Tweets.vue')),
    Loader: defineAsyncComponent(() => import('@/components/Loader.vue')),
    InfoOverlay: defineAsyncComponent(() => import('@/components/InfoOverlay.vue')),
    AltTextModal: defineAsyncComponent(() => import('@/components/AltTextModal.vue')),
    ImportTweetsModal: defineAsyncComponent(() => import('@/components/ImportTweetsModal.vue')),
  },
  data() {
    return {
      tweet: {
        text: "",
        root_id: "",
      },
      loading: true,
      profile: {},
      showImportModal: false,
      timeline: [],
      showInfo: false,
      infoContent: '',
      infoPosition: { top: '0px', left: '0px' },
      imageAttachments: [],
      imageKeys: [],
      pendingReads: 0,
      altModalIndex: -1,
      videoAttachment: undefined,
      toastMessage: '',
      toastType: 'error',
      toastTimeoutId: null,
    };
  },
  methods: {
    focusCompose() {
      this.$nextTick(() => {
        const el = this.$refs.composeTweet;
        if (el) {
          el.scrollIntoView({ behavior: 'smooth' });
          el.focus();
        }
      });
    },
    openFileInput(ref) {
      this.$refs[ref].click();
    },
    async fileChange(ref) {
      this.addImageFiles(Array.from(this.$refs[ref].files));
      if (this.$refs[ref]) {
        this.$refs[ref].value = '';
      }
    },
    onImageDrop(event) {
      const files = Array.from(event.dataTransfer?.files || [])
          .filter(f => f.type && f.type.startsWith('image/'));
      if (files.length === 0) return;
      this.addImageFiles(files);
    },
    addImageFiles(files) {
      const remaining = 4 - this.imageAttachments.length;
      const toAdd = files.slice(0, remaining);
      for (const file of toAdd) {
        this.pendingReads++;
        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = async () => {
          if (this.imageAttachments.length < 4) {
            const slot = this.imageAttachments.length;
            this.imageAttachments.push(reader.result);
            this.imageKeys.push('');
            try {
              const key = await warpnetService.uploadImage(reader.result);
              if (key) this.imageKeys[slot] = key;
            } catch (err) {
              console.error('Failed to upload image:', err);
              this.showToast('Failed to upload image. Please try again.', 'error');
            }
          }
          this.pendingReads--;
        };
        reader.onerror = (error) => {
          console.error("Error reading file", error);
          this.showToast('Error reading file. Please try again.', 'error');
          this.pendingReads--;
        };
      }
    },
    removeImageAttachment(index) {
      this.imageAttachments.splice(index, 1);
      this.imageKeys.splice(index, 1);
    },
    openAltModal(index) {
      this.altModalIndex = index;
    },
    async addNewTweet() {
      if (!this.tweet.text.trim()) return;
      const draftText = this.tweet.text;
      const draftImages = this.imageAttachments;
      try {
        // Use pre-uploaded keys when available (fresh attachments). Fall
        // back to a bulk upload for any slots that haven't been uploaded
        // yet (e.g. attached while offline, retried).
        let imageKeys = this.imageKeys.filter(k => k);
        const missing = draftImages.filter((_, i) => !this.imageKeys[i]);
        if (missing.length > 0) {
          const extra = await warpnetService.uploadImages(missing);
          imageKeys = imageKeys.concat(extra);
        }
        await warpnetService.createTweet({text: draftText, imageKeys});

        this.tweet.text = "";
        this.imageAttachments = [];
        this.imageKeys = [];

        this.timeline = await warpnetService.getMyTimeline(true);
      } catch (err) {
        console.error('Failed to post tweet:', err);
        this.showToast('Failed to post tweet. Please try again.', 'error');
      }
    },
    async loadMore() {
      const timeline = await warpnetService.getMyTimeline(false);
      this.timeline = this.timeline.concat(timeline);
    },
    async toggleInfo(event) {
      if (this.showInfo) {
        this.showInfo = false;
        return;
      }

      const rect = event.currentTarget.getBoundingClientRect();
      this.infoContent = await this.getInfo();

      this.infoPosition = {
        top: `${rect.bottom + window.scrollY}px`,
        left: `${rect.left + window.scrollX}px`,
      };

      this.showInfo = true;
    },
    async getInfo() {
      return await warpnetService.getNodeInfo();
    },
    showToast(message, type = 'error') {
      if (this.toastTimeoutId) clearTimeout(this.toastTimeoutId);
      this.toastMessage = message;
      this.toastType = type;
      this.toastTimeoutId = setTimeout(() => {
        this.toastMessage = '';
        this.toastTimeoutId = null;
      }, 4000);
    },
    onTweetsImported(result) {
      const n = (result && result.imported_tweets) || 0;
      this.showToast(`Imported ${n} tweet${n === 1 ? '' : 's'}. View them on your profile.`, 'success');
    },
    async consumeDeepLink() {
      // No URL router for profiles — route through Search.
      const link = parseDeepLink(await warpnetService.consumePendingDeepLink());
      if (link && link.kind === "user") {
        this.$router.push({ name: "Search", query: { q: link.id } });
      }
    },
  },
  async created() {
    console.log("loading component:", this.$options.name);

    this.profile = warpnetService.getOwnerProfile();

    try {
      const fullProfile = await warpnetService.getProfile(this.profile.user_id);
      if (fullProfile && !fullProfile.code) {
        this.profile.background_image = fullProfile.background_image_key
            ? await warpnetService.getImage({userId:this.profile.user_id, key:fullProfile.background_image_key})
            : null;
        this.profile.avatar = fullProfile.avatar_key
            ? await warpnetService.getImage({userId:this.profile.user_id, key:fullProfile.avatar_key})
            : null;
      }
    } catch (error) {
      console.error("Failed to load profile assets:", error);
    }

    this.timeline = await warpnetService.getMyTimeline(true);
    this.loading = false;

    // macOS hot-path: re-check on focus so subsequent clicks also route.
    this.consumeDeepLink();
    this._deepLinkFocusHandler = () => this.consumeDeepLink();
    window.addEventListener("focus", this._deepLinkFocusHandler);
  },
  mounted() {
    // The compose hint is handled here (not in created) so the textarea
    // ref is guaranteed to exist — otherwise "Tweet" from another page
    // silently lands on Home without focusing the composer.
    if (this.$route.query.compose) {
      this.focusCompose();
    }
  },
  watch: {
    '$route.query.compose'(val) {
      if (val) {
        this.focusCompose();
      }
    },
  },
  beforeUnmount() {
    if (this.toastTimeoutId) {
      clearTimeout(this.toastTimeoutId);
      this.toastTimeoutId = null;
    }
    if (this._deepLinkFocusHandler) {
      window.removeEventListener("focus", this._deepLinkFocusHandler);
      this._deepLinkFocusHandler = null;
    }
  },
};
</script>