<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div id="app" class="flex h-screen w-full">
    <!-- Sidebar -->
    <SideNav />

    <!-- Chats list (center column) -->
    <div class="hidden md:flex flex-col w-1/3 h-full overflow-y-scroll border-r border-lighter">
      <div class="px-5 py-3 border-b border-lighter flex items-center">
        <h1 class="text-xl font-bold flex-1">Chats</h1>
        <button type="button" disabled class="rounded-full w-9 h-9 flex items-center justify-center opacity-50 cursor-not-allowed flat-btn" aria-label="Chat settings (coming soon)" title="Coming soon">
          <i class="fas fa-cog text-xl text-blue" aria-hidden="true"></i>
        </button>
        <button type="button" @click="newMessage()" class="rounded-full w-9 h-9 flex items-center justify-center hover:bg-lightblue ml-1" aria-label="New message">
          <i class="fas fa-plus-circle text-xl text-blue" aria-hidden="true"></i>
        </button>
      </div>

      <Loader :loading="loading" />

      <template v-if="!loading">
        <div v-if="visibleChats.length === 0" class="flex flex-col items-center justify-center pt-10">
          <p class="font-bold text-lg">No chats yet</p>
          <p class="text-sm text-dark">Wait until someone starts a chat here.</p>
        </div>

        <div v-for="chat in visibleChats" :key="chat.id"
             class="cursor-pointer"
             :class="chat.id === active?.id ? 'border-r-2 border-blue' : ''"
             @click="selectChat(chat)">
          <div class="flex items-start px-4 py-2 hover:bg-lightest border-b">
            <div class="mr-4">
              <img
                  :src="getUser(chat.other_user_id)?.avatar || '/default_profile.png'"
                  class="h-12 w-12 rounded-full object-cover bg-transparent"
              />
            </div>
            <div class="w-full truncate">
              <div class="flex items-center">
                <p class="font-semibold truncate">{{ getUser(chat.other_user_id)?.username || 'Anonymous' }}</p>
                <p class="text-sm text-dark ml-2 truncate hidden md:block">
                  @{{ chat.other_user_id }}
                </p>
                <p class="text-sm text-dark ml-auto">
                  {{ $filters.timeago(chat.updated_at) }}
                </p>
              </div>
              <p class="text-sm truncate" v-linkify>{{ chat.last_message || '' }}</p>
            </div>
          </div>
        </div>
      </template>
    </div>

    <!-- Placeholder (right column, if no active chat selected) -->
    <div v-if="loading || !active" class="flex flex-col w-full md:w-2/3 h-full items-center justify-center">
      <div class="w-3/5 text-center">
        <p class="font-bold text-lg">You don’t have a message selected</p>
        <p class="text-sm text-dark mt-2">
          This is where you’ll see messages from people you don’t follow.
        </p>
        <button
            @click="newMessage()"
            class="mt-5 h-10 px-4 text-white font-semibold bg-blue hover:bg-darkblue rounded-full"
        >
          New Message
        </button>
      </div>
    </div>

    <!-- Messages view -->
    <div v-if="!loading && active" class="flex flex-col w-full md:w-2/3 h-full">
      <!-- Top bar -->
      <div class="flex items-center px-5 py-2 border-b border-lighter bg-white sticky top-0">
        <button @click="gotoHome()" class="block md:hidden mr-2 focus:outline-none">
          <i class="fas fa-arrow-left text-blue"></i>
        </button>
        <button type="button" @click="gotoProfile(active.other_user_id)" class="flex items-center text-left flat-btn" aria-label="View profile">
          <div class="mr-4">
            <img
                :src="getUser(active.other_user_id)?.avatar || '/default_profile.png'"
                class="w-6 h-6 rounded-full object-cover bg-transparent"
            />
          </div>
          <div class="flex flex-col">
            <h1 class="font-bold">{{ getUser(active.other_user_id)?.username }}</h1>
            <p class="text-xs text-dark">@{{ active.other_user_id }}</p>
          </div>
        </button>
        <button type="button" @click="askDeleteChat" class="ml-auto rounded-full w-9 h-9 flex items-center justify-center hover:bg-red-100 flat-btn" aria-label="Delete chat">
          <i class="fas fa-trash text-xl text-red-500" aria-hidden="true"></i>
        </button>
      </div>

      <!-- Privacy notice -->
      <div class="px-5 py-2 border-b border-lighter bg-white flex items-center justify-center">
        <i class="fas fa-lock text-xs text-dark mr-2" aria-hidden="true"></i>
        <p class="text-xs text-dark text-center">
          Message sending is end-to-end encrypted and stored only on your device and theirs.
        </p>
      </div>

      <!-- Messages -->
      <div ref="messagesScroll" class="flex-1 overflow-y-scroll px-5 pt-5 no-scrollbar" v-scroll:top="loadMore">
        <div class="flex flex-col">
          <div v-for="message in messages" :key="message.id">
            <!-- Own message -->
            <div v-if="message.sender_id === ownerProfile.user_id" class="group flex items-center justify-end mb-4">
              <button
                  v-if="message.id && !message.pending"
                  type="button"
                  @click="askDeleteMessage(message)"
                  class="mr-2 w-7 h-7 rounded-full items-center justify-center hover:bg-red-100 hidden group-hover:flex flat-btn"
                  aria-label="Delete message"
                  title="Delete message"
              >
                <i class="fas fa-trash text-sm text-red-500" aria-hidden="true"></i>
              </button>
              <div class="text-white py-2 px-4 rounded-tl-3xl rounded-bl-3xl rounded-tr-xl" :class="message.pending ? 'bg-blue opacity-70' : 'bg-blue'">
                <p v-if="message.text">{{ message.text }}</p>
                <ChatVideo
                    v-if="message.video_key"
                    :videoKey="message.video_key"
                    :senderId="message.sender_id"
                    :poster="(message.images && message.images[0]) || ''"
                />
                <img
                    v-else-if="message.images && message.images.length === 1"
                    :src="message.images[0]"
                    alt="Attachment"
                    class="max-w-xs rounded-lg mt-1"
                />
                <div
                    v-else-if="message.images && message.images.length > 1"
                    class="mt-1 grid grid-cols-2 gap-1 max-w-xs rounded-lg overflow-hidden"
                >
                  <img
                      v-for="(img, i) in message.images"
                      :key="i"
                      :src="img"
                      alt="Attachment"
                      class="w-full h-24 object-cover"
                  />
                </div>
              </div>
              <p class="text-xs text-dark ml-2">
                <span v-if="message.pending"><i class="fas fa-clock" aria-hidden="true"></i> Sending…</span>
                <span v-else>{{ $filters.time(message.created_at) }}</span>
              </p>
            </div>
            <!-- Incoming message -->
            <div v-else class="flex items-start mb-4">
              <img
                  :src="getUser(active.other_user_id)?.avatar || '/default_profile.png'"
                  class="h-8 w-8 rounded-full mr-2 object-cover bg-transparent cursor-pointer"
                  @click="gotoProfile(active.other_user_id)"
              />
              <div class="bg-lighter text-black py-2 px-4 rounded-tr-3xl rounded-tl-xl rounded-br-3xl">
                <p v-if="message.text">{{ message.text }}</p>
                <ChatVideo
                    v-if="message.video_key"
                    :videoKey="message.video_key"
                    :senderId="message.sender_id"
                    :poster="(message.images && message.images[0]) || ''"
                />
                <img
                    v-else-if="message.images && message.images.length === 1"
                    :src="message.images[0]"
                    alt="Attachment"
                    class="max-w-xs rounded-lg mt-1"
                />
                <div
                    v-else-if="message.images && message.images.length > 1"
                    class="mt-1 grid grid-cols-2 gap-1 max-w-xs rounded-lg overflow-hidden"
                >
                  <img
                      v-for="(img, i) in message.images"
                      :key="i"
                      :src="img"
                      alt="Attachment"
                      class="w-full h-24 object-cover"
                  />
                </div>
              </div>
              <p class="text-xs text-dark ml-2">{{ $filters.time(message.created_at) }}</p>
            </div>
          </div>
          <div ref="scrollToMe"></div>
        </div>
      </div>

      <!-- Input -->
      <div class="px-5 py-3 border-t border-lighter bg-white">
        <div v-if="imageAttachments.length > 0" class="flex flex-wrap gap-2 mb-2">
          <div v-for="(img, index) in imageAttachments" :key="index" class="relative inline-block">
            <img :src="img" alt="Image preview" class="w-24 h-24 object-cover rounded border border-lighter" />
            <button @click="removeImageAttachment(index)" type="button" class="absolute top-0 right-0 mt-1 mr-1 bg-white bg-opacity-75 rounded-full p-1 hover:bg-red-500 group" title="Remove image" aria-label="Remove image">
              <i class="fas fa-times text-red-600 group-hover:text-white text-xs" aria-hidden="true"></i>
            </button>
            <span v-if="!imageKeys[index]" class="absolute bottom-1 left-1 bg-white bg-opacity-90 rounded px-1 text-xs text-dark">…</span>
          </div>
        </div>
        <div v-if="videoAttachment" class="relative inline-block mb-2">
          <!-- h-24, not max-h-*: this build generates no max-h utilities. -->
          <video :src="videoAttachment.url" preload="metadata" class="h-24 rounded border border-lighter"></video>
          <button @click="removeVideoAttachment" type="button" class="absolute top-0 right-0 mt-1 mr-1 bg-white bg-opacity-75 rounded-full p-1 hover:bg-red-500 group" title="Remove video" aria-label="Remove video">
            <i class="fas fa-times text-red-600 group-hover:text-white text-xs" aria-hidden="true"></i>
          </button>
          <p v-if="videoUploading" class="text-xs text-dark mt-1">Uploading video…</p>
        </div>
        <div class="flex items-center">
          <button
              @click="openFileInput()"
              type="button"
              class="mr-2 rounded-full w-9 h-9 flex items-center justify-center hover:bg-lightblue"
              :class="{'opacity-50 cursor-not-allowed': imageAttachDisabled}"
              :disabled="imageAttachDisabled"
              aria-label="Attach image"
              :title="imageAttachTitle"
          >
            <i class="far fa-image text-blue text-lg" aria-hidden="true"></i>
          </button>
          <input ref="messageImageInput" @change="fileChange()" accept="image/*" type="file" multiple class="hidden" />
          <button
              @click="openVideoInput()"
              type="button"
              class="mr-2 rounded-full w-9 h-9 flex items-center justify-center hover:bg-lightblue"
              :class="{'opacity-50 cursor-not-allowed': videoAttachDisabled}"
              :disabled="videoAttachDisabled"
              aria-label="Attach video"
              :title="videoAttachTitle"
          >
            <i class="fas fa-film text-blue text-lg" aria-hidden="true"></i>
          </button>
          <input ref="messageVideoInput" @change="videoFileChange()" :accept="acceptedVideoTypes" type="file" class="hidden" />
          <div class="relative mr-2" data-emoji-anchor>
            <button
                type="button"
                @click="showEmojiPicker = !showEmojiPicker"
                class="rounded-full w-9 h-9 flex items-center justify-center hover:bg-lightblue"
                aria-label="Add emoji"
                title="Add emoji"
                :aria-expanded="showEmojiPicker"
            >
              <i class="far fa-smile text-blue text-lg" aria-hidden="true"></i>
            </button>
            <EmojiPicker
                v-if="showEmojiPicker"
                drop-up
                @select="insertEmoji"
                @close="showEmojiPicker = false"
            />
          </div>
          <input
              ref="messageInput"
              v-model="text"
              type="search"
              class="flex-1 px-4 py-2 rounded-full bg-lighter focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue text-sm"
              placeholder="Start a new message"
              @keyup.enter="sendMessage"
          />
          <button
              @click="sendMessage"
              :disabled="sendDisabled"
              class="ml-4 w-9 h-9 rounded-full flex items-center justify-center"
              :class="sendDisabled ? 'opacity-50 cursor-default' : 'hover:bg-lightblue'"
              aria-label="Send message"
              :title="videoUploading ? 'Uploading video…' : ''"
          >
            <i class="text-blue text-xl" :class="sending ? 'fas fa-circle-notch fa-spin' : 'fas fa-arrow-right'" aria-hidden="true"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- New message overlay -->
    <NewMessageOverlay
        :profileId="active?.other_user_id"
        v-if="showNewMessageModal"
        v-model:showNewMessageModal="showNewMessageModal"
        @selected="selected"
    />

    <ConfirmDialog
      :show="showDeleteChatConfirm"
      title="Delete chat"
      message="Delete this conversation? This removes it from your device and can't be undone."
      confirm-label="Delete"
      :destructive="true"
      @cancel="showDeleteChatConfirm = false"
      @confirm="deleteCurrentChat"
    />

    <ConfirmDialog
      :show="showDeleteMessageConfirm"
      title="Delete message"
      message="Delete this message? This can't be undone."
      confirm-label="Delete"
      :destructive="true"
      @cancel="showDeleteMessageConfirm = false; messagePendingDelete = null"
      @confirm="deleteMessage"
    />
  </div>
</template>


<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";
import {toast} from "@/lib/toast";
import {isMastodonUser} from "@/lib/network";
import {clampRunes, focusCaret, insertEmoji} from "@/lib/emoji";
import {acceptedVideoAccept, captureVideoPoster, normalizeVideoDataUrl, validateVideoFile} from "@/lib/video";

// Mirrors messageLimit in core/handler/chat.go.
const messageCharLimit = 5000;

// Mirrors maxMessageImages in core/handler/chat.go.
const maxMessageImages = 4;

export default {
  name: "Messages",
  components: {
    SideNav: defineAsyncComponent(() => import('@/components/SideNav.vue')),
    Loader: defineAsyncComponent(() => import('@/components/Loader.vue')),
    NewMessageOverlay: defineAsyncComponent(() => import('@/components/NewMessageOverlay.vue')),
    ConfirmDialog: defineAsyncComponent(() => import('@/components/ConfirmDialog.vue')),
    EmojiPicker: defineAsyncComponent(() => import('@/components/EmojiPicker.vue')),
    ChatVideo: defineAsyncComponent(() => import('@/components/ChatVideo.vue')),
  },
  data() {
    return {
      loading: true,
      showNewMessageModal: false,
      showDeleteChatConfirm: false,
      showDeleteMessageConfirm: false,
      messagePendingDelete: null,
      sending: false,
      tmpSeq: 0,
      chats: [],
      messages: [],
      ownerProfile: undefined,
      active: undefined,
      text: '',
      imageAttachments: [],
      imageKeys: [],
      videoAttachment: undefined,
      videoKey: '',
      videoPosterKey: '',
      videoPoster: '',
      videoUploading: false,
      usersMap: new Map(),
      pendingUsers: new Set(),
      otherUser: undefined,
      refreshTimer: null,
      refreshInFlight: false,
      showEmojiPicker: false,
    };
  },
  watch: {
    // The node caps a message at 5000 runes; keep the composer on the same
    // unit so an emoji-heavy message is never silently rejected on send.
    text(value) {
      const clamped = clampRunes(value, messageCharLimit);
      if (clamped !== value) this.text = clamped;
    },
  },
  computed: {
    // Only chats whose other user resolved are listed. Bridged Mastodon
    // accounts never land in the map, so their legacy chats stay hidden
    // instead of rendering as a clickable "Anonymous" row.
    visibleChats() {
      return this.chats.filter((c) => this.usersMap.has(c.other_user_id));
    },
    acceptedVideoTypes() {
      return acceptedVideoAccept;
    },
    // A message carries either images or a video, never both: the still frame
    // of a video already occupies the message's image keys.
    imageAttachDisabled() {
      return !!this.videoAttachment || this.imageAttachments.length >= maxMessageImages;
    },
    imageAttachTitle() {
      if (this.videoAttachment) return 'Remove the video to attach images';
      return this.imageAttachments.length >= maxMessageImages
          ? `Maximum ${maxMessageImages} images`
          : 'Attach image';
    },
    videoAttachDisabled() {
      return !!this.videoAttachment || this.imageAttachments.length > 0;
    },
    videoAttachTitle() {
      if (this.videoAttachment) return 'Only one video per message';
      if (this.imageAttachments.length > 0) return 'Remove images to attach a video';
      return 'Attach video (MP4 or MOV)';
    },
    sendDisabled() {
      if (this.sending || this.videoUploading) return true;
      return !this.text.length && this.imageAttachments.length === 0 && !this.videoAttachment;
    },
  },
  methods: {
    insertEmoji(emoji) {
      const field = this.$refs.messageInput;
      const next = insertEmoji({
        text: this.text,
        emoji,
        field,
        limit: messageCharLimit,
      });
      if (!next) return;
      this.text = next.text;
      this.$nextTick(() => focusCaret(field, next.caret));
    },
    newMessage() {
      this.showNewMessageModal = true;
    },
    openFileInput() {
      this.$refs.messageImageInput.click();
    },
    fileChange() {
      const input = this.$refs.messageImageInput;
      const files = Array.from((input && input.files) || []);
      if (input) {
        input.value = '';
      }
      // Upload as they are picked, so send only has to hand over the keys.
      for (const file of files.slice(0, maxMessageImages - this.imageAttachments.length)) {
        const reader = new FileReader();
        reader.onload = async () => {
          if (this.imageAttachments.length >= maxMessageImages) return;
          const slot = this.imageAttachments.length;
          this.imageAttachments.push(reader.result);
          this.imageKeys.push('');
          try {
            const key = await warpnetService.uploadImage(reader.result);
            if (key) this.imageKeys[slot] = key;
          } catch (err) {
            console.error('Failed to upload image:', err);
            toast.error('Failed to upload image. Please try again.');
          }
        };
        reader.onerror = (error) => console.error("Error reading file", error);
        reader.readAsDataURL(file);
      }
    },
    removeImageAttachment(index) {
      this.imageAttachments.splice(index, 1);
      this.imageKeys.splice(index, 1);
      if (this.$refs.messageImageInput) {
        this.$refs.messageImageInput.value = '';
      }
    },
    clearImageAttachments() {
      this.imageAttachments = [];
      this.imageKeys = [];
      if (this.$refs.messageImageInput) {
        this.$refs.messageImageInput.value = '';
      }
    },
    openVideoInput() {
      this.$refs.messageVideoInput.click();
    },
    async videoFileChange() {
      const input = this.$refs.messageVideoInput;
      const file = input && input.files && input.files[0];
      if (input) {
        input.value = '';
      }
      if (!file) return;

      const problem = validateVideoFile(file);
      if (problem) {
        toast.error(problem);
        return;
      }

      this.removeVideoAttachment();
      // The blob URL identifies this upload: if the user removes the clip or
      // picks another while it is in flight, this run must stop touching the
      // composer instead of attaching a key the user no longer wants. Compare
      // the URL, not the object — Vue hands back a reactive proxy of it, which
      // never equals the raw object by identity.
      const url = URL.createObjectURL(file);
      this.videoAttachment = {url, name: file.name};
      this.videoUploading = true;
      const isCurrent = () => this.videoAttachment && this.videoAttachment.url === url;

      // The still frame is uploaded as an ordinary image and travels in the
      // message's image key, so the recipient sees a preview without
      // fetching the clip.
      const poster = await this.captureAndUploadPoster(file);
      if (isCurrent()) {
        this.videoPoster = poster.dataUrl;
        this.videoPosterKey = poster.key;
      }

      try {
        const dataUrl = normalizeVideoDataUrl(await this.readFileAsDataURL(file), file);
        const key = await warpnetService.uploadVideo(dataUrl);
        if (!isCurrent()) return;
        if (!key) {
          throw new Error('node returned an empty video key');
        }
        this.videoKey = key;
      } catch (err) {
        console.error('Failed to upload video:', err);
        if (!isCurrent()) return;
        toast.error(err?.message || 'Failed to upload video. Please try again.');
        this.removeVideoAttachment();
      } finally {
        if (!this.videoAttachment || isCurrent()) {
          this.videoUploading = false;
        }
      }
    },
    // Best effort: a clip the browser cannot decode must still send without
    // a preview frame.
    async captureAndUploadPoster(file) {
      try {
        const dataUrl = await captureVideoPoster(file);
        if (!dataUrl) return {dataUrl: '', key: ''};
        return {dataUrl, key: await warpnetService.uploadImage(dataUrl) || ''};
      } catch (err) {
        console.error('Failed to upload video poster:', err);
        return {dataUrl: '', key: ''};
      }
    },
    readFileAsDataURL(file) {
      return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(reader.result);
        reader.onerror = () => reject(reader.error || new Error('file read failed'));
        reader.readAsDataURL(file);
      });
    },
    removeVideoAttachment() {
      if (this.videoAttachment && this.videoAttachment.url) {
        URL.revokeObjectURL(this.videoAttachment.url);
      }
      this.videoAttachment = undefined;
      this.videoKey = '';
      this.videoPosterKey = '';
      this.videoPoster = '';
      if (this.$refs.messageVideoInput) {
        this.$refs.messageVideoInput.value = '';
      }
    },
    gotoHome() {
      this.$router.push({
        name: "Home",
      });
    },
    gotoProfile(userId) {
      if (!userId) return;
      this.$router.push({
        name: "Profile",
        params: { id: userId },
      });
    },
    async sendMessage() {
      if (this.sendDisabled) return;
      if (!this.active?.other_user_id) return;

      const sentText = this.text;
      const sentImages = [...this.imageAttachments];
      const sentImageKeys = [...this.imageKeys];
      const sentVideo = this.videoAttachment;
      const sentVideoKey = this.videoKey;
      const sentVideoPosterKey = this.videoPosterKey;
      const sentVideoPoster = this.videoPoster;

      // Optimistic bubble with a temp id and a "Sending…" status, so the
      // message shows immediately instead of vanishing until the refetch.
      const tempId = `pending-${++this.tmpSeq}`;
      this.messages = [...this.messages, {
        id: tempId,
        pending: true,
        sender_id: this.ownerProfile.user_id,
        text: sentText,
        images: sentVideoPoster ? [sentVideoPoster] : sentImages,
        video_key: sentVideoKey || undefined,
        created_at: new Date().toISOString(),
      }];
      this.scrollToEnd();

      this.sending = true;
      try {
        await this.deliverMessage(sentText, sentImages, sentImageKeys, sentVideoKey, sentVideoPosterKey);
        // The local node accepted the message (queued to its outbox and
        // re-sent when the recipient comes online), so it's safe to clear
        // the composer now.
        this.text = '';
        this.clearImageAttachments();
        this.removeVideoAttachment();
      } catch (err) {
        // The local node itself rejected the send — nothing was queued.
        // Drop the optimistic bubble and keep the text so the user can retry.
        console.error('Failed to send message:', err);
        this.messages = this.messages.filter((m) => m.id !== tempId);
        this.text = sentText;
        this.imageAttachments = sentImages;
        this.imageKeys = sentImageKeys;
        this.videoAttachment = sentVideo;
        this.videoKey = sentVideoKey;
        this.videoPosterKey = sentVideoPosterKey;
        this.videoPoster = sentVideoPoster;
        toast.error(err?.message || "Couldn't send the message. Please try again.");
      } finally {
        this.sending = false;
      }
    },
    async deliverMessage(sentText, sentImages, sentImageKeys, sentVideoKey, sentVideoPosterKey) {
      if (!this.active.id) {
        const chat = await warpnetService.createChat(this.active.other_user_id);
        if (!chat || !chat.id) {
          throw new Error('createChat returned no id');
        }
        this.loadChatUser(chat.owner_id);
        this.loadChatUser(chat.other_user_id);

        this.active = { ...this.active, ...chat };

        const existingIndex = this.chats.findIndex((c) => c.id === chat.id);
        if (existingIndex === -1) {
          this.chats = [...this.chats, chat];
        } else {
          this.chats.splice(existingIndex, 1, { ...this.chats[existingIndex], ...chat });
        }
      }

      // A video message carries its still frame instead of any images.
      let imageKeys = sentVideoKey ? [sentVideoPosterKey].filter(Boolean) : sentImageKeys.filter(Boolean);
      if (!sentVideoKey) {
        // Slots whose eager upload failed (offline, retried) go up now.
        const missing = sentImages.filter((_, i) => !sentImageKeys[i]);
        if (missing.length > 0) {
          imageKeys = imageKeys.concat(await warpnetService.uploadImages(missing));
        }
      }

      await warpnetService.sendDirectMessage({
        chatId: this.active.id,
        receiverId: this.active.other_user_id,
        text: sentText,
        imageKeys: imageKeys,
        videoKey: sentVideoKey,
      });

      // Past this point the message is safely queued on the node. Refreshing
      // the thread / preview is best-effort — a failure here must not be
      // reported as a send failure (which would wrongly restore the composer).
      try {
        await this.selectChat(this.active);

        const chatIndex = this.chats.findIndex((c) => c.id === this.active.id);
        if (chatIndex !== -1) {
          const attachmentPreview = sentVideoKey ? '[video]' : (imageKeys.length > 0 ? '[image]' : '');
          const preview = sentText || attachmentPreview || this.chats[chatIndex].last_message;
          this.chats.splice(chatIndex, 1, {
            ...this.chats[chatIndex],
            last_message: preview,
            updated_at: new Date().toISOString(),
          });
        }
      } catch (err) {
        console.warn('post-send refresh failed (message was sent):', err);
      }
    },
    scrollToEnd() {
      const pin = () => {
        const el = this.$refs.messagesScroll;
        if (el) el.scrollTop = el.scrollHeight;
      };
      this.$nextTick(() => {
        pin();
        setTimeout(pin, 100);
      });
    },
    // Attachment keys ride on the message; the bytes come from the sender's
    // node. A video message carries its still frame as its only image key.
    async hydrateMedia(msgs) {
      await Promise.all(msgs.map(async (msg) => {
        const keys = msg.image_keys || [];
        if (keys.length === 0) return;
        const images = await Promise.all(keys.map(
            (key) => warpnetService.getImage({userId: msg.sender_id, key})
                .catch(() => ''),
        ));
        msg.images = images.filter(Boolean);
      }));
    },
    async selected(user) {
      if (isMastodonUser(user)) {
        return
      }
      console.log("selected messages user", JSON.stringify(user))

      if (!this.ownerProfile.user_id || !user.id) {
        console.error("messages: no selected user ", this.ownerProfile, user)
        return;
      }
      this.showNewMessageModal = false;

      let currentChat = null
      for (const chat of this.chats) {
        const participants = [chat.owner_id, chat.other_user_id];
        if (participants.includes(this.ownerProfile.user_id) && participants.includes(user.id)) {
          currentChat = chat;
          break;
        }
      }

      if (!currentChat) {
        currentChat = {
          id: "",
          other_user_id: user.id,
          owner_id: this.ownerProfile.user_id,
        };
      }
      await this.selectChat(currentChat);
    },
    async selectChat(chat) {
      if (!chat) {
        console.warn("no active chat could be selected")
        return
      }
      this.messages = []; // reset messages
      this.active = chat;

      const messages = await warpnetService.getDirectMessages(
          {chatId: chat.id, cursorReset: true},
      );
      // The user may have switched chats while the fetch was in flight.
      if (this.active?.id !== chat.id) return;
      messages.sort((a, b) => new Date(a.created_at) - new Date(b.created_at));
      this.messages = messages;
      this.scrollToEnd();
      // Attachments fill in per message; text must not wait for blobs.
      this.hydrateMedia(this.messages);
    },
    askDeleteChat() {
      if (!this.active || !this.active.id) return;
      this.showDeleteChatConfirm = true;
    },
    async deleteCurrentChat() {
      this.showDeleteChatConfirm = false;
      if (!this.active || !this.active.id) return;
      try {
        const deletedId = this.active.id;
        await warpnetService.deleteChat(deletedId);
        this.chats = this.chats.filter((c) => c.id !== deletedId);
        this.messages = [];
        this.active = undefined;
      } catch (err) {
        console.error('Failed to delete chat:', err);
        toast.error(err?.message || "Couldn't delete the chat. Please try again.");
      }
    },
    askDeleteMessage(message) {
      if (!this.active?.id || !message?.id) return;
      this.messagePendingDelete = message;
      this.showDeleteMessageConfirm = true;
    },
    async deleteMessage() {
      this.showDeleteMessageConfirm = false;
      const message = this.messagePendingDelete;
      this.messagePendingDelete = null;
      if (!this.active?.id || !message?.id) return;
      try {
        await warpnetService.deleteMessage(this.active.id, message.id);
        this.messages = this.messages.filter((m) => m.id !== message.id);
      } catch (err) {
        console.error('Failed to delete message:', err);
        toast.error(err?.message || "Couldn't delete the message. Please try again.");
      }
    },
    deselectAll() {
      this.active = undefined;
    },
    getUser(userId) {
      return this.usersMap.get(userId);
    },
    async loadChatUser(userId) {
      if (!userId || userId.length === 0) {
        return
      }
      const known = this.usersMap.get(userId)
      if (known && known.username) {
        return
      }
      if (this.pendingUsers.has(userId)) {
        return
      }
      this.pendingUsers.add(userId)
      try {
        let u
        try {
          u = await warpnetService.getProfile(userId)
        } catch (err) {
          console.error('messages: failed to load chat user', userId, err)
        }
        if (!u || !u.id) {
          console.warn('messages: unresolved chat user, showing placeholder', userId)
          if (!isMastodonUser({id: userId})) {
            this.usersMap.set(userId, {id: userId})
          }
          return
        }
        // Leaving a bridged user out of the map hides the whole chat row:
        // the list only renders chats whose other user resolved.
        if (isMastodonUser(u)) {
          this.usersMap.delete(userId)
          return
        }
        this.usersMap.set(userId, u)
        try {
          const avatar = await warpnetService.getImage({userId: userId, key: u.avatar_key})
          if (avatar) {
            this.usersMap.set(userId, {...u, avatar})
          }
        } catch (err) {
          console.warn('messages: failed to load avatar for', userId, err)
        }
      } finally {
        this.pendingUsers.delete(userId)
      }
    },
    // Swap each chat so other_user_id is the peer, seed a placeholder row
    // for peers not yet resolved, and hydrate each one independently.
    normalizeChats(chats) {
      for (const chat of chats) {
        if (chat.owner_id !== this.ownerProfile.user_id) {
          [chat.owner_id, chat.other_user_id] = [chat.other_user_id, chat.owner_id];
        }
        const uid = chat.other_user_id;
        if (uid && !this.usersMap.has(uid) && !isMastodonUser({id: uid})) {
          this.usersMap.set(uid, {id: uid});
        }
      }
      return Promise.all(chats.map((chat) => this.loadChatUser(chat.other_user_id)));
    },
    async loadMore() {
      if (!this.active) return;
      const olderMessages = await warpnetService.getDirectMessages(
          {chatId: this.active.id, cursorReset: false},
      )
      const known = new Set(this.messages.map((m) => m && m.id));
      const fresh = olderMessages.filter((m) => m && m.id && !known.has(m.id));
      if (fresh.length === 0) return;
      const freshIds = new Set(fresh.map((m) => m.id));
      this.messages = [...fresh, ...this.messages]
          .sort((a, b) => new Date(a.created_at) - new Date(b.created_at));
      // Hydrate through the reactive array so the fill-in triggers a render.
      this.hydrateMedia(this.messages.filter((m) => freshIds.has(m.id)));
    },
    isNearBottom() {
      const el = this.$refs.messagesScroll;
      if (!el) return true;
      return el.scrollHeight - el.scrollTop - el.clientHeight < 150;
    },
    // Poll-driven live updates: the node bridge is strictly
    // request/response (no server push), so — like the 2s notification
    // poll in service.js — the chat list and the active chat are
    // re-fetched on an interval and new items merged in by id. The
    // pagination cursors are saved and restored around the page-1
    // fetches so scroll-back pagination isn't reset by the poll.
    async refreshData() {
      if (this.refreshInFlight || this.loading) return;
      this.refreshInFlight = true;
      try {
        warpnetService.markMessageNotificationsRead().catch(() => {});
        const savedChatsCursor = warpnetService.getCursor('chats');
        const chats = await warpnetService.getChats(true);
        warpnetService.setCursor('chats', savedChatsCursor);
        this.normalizeChats(chats);
        if (chats.length > 0) {
          const freshIds = new Set(chats.map((c) => c.id));
          this.chats = [...chats, ...this.chats.filter((c) => !freshIds.has(c.id))];
        }

        const activeId = this.active?.id;
        if (!activeId) return;
        const savedMessagesCursor = warpnetService.getCursor('messages');
        const page = await warpnetService.getDirectMessages(
            {chatId: activeId, cursorReset: true},
        );
        warpnetService.setCursor('messages', savedMessagesCursor);
        // The user may have switched chats while the fetch was in flight.
        if (this.active?.id !== activeId) return;
        const known = new Set(this.messages.map((m) => m && m.id));
        const fresh = page.filter((m) => m && m.id && !known.has(m.id));
        if (fresh.length === 0) return;
        const freshIds = new Set(fresh.map((m) => m.id));
        const wasNearBottom = this.isNearBottom();
        this.messages = [...this.messages, ...fresh]
            .sort((a, b) => new Date(a.created_at) - new Date(b.created_at));
        // Hydrate through the reactive array so the fill-in triggers a render.
        this.hydrateMedia(this.messages.filter((m) => freshIds.has(m.id)));
        if (wasNearBottom) {
          this.scrollToEnd();
        }
      } catch (err) {
        console.error('Failed to refresh chats:', err);
      } finally {
        this.refreshInFlight = false;
      }
    },
  },
  async created() {
    console.log("loading component:", this.$options.name);
    console.log("messages: route chat id:", this.$route.params.chatId)

    this.ownerProfile = warpnetService.getOwnerProfile()
    warpnetService.markMessageNotificationsRead().catch(() => {});
    // Started before the initial load (refreshData no-ops while loading)
    // so a user with no chats yet still picks up an incoming chat live.
    this.refreshTimer = setInterval(() => this.refreshData(), 3000);
    this.loadChatUser(this.ownerProfile.user_id)

    try {
      const chats = await warpnetService.getChats(true)
      if (chats.length === 0) {
        console.warn("messages: chats not found")
        return;
      }

      const activeChat = chats.find((chat) => chat.id === this.$route.params.chatId) || null;
      const hydration = this.normalizeChats(chats);
      this.chats = chats;
      // The fast happy path looks the same as before; a hanging peer
      // profile or attachment holds the loader for at most a second.
      await Promise.race([
        Promise.all([hydration, this.selectChat(activeChat)]),
        new Promise((resolve) => setTimeout(resolve, 1000)),
      ]);
    } catch (err) {
      console.error('messages: failed to load chats:', err);
    } finally {
      this.loading = false;
    }
    this.scrollToEnd();
  },
  beforeUnmount() {
    if (this.refreshTimer) {
      clearInterval(this.refreshTimer);
      this.refreshTimer = null;
    }
  },
};
</script>
