<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div id="app" class="flex h-screen w-full">
    <!-- Sidebar -->
    <SideNav />

    <!-- Chats list (center column) -->
    <div class="hidden md:flex flex-col w-1/3 h-full overflow-y-scroll border-r border-lighter">
      <div class="px-5 py-3 border-b border-lighter flex items-center">
        <h1 class="text-xl font-bold flex-1">Chats</h1>
        <button type="button" disabled class="rounded-full w-9 h-9 flex items-center justify-center opacity-50 cursor-not-allowed flat-btn" aria-label="Chat settings (coming soon)" title="Coming soon">
          <i class="fas fa-cog text-xl text-blue" aria-hidden="true"></i>
        </button>
        <button type="button" @click="newMessage()" class="rounded-full w-9 h-9 flex items-center justify-center hover:bg-lightblue ml-1" aria-label="New message">
          <i class="fas fa-plus-circle text-xl text-blue" aria-hidden="true"></i>
        </button>
      </div>

      <Loader :loading="loading" />

      <template v-if="!loading">
        <div v-if="chats.length === 0" class="flex flex-col items-center justify-center pt-10">
          <p class="font-bold text-lg">No chats yet</p>
          <p class="text-sm text-dark">Wait until someone starts a chat here.</p>
        </div>

        <div v-for="chat in chats" :key="chat.id"
             class="cursor-pointer"
             :class="chat.id === active?.id ? 'border-r-2 border-blue' : ''"
             @click="selectChat(chat)">
          <div class="flex items-start px-4 py-2 hover:bg-lightest border-b">
            <div class="mr-4">
              <img
                  :src="getUser(chat.other_user_id)?.avatar || '/default_profile.png'"
                  class="h-12 w-12 rounded-full object-cover bg-transparent"
              />
            </div>
            <div class="w-full truncate">
              <div class="flex items-center">
                <p class="font-semibold truncate">{{ getUser(chat.other_user_id)?.username || 'Anonymous' }}</p>
                <p class="text-sm text-dark ml-2 truncate hidden md:block">
                  @{{ chat.other_user_id }}
                </p>
                <p class="text-sm text-dark ml-auto">
                  {{ $filters.timeago(chat.updated_at) }}
                </p>
              </div>
              <p class="text-sm truncate" v-linkify>{{ chat.last_message || '' }}</p>
            </div>
          </div>
        </div>
      </template>
    </div>

    <!-- Placeholder (right column, if no active chat selected) -->
    <div v-if="loading || !active" class="flex flex-col w-full md:w-2/3 h-full items-center justify-center">
      <div class="w-3/5 text-center">
        <p class="font-bold text-lg">You don’t have a message selected</p>
        <p class="text-sm text-dark mt-2">
          This is where you’ll see messages from people you don’t follow.
        </p>
        <button
            @click="newMessage()"
            class="mt-5 h-10 px-4 text-white font-semibold bg-blue hover:bg-darkblue rounded-full"
        >
          New Message
        </button>
      </div>
    </div>

    <!-- Messages view -->
    <div v-if="!loading && active" class="flex flex-col w-full md:w-2/3 h-full">
      <!-- Top bar -->
      <div class="flex items-center px-5 py-2 border-b border-lighter bg-white sticky top-0">
        <button @click="gotoHome()" class="block md:hidden mr-2 focus:outline-none">
          <i class="fas fa-arrow-left text-blue"></i>
        </button>
        <button type="button" @click="gotoProfile(active.other_user_id)" class="flex items-center text-left flat-btn" aria-label="View profile">
          <div class="mr-4">
            <img
                :src="getUser(active.other_user_id)?.avatar || '/default_profile.png'"
                class="w-6 h-6 rounded-full object-cover bg-transparent"
            />
          </div>
          <div class="flex flex-col">
            <h1 class="font-bold">{{ getUser(active.other_user_id)?.username }}</h1>
            <p class="text-xs text-dark">@{{ active.other_user_id }}</p>
          </div>
        </button>
        <button type="button" @click="askDeleteChat" class="ml-auto rounded-full w-9 h-9 flex items-center justify-center hover:bg-red-100 flat-btn" aria-label="Delete chat">
          <i class="fas fa-trash text-xl text-red-500" aria-hidden="true"></i>
        </button>
      </div>

      <!-- Messages -->
      <div ref="messagesScroll" class="flex-1 overflow-y-scroll px-5 pt-5 no-scrollbar" v-scroll:top="loadMore">
        <div class="flex flex-col">
          <div v-for="message in messages" :key="message.id">
            <!-- Own message -->
            <div v-if="message.sender_id === ownerProfile.user_id" class="group flex items-center justify-end mb-4">
              <button
                  v-if="message.id"
                  type="button"
                  @click="deleteMessage(message)"
                  class="mr-2 w-7 h-7 rounded-full items-center justify-center hover:bg-red-100 hidden group-hover:flex flat-btn"
                  aria-label="Delete message"
                  title="Delete message"
              >
                <i class="fas fa-trash text-sm text-red-500" aria-hidden="true"></i>
              </button>
              <div class="bg-blue text-white py-2 px-4 rounded-tl-3xl rounded-bl-3xl rounded-tr-xl">
                <p v-if="message.text">{{ message.text }}</p>
                <img v-if="message.image" :src="message.image" alt="Attachment" class="max-w-xs rounded-lg mt-1" />
              </div>
              <p class="text-xs text-dark ml-2">{{ $filters.time(message.created_at) }}</p>
            </div>
            <!-- Incoming message -->
            <div v-else class="flex items-start mb-4">
              <img
                  :src="getUser(active.other_user_id)?.avatar || '/default_profile.png'"
                  class="h-8 w-8 rounded-full mr-2 object-cover bg-transparent cursor-pointer"
                  @click="gotoProfile(active.other_user_id)"
              />
              <div class="bg-lighter text-black py-2 px-4 rounded-tr-3xl rounded-tl-xl rounded-br-3xl">
                <p v-if="message.text">{{ message.text }}</p>
                <img v-if="message.image" :src="message.image" alt="Attachment" class="max-w-xs rounded-lg mt-1" />
              </div>
              <p class="text-xs text-dark ml-2">{{ $filters.time(message.created_at) }}</p>
            </div>
          </div>
          <div ref="scrollToMe"></div>
        </div>
      </div>

      <!-- Input -->
      <div class="px-5 py-3 border-t border-lighter bg-white">
        <div v-if="imageAttachment" class="relative inline-block mb-2">
          <img :src="imageAttachment" alt="Image preview" class="w-24 h-24 object-cover rounded border border-lighter" />
          <button @click="removeImageAttachment" type="button" class="absolute top-0 right-0 mt-1 mr-1 bg-white bg-opacity-75 rounded-full p-1 hover:bg-red-500 group" title="Remove image" aria-label="Remove image">
            <i class="fas fa-times text-red-600 group-hover:text-white text-xs" aria-hidden="true"></i>
          </button>
        </div>
        <div class="flex items-center">
          <button @click="openFileInput()" type="button" class="mr-2 rounded-full w-9 h-9 flex items-center justify-center hover:bg-lightblue" aria-label="Attach image">
            <i class="far fa-image text-blue text-lg" aria-hidden="true"></i>
          </button>
          <input ref="messageImageInput" @change="fileChange()" accept="image/*" type="file" class="hidden" />
          <input
              v-model="text"
              type="search"
              class="flex-1 px-4 py-2 rounded-full bg-lighter focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue text-sm"
              placeholder="Start a new message"
              @keyup.enter="sendMessage"
          />
          <button
              @click="sendMessage"
              :disabled="!text.length && !imageAttachment"
              class="ml-4 w-9 h-9 rounded-full flex items-center justify-center"
              :class="(!text.length && !imageAttachment) ? 'opacity-50 cursor-default' : 'hover:bg-lightblue'"
              aria-label="Send message"
          >
            <i class="fas fa-arrow-right text-blue text-xl" aria-hidden="true"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- New message overlay -->
    <NewMessageOverlay
        :profileId="active?.other_user_id"
        v-if="showNewMessageModal"
        v-model:showNewMessageModal="showNewMessageModal"
        @selected="selected"
    />

    <ConfirmDialog
      :show="showDeleteChatConfirm"
      title="Delete chat"
      message="Delete this conversation? This removes it from your device and can't be undone."
      confirm-label="Delete"
      :destructive="true"
      @cancel="showDeleteChatConfirm = false"
      @confirm="deleteCurrentChat"
    />
  </div>
</template>


<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";

export default {
  name: "Messages",
  components: {
    SideNav: defineAsyncComponent(() => import('@/components/SideNav.vue')),
    Loader: defineAsyncComponent(() => import('@/components/Loader.vue')),
    NewMessageOverlay: defineAsyncComponent(() => import('@/components/NewMessageOverlay.vue')),
    ConfirmDialog: defineAsyncComponent(() => import('@/components/ConfirmDialog.vue')),
  },
  data() {
    return {
      loading: true,
      showNewMessageModal: false,
      showDeleteChatConfirm: false,
      chats: [],
      messages: [],
      ownerProfile: undefined,
      active: undefined,
      text: '',
      imageAttachment: undefined,
      usersMap: new Map(),
      otherUser: undefined,
      refreshTimer: null,
      refreshInFlight: false,
    };
  },
  methods: {
    newMessage() {
      this.showNewMessageModal = true;
    },
    openFileInput() {
      this.$refs.messageImageInput.click();
    },
    fileChange() {
      const file = this.$refs.messageImageInput.files[0];
      if (!file) return;
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => this.imageAttachment = reader.result;
      reader.onerror = (error) => console.error("Error reading file", error);
    },
    removeImageAttachment() {
      this.imageAttachment = undefined;
      if (this.$refs.messageImageInput) {
        this.$refs.messageImageInput.value = '';
      }
    },
    gotoHome() {
      this.$router.push({
        name: "Home",
      });
    },
    gotoProfile(userId) {
      if (!userId) return;
      this.$router.push({
        name: "Profile",
        params: { id: userId },
      });
    },
    sendMessage() {
      if (!this.active.other_user_id || (this.text.length === 0 && !this.imageAttachment)) return;

      // Capture the input into locals and clear the form right away.
      // The user can keep typing / send another message while the
      // network round-trip below runs in the background — no more
      // "input frozen until the message reappears in the chat".
      const sentText = this.text;
      const sentImage = this.imageAttachment;
      this.text = '';
      this.imageAttachment = undefined;
      if (this.$refs.messageImageInput) {
        this.$refs.messageImageInput.value = '';
      }

      // Fire-and-forget. Errors are logged; failed sends do not block
      // the next attempt because nothing in the UI is gating on this
      // promise's resolution.
      this.deliverMessage(sentText, sentImage).catch((err) => {
        console.error('Failed to send message:', err);
      });
    },
    async deliverMessage(sentText, sentImage) {
      if (!this.active.id) {
        const chat = await warpnetService.createChat(this.active.other_user_id);
        if (!chat || !chat.id) {
          throw new Error('createChat returned no id');
        }
        await this.loadChatUser(chat.owner_id);
        await this.loadChatUser(chat.other_user_id);

        this.active = { ...this.active, ...chat };

        const existingIndex = this.chats.findIndex((c) => c.id === chat.id);
        if (existingIndex === -1) {
          this.chats = [...this.chats, chat];
        } else {
          this.chats.splice(existingIndex, 1, { ...this.chats[existingIndex], ...chat });
        }
      }

      let imageKey = '';
      if (sentImage) {
        imageKey = await warpnetService.uploadImage(sentImage);
      }

      await warpnetService.sendDirectMessage({
        chatId: this.active.id,
        receiverId: this.active.other_user_id,
        text: sentText,
        imageKey: imageKey,
      });

      await this.selectChat(this.active);

      const chatIndex = this.chats.findIndex((c) => c.id === this.active.id);
      if (chatIndex !== -1) {
        const preview = sentText || (imageKey ? '[image]' : this.chats[chatIndex].last_message);
        this.chats.splice(chatIndex, 1, {
          ...this.chats[chatIndex],
          last_message: preview,
          updated_at: new Date().toISOString(),
        });
      }
    },
    scrollToEnd() {
      this.$nextTick(() => {
        const el = this.$refs.scrollToMe;
        if (el) {
          el.scrollIntoView({ behavior: "smooth" });
        }
        if (!this.$refs.input) {
          return
        }
        setTimeout(() => this.$refs.input.focus(), 500);
      });
    },
    async selected(user) {
      console.log("selected messages user", JSON.stringify(user))

      if (!this.ownerProfile.user_id || !user.id) {
        console.error("messages: no selected user ", this.ownerProfile, user)
        return;
      }
      this.showNewMessageModal = false;

      let currentChat = null
      for (const chat of this.chats) {
        const participants = [chat.owner_id, chat.other_user_id];
        if (participants.includes(this.ownerProfile.user_id) && participants.includes(user.id)) {
          currentChat = chat;
          break;
        }
      }

      if (!currentChat) {
        currentChat = {
          id: "",
          other_user_id: user.id,
          owner_id: this.ownerProfile.user_id,
        };
      }
      await this.selectChat(currentChat);
    },
    async selectChat(chat) {
      if (!chat) {
        console.warn("no active chat could be selected")
        return
      }
      this.messages = []; // reset messages
      this.active = chat;

      this.messages = await warpnetService.getDirectMessages(
          {chatId: chat.id, cursorReset: true},
      );
      await Promise.all(this.messages.map(async (msg) => {
        if (msg.image_key) {
          msg.image = await warpnetService.getImage({userId: msg.sender_id, key: msg.image_key});
        }
      }));
      this.messages.sort((a, b) => new Date(a.created_at) - new Date(b.created_at));
      this.scrollToEnd();
    },
    askDeleteChat() {
      if (!this.active || !this.active.id) return;
      this.showDeleteChatConfirm = true;
    },
    async deleteCurrentChat() {
      this.showDeleteChatConfirm = false;
      if (!this.active || !this.active.id) return;
      try {
        const deletedId = this.active.id;
        await warpnetService.deleteChat(deletedId);
        this.chats = this.chats.filter((c) => c.id !== deletedId);
        this.messages = [];
        this.active = undefined;
      } catch (err) {
        console.error('Failed to delete chat:', err);
      }
    },
    async deleteMessage(message) {
      if (!this.active?.id || !message?.id) return;
      try {
        await warpnetService.deleteMessage(this.active.id, message.id);
        this.messages = this.messages.filter((m) => m.id !== message.id);
      } catch (err) {
        console.error('Failed to delete message:', err);
      }
    },
    deselectAll() {
      this.active = undefined;
    },
    getUser(userId) {
      return this.usersMap.get(userId);
    },
    async loadChatUser(userId) {
      const u = await warpnetService.getProfile(userId)
      u.avatar = await warpnetService.getImage({userId:u.id, key:u.avatar_key})
      this.usersMap.set(u.id, u)
    },
    async loadMore() {
      if (!this.active) return;
      const olderMessages = await warpnetService.getDirectMessages(
          {chatId: this.active.id, cursorReset: false},
      )
      const known = new Set(this.messages.map((m) => m && m.id));
      const fresh = olderMessages.filter((m) => m && m.id && !known.has(m.id));
      await Promise.all(fresh.map(async (msg) => {
        if (msg.image_key) {
          msg.image = await warpnetService.getImage({userId: msg.sender_id, key: msg.image_key});
        }
      }));
      this.messages = [...fresh, ...this.messages];
      this.messages.sort((a, b) => new Date(a.created_at) - new Date(b.created_at));
    },
    isNearBottom() {
      const el = this.$refs.messagesScroll;
      if (!el) return true;
      return el.scrollHeight - el.scrollTop - el.clientHeight < 150;
    },
    // Poll-driven live updates: the node bridge is strictly
    // request/response (no server push), so — like the 2s notification
    // poll in service.js — the chat list and the active chat are
    // re-fetched on an interval and new items merged in by id. The
    // pagination cursors are saved and restored around the page-1
    // fetches so scroll-back pagination isn't reset by the poll.
    async refreshData() {
      if (this.refreshInFlight || this.loading) return;
      this.refreshInFlight = true;
      try {
        const savedChatsCursor = warpnetService.getCursor('chats');
        const chats = await warpnetService.getChats(true);
        warpnetService.setCursor('chats', savedChatsCursor);
        for (const chat of chats) {
          if (!this.usersMap.has(chat.owner_id)) await this.loadChatUser(chat.owner_id);
          if (!this.usersMap.has(chat.other_user_id)) await this.loadChatUser(chat.other_user_id);
          if (chat.owner_id !== this.ownerProfile.user_id) {
            [chat.owner_id, chat.other_user_id] = [chat.other_user_id, chat.owner_id];
          }
        }
        if (chats.length > 0) {
          const freshIds = new Set(chats.map((c) => c.id));
          this.chats = [...chats, ...this.chats.filter((c) => !freshIds.has(c.id))];
        }

        const activeId = this.active?.id;
        if (!activeId) return;
        const savedMessagesCursor = warpnetService.getCursor('messages');
        const page = await warpnetService.getDirectMessages(
            {chatId: activeId, cursorReset: true},
        );
        warpnetService.setCursor('messages', savedMessagesCursor);
        // The user may have switched chats while the fetch was in flight.
        if (this.active?.id !== activeId) return;
        const known = new Set(this.messages.map((m) => m && m.id));
        const fresh = page.filter((m) => m && m.id && !known.has(m.id));
        if (fresh.length === 0) return;
        await Promise.all(fresh.map(async (msg) => {
          if (msg.image_key) {
            msg.image = await warpnetService.getImage({userId: msg.sender_id, key: msg.image_key});
          }
        }));
        if (this.active?.id !== activeId) return;
        const wasNearBottom = this.isNearBottom();
        this.messages = [...this.messages, ...fresh]
            .sort((a, b) => new Date(a.created_at) - new Date(b.created_at));
        if (wasNearBottom) {
          this.scrollToEnd();
        }
      } catch (err) {
        console.error('Failed to refresh chats:', err);
      } finally {
        this.refreshInFlight = false;
      }
    },
  },
  async created() {
    console.log("loading component:", this.$options.name);
    console.log("messages: route chat id:", this.$route.params.chatId)

    this.ownerProfile = warpnetService.getOwnerProfile()
    // Started before the initial load (refreshData no-ops while loading)
    // so a user with no chats yet still picks up an incoming chat live.
    this.refreshTimer = setInterval(() => this.refreshData(), 3000);
    await this.loadChatUser(this.ownerProfile.user_id)

    const chats = await warpnetService.getChats(true)
    if (chats.length === 0) {
      console.warn("messages: chats not found")
      this.loading = false;
      return;
    }

    let activeChat = null
    for (const chat of chats) {
      await this.loadChatUser(chat.owner_id)
      await this.loadChatUser(chat.other_user_id)

      if (chat.id === this.$route.params.chatId) {
        console.log('ACTIVE CHAT', JSON.stringify(chat))
        console.log('ACTIVE CHAT owner', chat.owner_id, "other", chat.other_user_id)
        activeChat = chat
      }
      if (chat.owner_id !== this.ownerProfile.user_id) {
        [chat.owner_id, chat.other_user_id] = [chat.other_user_id, chat.owner_id];
      }
    }

    this.chats = chats;
    await this.selectChat(activeChat);
    this.loading = false;
  },
  beforeUnmount() {
    if (this.refreshTimer) {
      clearInterval(this.refreshTimer);
      this.refreshTimer = null;
    }
  },
};
</script>
