<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided "as is" without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div id="app" class="flex container h-screen w-full">
      <SideNav />

      <div class="w-full h-full overflow-y-scroll no-scrollbar">
        <div class="px-5 py-3 border-lighter flex items-center justify-between">
          <button
              @click="gotoHome()"
              class="rounded-full md:pr-2 focus:outline-none hover:bg-lightblue"
          >
            <i class="fas fa-arrow-left text-blue"></i>
          </button>
          <h1 class="text-xl font-bold">Notifications</h1>
          <div ref="settingsMenu" class="relative">
            <button
              type="button"
              @click="settingsOpen = !settingsOpen"
              class="rounded-full w-9 h-9 flex items-center justify-center hover:bg-lightblue"
              aria-label="Notification settings"
              :aria-expanded="settingsOpen"
            >
              <i class="fas fa-cog text-xl text-blue" aria-hidden="true"></i>
            </button>
            <div
              v-if="settingsOpen"
              class="absolute right-0 mt-2 w-48 bg-white dark:bg-darktheme-card mastodon:bg-mastodon-card rounded-md shadow-lg py-1 z-10"
            >
              <button
                type="button"
                @click="onMarkAllRead"
                class="block w-full text-left px-4 py-2 text-sm hover:bg-gray-100 flat-btn"
              >Mark all as read</button>
            </div>
          </div>
        </div>

        <div class="flex flex-col">
          <div class="flex flex-row justify-evenly text-sm">
            <button
              @click="submit('All')"
              class="w-full text-dark font-bold border-b-2 p-1 md:px-3 md:py-4 hover:bg-lightblue sm:truncate"
              :class="`${this.mode === 'All' ? 'border-blue' : ''}`"
            >
              All
            </button>
            <button
              @click="submit('Mentions')"
              class="w-full text-dark font-bold border-b-2 p-1 md:px-3 md:py-4 hover:bg-lightblue sm:truncate"
              :class="`${this.mode === 'Mentions' ? 'border-blue' : ''}`"
            >
              Mentions
            </button>
            <button
              v-if="locked"
              @click="submit('Requests')"
              class="w-full text-dark font-bold border-b-2 p-1 md:px-3 md:py-4 hover:bg-lightblue sm:truncate"
              :class="`${this.mode === 'Requests' ? 'border-blue' : ''}`"
            >
              Requests
            </button>
          </div>
        </div>

        <!-- notifications -->
        <Loader :loading="loading" />
        <div v-if="mode === 'All'">
          <div
            v-if="!loading && notifications.length === 0"
            class="flex flex-col items-center justify-center w-full pt-10"
          >
            <div class="w-1/2 flex flex-col items-center justify-center">
              <p class="font-bold text-lg">No notifications yet</p>
              <p class="text-sm text-dark">Wait until some get shown here.</p>
            </div>
          </div>

          <div v-for="notification in notifications" :key="notification.id">
            <button
              type="button"
              class="w-full text-left p-2 pt-1 pb-1 md:p-4 md:pt-2 md:pb-2 border-b hover:bg-lightest flex flat-btn"
              :class="notification.is_read ? '' : 'bg-lightblue'"
              @click="openNotification(notification)"
            >
              <div class="w-full">
                <div class="flex flex-row mr-2 md:mr-4 pt-1 text-2xl">
                  <i
                    v-if="notification.type === 'reply'"
                    class="pt-1 fas fa-comment text-blue"
                  ></i>
                  <i
                    v-if="notification.type === 'like'"
                    class="pt-1 fas fa-heart text-red-600"
                  ></i>
                  <i
                    v-if="notification.type === 'retweet'"
                    class="pt-1 fas fa-retweet text-green-500"
                  ></i>
                  <i
                    v-if="notification.type === 'follow'"
                    class="pt-1 fas fa-user-plus text-blue"
                  ></i>
                  <i
                    v-if="notification.type === 'moderation'"
                    class="pt-1 fas fa-shield-alt text-blue"
                  ></i>
                  <i
                    v-if="notification.type === 'message'"
                    class="pt-1 fas fa-envelope text-blue"
                  ></i>

                  <img
                    :src="avatarFor(notification)"
                    class="h-8 w-8 ml-2 rounded-full flex-none"
                  />
                </div>
                <div class="flex items-center w-full">
                  <p class="font-sm">{{ notification.text }}</p>
                  <p class="text-sm text-dark ml-auto">
                    {{ $filters.timeago(notification.created_at) }}
                  </p>
                </div>
              </div>
            </button>
          </div>
        </div>
        <div v-if="mode === 'Mentions'">
          <div
            v-if="mentions.length === 0"
            class="flex flex-col items-center justify-center w-full pt-10"
          >
            <div class="w-1/2 flex flex-col items-center justify-center">
              <p class="font-bold text-lg">No mentions yet</p>
              <p class="text-sm text-dark">Wait until some get shown here.</p>
            </div>
          </div>
          <div v-for="notification in mentions" :key="notification.id">
            <button
              type="button"
              class="w-full text-left p-2 pt-1 pb-1 md:p-4 md:pt-2 md:pb-2 border-b hover:bg-lightest flex flat-btn"
              :class="notification.is_read ? '' : 'bg-lightblue'"
              @click="openNotification(notification)"
            >
              <div class="w-full">
                <div class="flex flex-row mr-2 md:mr-4 pt-1 text-2xl">
                  <img
                    :src="avatarFor(notification)"
                    class="h-8 w-8 ml-2 rounded-full flex-none"
                  />
                </div>
                <div class="flex items-center w-full">
                  <p class="font-sm">{{ notification.text }}</p>
                  <p class="text-sm text-dark ml-auto">
                    {{ $filters.timeago(notification.created_at) }}
                  </p>
                </div>
              </div>
            </button>
          </div>
        </div>
        <div v-if="mode === 'Requests' && locked">
          <div
            v-if="followRequests.length === 0"
            class="flex flex-col items-center justify-center pt-10 px-5"
          >
            <p class="font-bold text-lg">No follow requests</p>
            <p class="text-sm text-dark">When your account is locked, requests to follow you appear here.</p>
          </div>
          <div
            v-for="r in followRequests"
            :key="r.id"
            class="px-5 py-3 border-b border-lighter flex items-center"
          >
            <img :src="r.avatar || '/default_profile.png'" class="h-10 w-10 rounded-full object-cover" alt="" />
            <button
              @click="$router.push({ name: 'Profile', params: { id: r.id } })"
              class="ml-3 text-left flat-btn"
            >
              <p class="font-bold">{{ r.username || r.id }}</p>
              <p class="text-dark text-sm">@{{ r.id }}</p>
            </button>
            <div class="ml-auto flex gap-2">
              <button
                @click="authorizeRequest(r.id)"
                class="text-white bg-blue font-bold px-3 py-1 rounded-full hover:bg-darkblue"
              >Authorize</button>
              <button
                @click="rejectRequest(r.id)"
                class="text-red-600 border border-red-600 font-bold px-3 py-1 rounded-full hover:bg-red-50"
              >Reject</button>
            </div>
          </div>
        </div>
      </div>

      <!-- default right bar -->
      <DefaultRightBar :profile="ownerProfile" />

      <NotificationOverlay
        :show="overlayOpen"
        :notificationId="overlayNotificationId"
        @close="overlayOpen = false"
      />
  </div>
</template>

<script>
import {defineAsyncComponent} from "vue";
import SideNav from "../components/SideNav.vue";
import DefaultRightBar from "../components/DefaultRightBar.vue";
import {warpnetService} from "@/service/service";
import {toast} from "@/lib/toast";

export default {
  name: "Notifications",
  components: {
    SideNav,
    DefaultRightBar,
    Loader: defineAsyncComponent(() => import('@/components/Loader.vue')),
    NotificationOverlay: defineAsyncComponent(() => import('@/components/NotificationOverlay.vue')),
  },
  data() {
    return {
      loading: false,
      notifications: [],
      followRequests: [],
      locked: false,
      ownerProfile: {},
      mode: this.$route.query.m || "All",
      overlayOpen: false,
      overlayNotificationId: '',
      settingsOpen: false,
      actorAvatars: {},
    };
  },
  computed: {
    mentions() {
      // Warpnet emits "reply" (never "mention") when someone responds to you,
      // so the Mentions tab keys off replies too.
      return this.notifications.filter(n => n.type === 'mention' || n.type === 'reply');
    },
  },
  methods: {
    gotoHome() {
      if (window.history.length > 1) {
        this.$router.back();
      } else {
        this.$router.push({ name: "Home" });
      }
    },
    submit(m = this.mode) {
      this.mode = m;
      this.$router.replace({
        name: "Notifications",
        query: { m: m, hash: Date.now() },
      });
    },
    openNotification(notification) {
      // Mark this one read so the badge decrements even if the click
      // ends up not navigating (overlay / unknown type).
      this.markRead(notification);
      // If the notification points at a tweet, navigate directly.
      // Otherwise show the lightweight overlay (follow / unknown types).
      if (notification?.tweet_id) {
        this.$router.push({
          name: 'Tweet',
          params: { id: notification.tweet_id },
          query: { u: notification.user_id || '' },
        });
        return;
      }
      this.overlayNotificationId = notification?.id || '';
      this.overlayOpen = true;
    },
    async markRead(notification) {
      if (!notification || !notification.id || notification.is_read) return;
      try {
        await warpnetService.markNotificationRead(notification.id);
        notification.is_read = true;
      } catch (err) {
        console.error('Failed to mark notification read:', err);
      }
    },
    async markAllRead() {
      // One node-side request covers every page — the per-item loop this
      // replaces only marked the first page, so unread items beyond it
      // kept the badge alive forever.
      try {
        await warpnetService.markAllNotificationsRead();
        this.notifications.forEach(n => { if (n) n.is_read = true; });
      } catch (err) {
        console.error('Failed to mark all notifications read:', err);
      }
    },
    async onMarkAllRead() {
      this.settingsOpen = false;
      await this.markAllRead();
    },
    avatarFor(n) {
      return (n && n.actor_id && this.actorAvatars[n.actor_id]) || '/default_profile.png';
    },
    async hydrateAvatars(list) {
      const ids = [...new Set((list || [])
        .map(n => n && n.actor_id)
        .filter(id => id && !this.actorAvatars[id]))];
      await Promise.all(ids.map(async (id) => {
        try {
          const p = await warpnetService.getProfile(id);
          if (p && p.avatar_key) {
            const img = await warpnetService.getImage({ userId: id, key: p.avatar_key });
            if (img) this.actorAvatars[id] = img;
          }
        } catch (e) {}
      }));
    },
    async hydrateRequests(ids) {
      return Promise.all(
        (ids || []).map(async (id) => {
          try {
            const p = await warpnetService.getProfile(id);
            if (!p) return { id };
            if (p.avatar_key) {
              p.avatar = await warpnetService.getImage({ userId: id, key: p.avatar_key });
            }
            return p;
          } catch (e) { return { id }; }
        })
      );
    },
    async loadFollowRequests() {
      try {
        const resp = await warpnetService.getFollowRequests();
        const ids = resp?.follower_ids || resp?.ids || [];
        this.followRequests = await this.hydrateRequests(ids);
      } catch (err) {
        console.error('Failed to load follow requests:', err);
      }
    },
    async authorizeRequest(id) {
      try {
        await warpnetService.authorizeFollowRequest(id);
        this.followRequests = this.followRequests.filter(r => r.id !== id);
      } catch (err) {
        console.error('Failed to authorize', err);
        toast.error(err?.message || "Couldn't authorize the request. Please try again.");
      }
    },
    async rejectRequest(id) {
      try {
        await warpnetService.rejectFollowRequest(id);
        this.followRequests = this.followRequests.filter(r => r.id !== id);
      } catch (err) {
        console.error('Failed to reject', err);
        toast.error(err?.message || "Couldn't reject the request. Please try again.");
      }
    },
  },
  async created() {
    console.log("loading component:", this.$options.name);
    try {
      this.loading = true;
      this.ownerProfile = warpnetService.getOwnerProfile();
      // The owner stub in stateMap doesn't carry the `locked` flag, so fetch
      // the full profile to decide whether to show the Requests tab.
      try {
        const me = await warpnetService.getProfile(this.ownerProfile.user_id);
        this.locked = Boolean(me && me.locked);
      } catch (err) {
        console.warn('Failed to read own locked state:', err);
      }
      const resp = await warpnetService.getNotifications(true);
      if (resp && resp.notifications) {
        this.notifications = resp.notifications.filter((n) => n && n.type !== 'message');
        this.hydrateAvatars(this.notifications);
      }
      // Don't bulk-mark-read just for opening the view — that erased the
      // unread state before the user looked at anything. Items are marked
      // read when opened (openNotification), or all at once via the
      // "Mark all as read" menu.
      if (this.locked) {
        await this.loadFollowRequests();
      }
    } catch (err) {
      console.error('Failed to load notifications:', err);
    } finally {
      this.loading = false;
    }

    // Ride the service's 2s notification poll so new notifications show
    // up while the page is open, instead of only after a manual reload.
    // Items already marked read locally stay read even if a poll lands
    // before the mark-read request settles on the node.
    this._unsubscribeLive = warpnetService.subscribeNotifications((resp) => {
      if (this.loading) return;
      const incoming = ((resp && resp.notifications) || []).filter((n) => n && n.type !== 'message');
      if (incoming.length === 0) return;
      const readIds = new Set(
        this.notifications.filter((n) => n && n.is_read).map((n) => n.id)
      );
      this.notifications = incoming.map((n) =>
        n && readIds.has(n.id) ? { ...n, is_read: true } : n
      );
      this.hydrateAvatars(this.notifications);
    });
  },
  mounted() {
    this._onDocClick = (e) => {
      if (!this.settingsOpen) return;
      const menu = this.$refs.settingsMenu;
      if (menu && !menu.contains(e.target)) {
        this.settingsOpen = false;
      }
    };
    this._onDocKeyup = (e) => {
      if (e.key === "Escape" && this.settingsOpen) {
        this.settingsOpen = false;
      }
    };
    document.addEventListener("click", this._onDocClick);
    window.addEventListener("keyup", this._onDocKeyup);
  },
  beforeUnmount() {
    if (this._unsubscribeLive) {
      this._unsubscribeLive();
      this._unsubscribeLive = null;
    }
    if (this._onDocClick) {
      document.removeEventListener("click", this._onDocClick);
      this._onDocClick = null;
    }
    if (this._onDocKeyup) {
      window.removeEventListener("keyup", this._onDocKeyup);
      this._onDocKeyup = null;
    }
  },
};
</script>
