<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div class="flex w-full h-screen flex-col-reverse md:flex-row" v-escape="esc">
    <!-- left side -->
    <div class="flex w-full md:w-1/2 h-full bg-blue p-5 md:p-0">
      <div class="flex items-center justify-center w-full h-full">
        <div class="flex flex-col">
          <div class="flex items-center">
            <i class="fas fa-search text-white text-2xl mr-5"></i>
            <p class="text-white font-bold text-xl">Follow your interests.</p>
          </div>
          <div class="flex items-center mt-10">
            <i class="fas fa-user-friends text-white text-2xl mr-4"></i>
            <p class="text-white font-bold text-xl">
              Hear what people are talking about.
            </p>
          </div>
          <div class="flex items-center mt-10">
            <i class="fas fa-comment text-white text-2xl mr-5"></i>
            <p class="text-white font-bold text-xl">Join the conversation.</p>
          </div>
        </div>
      </div>
    </div>

    <!-- right side -->
    <div class="flex w-full md:w-1/2 h-full overflow-y-auto">
      <div class="flex w-full min-h-full py-8">
        <div class="w-full md:w-1/2 flex flex-col font-bold p-5 md:p-0 m-auto">
          <p class="text-2xl md:text-3xl mb-3">
            Dive deep into the Warp and see what happens...
          </p>
          <p class="text-sm font-normal text-dark mb-6">
            A decentralized, peer-to-peer network. Your account lives locally on
            this device — no central server, no password recovery.
          </p>
          <p>Join Warpnet today.</p>
          <button v-if="isFirstRun === true"
            @click.prevent="setSignUpStep('step1')"
            class="rounded-full bg-blue font-bold text-lg text-white mt-4 p-3 hover:bg-darkblue"
          >
            Sign up
          </button>
          <LogInComponent v-else-if="isFirstRun === false"></LogInComponent>
          <!-- first-run probe failed (node unreachable): offer a retry rather
               than silently showing login with no sign-up path -->
          <div v-else-if="firstRunError" class="mt-4">
            <p class="text-red-600 text-sm font-medium mb-2" role="alert">
              Couldn't reach your Warpnet node. Make sure it's running.
            </p>
            <button
              @click.prevent="resolveFirstRun"
              class="rounded-full bg-blue font-bold text-white p-3 px-6 hover:bg-darkblue"
            >Try again</button>
          </div>
          <!-- still resolving first-run state -->
          <div v-else class="mt-4 text-dark">
            <i class="fas fa-circle-notch fa-spin mr-2" aria-hidden="true"></i>Loading…
          </div>
        </div>
      </div>
    </div>

    <!-- sign up modal -->
    <div
      v-if="showModal !== ''"
      class="fixed w-full h-full top-0 left-0 flex items-center justify-center"
    >
      <div
        class="absolute w-full h-full bg-gray-900 opacity-50"
        @click.prevent="setSignUpStep('')"
      ></div>

      <div
        class="modal-main bg-white w-11/12 max-w-md mx-auto rounded-lg z-50 overflow-y-auto max-h-full"
        role="dialog"
        aria-modal="true"
        aria-label="Create your account"
      >
        <div v-if="showModal === 'step1'">
          <div class="pl-1 pr-4 py-1 h-12">
            <button
              @click="setSignUpStep('step2')"
              class="rounded-full bg-blue font-bold text-white mt-2 p-1 pl-3 pr-3 relative right-0 float-right hover:bg-darkblue"
              :class="!username ? 'opacity-50 cursor-not-allowed' : ''"
              :disabled="!username"
            >
              Next
            </button>
            <i
              class="flex justify-center fab text-blue text-2xl mt-2 mb-8"
            ></i>
          </div>
          <div class="pt-5 px-8">
            <div class="flex justify-between items-center pb-8">
              <p class="text-2xl font-bold">Create your account</p>
            </div>
            <p class="text-sm text-dark mb-4">Step 1 of 4</p>
            <div class="w-full bg-lightblue border-b-2 border-dark mb-8 p-2">
              <label for="signup-username" class="text-dark">Username</label>
              <input
                id="signup-username"
                v-model="username"
                class="w-full bg-lightblue text-lg"
                type="text"
                autocomplete="username"
                @keydown.enter="setSignUpStep('step2')"
              />
            </div>
          </div>
        </div>

        <div v-if="showModal === 'step2'">
          <div class="pl-1 pr-4 py-1 h-12">
            <button
              @click="setSignUpStep('step1')"
              class="absolute rounded-full p-2 pl-3 hover:bg-lightblue"
              aria-label="Back"
            >
              <i class="fas fa-arrow-left text-blue"></i>
            </button>
            <button
              @click="setSignUpStep('step3')"
              :disabled="!(userResponsibility && localStorageLoss && futureAds)"
              class="rounded-full bg-blue font-bold text-white mt-2 p-1 pl-3 pr-3 relative right-0 float-right hover:bg-darkblue"
              :class="!(userResponsibility && localStorageLoss && futureAds) ? 'opacity-50 cursor-not-allowed' : ''"
            >
              Next
            </button>
            <i
              class="flex justify-center fab text-blue text-2xl mt-2 mb-8"
            ></i>
          </div>
          <div class="pt-5 px-8">
            <div class="flex justify-between items-center pb-4">
              <p class="text-2xl font-bold">Important information</p>
            </div>
            <p class="text-sm text-dark mb-1">Step 2 of 4</p>
            <p class="text-sm text-dark mb-4">Please acknowledge all three to continue.</p>

            <div class="mt-5 mb-8">
              <p class="font-bold text-xl mb-1">User Responsibility</p>
              <label class="flex justify-between items-top cursor-pointer">
                <span>
                  I acknowledge that I am solely responsible for the content I upload to WarpNet.
                </span>
                <input class="mt-2 ml-4 mr-4" type="checkbox" v-model="userResponsibility" />
              </label>
            </div>

            <div class="mt-5 mb-8">
              <p class="font-bold text-xl mb-1 text-red-700">Local Storage Disclaimer</p>
              <label class="flex justify-between items-top cursor-pointer">
                <span>
                  I understand that all my data is stored locally on my device, and if I lose access to this device,
                  my WarpNet account will be permanently lost.
                </span>
                <input class="mt-2 ml-4 mr-4" type="checkbox" v-model="localStorageLoss" />
              </label>
            </div>

            <div class="mt-5 mb-5">
              <p class="font-bold text-xl mb-1">Future Advertising</p>
              <label class="flex justify-between items-top cursor-pointer">
                <span>
                  I understand that WarpNet may introduce sponsored content or advertisements in the future.
                </span>
                <input class="mt-2 ml-4 mr-4" type="checkbox" v-model="futureAds" />
              </label>
            </div>
          </div>
        </div>

        <div v-if="showModal === 'step3'">
          <div class="pl-1 pr-4 py-1 h-12">
            <button
              @click="setSignUpStep('step2')"
              class="absolute rounded-full p-2 pl-3 hover:bg-lightblue"
              aria-label="Back"
            >
              <i class="fas fa-arrow-left text-blue"></i>
            </button>
            <button
              @click="setSignUpStep('step4')"
              class="rounded-full bg-blue font-bold text-white mt-2 p-1 pl-3 pr-3 relative right-0 float-right hover:bg-darkblue"
              :class="!(isPasswordPairValid && isPasswordStrong) ? 'opacity-50 cursor-not-allowed' : ''"
              :disabled="!(isPasswordPairValid && isPasswordStrong)"
            >
              Next
            </button>
            <i
              class="flex justify-center fab text-blue text-2xl mt-2 mb-8"
            ></i>
          </div>
          <div class="pt-5 px-8">
            <div class="flex justify-between items-center pb-2">
              <p class="text-2xl font-bold">You'll need a password</p>
            </div>
            <p class="text-sm text-dark mb-4">Step 3 of 4</p>

            <div class="w-full bg-lightblue border-b-2 border-dark p-2">
              <label for="signup-password" class="leading-tight text-dark">Password</label>
              <input
                id="signup-password"
                v-model="password"
                class="w-full bg-lightblue text-lg"
                :type="`${revealPassword ? 'text' : 'password'}`"
                autocomplete="new-password"
              />
            </div>

            <div class="w-full bg-lightblue border-b-2 border-dark p-2 mt-4">
              <label for="signup-password-confirm" class="leading-tight text-dark">Confirm password</label>
              <input
                id="signup-password-confirm"
                v-model="passwordConfirm"
                class="w-full bg-lightblue text-lg"
                :type="`${revealPassword ? 'text' : 'password'}`"
                autocomplete="new-password"
              />
            </div>

            <p
              v-if="password && passwordConfirm && password !== passwordConfirm"
              class="mt-2 text-red-600 text-sm font-medium"
              role="alert"
            >
              Passwords do not match.
            </p>

            <PasswordRules :password="password" />

            <button
              type="button"
              @click="revealPassword = !revealPassword"
              class="text-blue pl-2 mt-2"
              :aria-pressed="revealPassword"
            >
              <i :class="revealPassword ? 'fas fa-eye-slash' : 'fas fa-eye'" aria-hidden="true"></i>
              {{ revealPassword ? "Hide password" : "Reveal password" }}
            </button>
          </div>
        </div>

        <div v-if="showModal === 'step4'">
          <div class="pl-1 pr-4 py-1 h-12">
            <button
              @click="setSignUpStep('step3')"
              class="absolute rounded-full p-2 pl-3 hover:bg-lightblue"
              aria-label="Back"
            >
              <i class="fas fa-arrow-left text-blue"></i>
            </button>
            <p class="flex items-start ml-12 p-2 text-sm text-dark">
              Step 4 of 4
            </p>
          </div>
          <div class="pt-5 px-8">
            <div class="flex justify-between items-center pb-8">
              <p class="text-2xl font-bold">Create your account</p>
            </div>

            <p>
              By signing up, you agree to our
              <a href="https://github.com/Warp-net/docs/blob/main/legal/T%26C.md" target="_blank" rel="noopener" class="text-blue">Terms</a>
              and
              <a href="https://github.com/Warp-net/docs/blob/main/legal/PRIVACY-POLICY.md" target="_blank" rel="noopener" class="text-blue">Privacy Policy</a>.
            </p>
            <button
              v-if="!isLoading"
              @click="signMeUp"
              class="w-full rounded-full mt-4 py-3 bg-blue text-white font-bold hover:bg-darkblue"
            >
              Sign up
            </button>
            <div v-else class="w-full rounded-full mt-4 py-3">
              <ProgressBar/>
            </div>
            <p v-if="signUpError" class="mt-3 text-red-600 text-sm text-center font-medium" role="alert">
              {{ signUpError }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import {defineAsyncComponent} from "vue";
import {warpnetService} from "@/service/service";
import {parseDeepLink} from "@/lib/deeplink";
import {isPasswordStrong} from "@/lib/password";
export default {
  name: "Root",
  components: {
    ProgressBar: defineAsyncComponent(() => import('@/components/ProgressBar.vue')),
    LogInComponent: defineAsyncComponent(() => import('@/components/LogInComponent.vue')),
    PasswordRules: defineAsyncComponent(() => import('@/components/PasswordRules.vue')),
  },
  data() {
    return {
      username: "",
      password: "",
      passwordConfirm: "",
      revealPassword: false,
      isFirstRun: null,
      isLoading: false,
      showModal: "",

      userResponsibility: false,
      futureAds: false,
      localStorageLoss: false,
      signUpError: "",
      firstRunError: false,
    };
  },
  computed: {
    isPasswordPairValid() {
      return (
        this.password.length > 0 &&
        this.passwordConfirm.length > 0 &&
        this.password === this.passwordConfirm
      );
    },
    // Mirror the backend password policy so step 3 can't advance a password
    // the node will later reject on the final step.
    isPasswordStrong() {
      return isPasswordStrong(this.password);
    },
  },
  async mounted() {
    await this.resolveFirstRun();
  },
  methods: {
    async resolveFirstRun() {
      this.firstRunError = false;
      this.isFirstRun = null;
      try {
        this.isFirstRun = await warpnetService.isFirstRun();
      } catch (err) {
        // Don't silently fall back to the login screen — a brand-new user
        // would then have no path to sign up. Surface a retry instead.
        console.error("failed to determine first-run state:", err);
        this.firstRunError = true;
      }
      console.log("Is first run:", this.isFirstRun);
    },
    async signMeUp() {
      try {
        this.isLoading = true;
        this.signUpError = "";
        // Capture firstRun BEFORE signInUser: by the time the node has
        // a session, IsFirstRun() flips to false on the next call.
        const wasFirstRun = this.isFirstRun === true;
        await warpnetService.signInUser({
          username: this.username,
          password: this.password,
        });
        if (wasFirstRun) {
          // SideNav picks this up on mount and opens the pairing
          // explainer so a brand-new user gets the QR + visual guide
          // immediately, without having to discover the dropdown.
          // Guarded so privacy modes / disabled storage can't throw
          // and abort the routing to Home — onboarding is a nice-to-have,
          // signup completion is not.
          try {
            if (typeof sessionStorage !== "undefined") {
              sessionStorage.setItem("warpnet:show-pairing-onboarding", "1");
            }
          } catch (e) {
            console.warn("sessionStorage write failed, skipping pairing onboarding:", e);
          }
        }
        this.setStep("");
        // No Vue route by id — route via Search (same as SearchBar).
        const deepLink = parseDeepLink(await warpnetService.consumePendingDeepLink());
        if (deepLink && deepLink.kind === "user") {
          this.$router.push({ name: "Search", query: { q: deepLink.id } });
          return;
        }
        this.$router.push({ name: "Home" });
      } catch (error) {
        console.error("error signing up:", error);
        this.signUpError = error?.message || "Sign-up failed. Please try again.";
      } finally {
        this.isLoading = false;
      }
    },
    async setStep(step) {
      this.signUpError = "";
      this.showModal = step || ""
    },
    setSignUpStep(step) {
      switch (step) {
        case "step2":
          if (!this.username) {
            return;
          }
          break;
        case "step4":
          if (!this.isPasswordPairValid || !this.isPasswordStrong) {
            return;
          }
          break;
      }
      this.setStep(step);
    },
    esc() {
      this.setStep("");
      this.isLoading = false;
    },
  },
};
</script>
