<!-- License generated by licensor(https://github.com/Marvin9/licensor).

Warpnet - Decentralized Social Network
Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
<github.com.mecdy@passmail.net>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
-->
<template>
  <div id="app" class="flex container h-screen w-full">
    <div class="flex container h-screen w-full">
      <SideNav />

      <div class="w-full h-full overflow-y-scroll no-scrollbar">
        <div class="px-5 pt-3 flex items-center">
          <button
            @click="goHome()"
            class="rounded-full p-3 px-4 focus:outline-none hover:bg-lightblue"
          >
            <i class="fas fa-arrow-left text-blue"></i>
          </button>
          <div class="lg:block ml-4">
            <h1 class="text-xl font-bold">Who to follow</h1>
          </div>
        </div>

        <Loader :loading="loading" />

        <div v-if="warpnetProfiles.length > 0">
          <h2 class="px-5 pt-3 text-left text-lg font-bold">
            <img src="@/assets/logo-transparent.png" alt="Warpnet" class="w-5 h-5 inline-block object-contain" />
          </h2>
          <Users :users="warpnetProfiles" :loading="loading" />
        </div>
        <div v-if="mastodonProfiles.length > 0">
          <h2 class="px-5 pt-3 text-left text-lg font-bold">
            <i class="fab fa-mastodon text-[color:var(--gd-trim)]" role="img" aria-label="Mastodon"></i>
          </h2>
          <Users :users="mastodonProfiles" :loading="loading" />
        </div>
        <div v-if="!loading && profiles.length === 0" class="flex justify-center py-6">
          <span>No results</span>
        </div>

        <button
          v-if="hasMore && !loading"
          :disabled="loadingMore"
          @click="loadMore()"
          class="p-3 w-full hover:bg-lighter text-center text-blue border-t border-lighter"
        >
          Show More
        </button>
      </div>

      <div
        class="hidden md:block w-1/3 z-0 h-full border-l border-lighter px-6 py-2 overflow-y-scroll no-scrollbar relative"
      >
        <SearchBar />
      </div>
    </div>
  </div>
</template>

<script>
import SideNav from "../components/SideNav.vue";
import SearchBar from "../components/SearchBar.vue";
import Users from "../components/Users.vue";
import Loader from "../components/Loader.vue";
import {warpnetService} from "@/service/service";
import {isMastodonUser} from "@/lib/network";

export default {
  name: "WhoToFollow",
  components: {
    SideNav,
    SearchBar,
    Users,
    Loader,
  },
  data() {
    return {
      loading: true,
      loadingMore: false,
      profiles: [],
      hasMore: true,
    };
  },
  computed: {
    warpnetProfiles() {
      return this.profiles.filter((p) => !isMastodonUser(p));
    },
    mastodonProfiles() {
      return this.profiles.filter((p) => isMastodonUser(p));
    },
  },
  methods: {
    goHome() {
      this.$router.push("/");
    },
    async loadMore() {
      if (!this.hasMore || this.loadingMore) {
        return;
      }
      this.loadingMore = true;
      try {
        const users = await warpnetService.getWhoToFollow(false);
        if (!users || users.length === 0) {
          this.hasMore = false;
          return;
        }
        this.profiles.push(...users);
      } catch (err) {
        console.error("loading component:", this.$options.name, err);
      } finally {
        this.loadingMore = false;
      }
    },
  },
  async created() {
    console.log("loading component:", this.$options.name);
    try {
      const users = await warpnetService.getWhoToFollow(true);
      this.profiles = users || [];
      if (this.profiles.length === 0) {
        this.hasMore = false;
      }
    } catch (err) {
      console.error("loading component:", this.$options.name, err);
    } finally {
      this.loading = false;
    }
  },
};
</script>
