/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

import {
    PRIVATE_DELETE_CHAT,
    PRIVATE_DELETE_TWEET,
    PRIVATE_GET_CHAT,
    PRIVATE_GET_CHATS,
    PRIVATE_GET_MESSAGE,
    PRIVATE_GET_MESSAGES,
    PRIVATE_GET_NOTIFICATIONS,
    PRIVATE_GET_STATS,
    PRIVATE_GET_TIMELINE,
    PRIVATE_POST_LOGIN,
    PRIVATE_POST_TWEET,
    PRIVATE_POST_UPLOAD_IMAGE,
    PRIVATE_POST_UPLOAD_VIDEO,
    PRIVATE_POST_USER,
    PRIVATE_DELETE_MESSAGE,
    PUBLIC_GET_FOLLOWINGS,
    PUBLIC_GET_FOLLOWERS,
    PUBLIC_GET_IMAGE,
    PUBLIC_GET_VIDEO,
    PUBLIC_GET_TWEET,
    PUBLIC_GET_TWEET_STATS,
    PUBLIC_GET_TWEETS,
    PUBLIC_GET_USER,
    PUBLIC_GET_USERS,
    PUBLIC_GET_WHOTOFOLLOW,
    PUBLIC_POST_CHAT,
    PUBLIC_POST_FOLLOW,
    PUBLIC_POST_REACT,
    PUBLIC_POST_MESSAGE,
    PUBLIC_POST_RETWEET,
    PUBLIC_POST_UNFOLLOW,
    PUBLIC_POST_UNREACT,
    PUBLIC_POST_UNRETWEET,
    PUBLIC_POST_VIEW,
    PUBLIC_POST_POLL_VOTE,
    PUBLIC_GET_POLL
} from "@/service/service";
import {generateUUID} from "@/lib/uuid";
import {DEFAULT_REACTION} from "@/lib/emoji";

const mockMap = new Map();

if (process.env.NODE_ENV === 'development') {
    console.warn("⚠️ Running in standalone mode — mocking window.go ⚠️");

    window.go = {
        main: {
            App: {
                Call: (arg1) => {
                    const body = generateResponse(arg1);
                    return Promise.resolve({body:body});
                },
                IsFirstRun: () => Promise.resolve(true),
                SelectNetwork: () => Promise.resolve(),
                ConsumePendingDeepLink: () => Promise.resolve(""),
            }
        }
    };
}

function generateResponse(arg) {
    switch (arg.path) {
        case PRIVATE_POST_LOGIN:
            const uid = generateUUID()

            const u = newUser()
            u.node_id = arg.node_id
            u.username = arg.body.username || "Missing!"

            mockMap.set("user:"+u.id, u)
            return {
                token: generateUUID(),
                node_id: arg.node_id,
                user_id: uid,
                psk: "test",
                network: "testnet",
            }

        case PRIVATE_POST_TWEET:
            // A reply is a tweet with a parent: store it in the thread, bump
            // the parent's reply count, and keep it out of the timeline.
            if (arg.body.parent_id) {
                let reply = {
                    id : generateUUID(),
                    root_id : arg.body.root_id,
                    parent_id : arg.body.parent_id,
                    parent_user_id : arg.body.parent_user_id,
                    text : arg.body.text || "Missing!",
                    username : arg.body.username || "Missing!",
                    user_id : arg.body.user_id,
                    created_at : arg.body.created_at || Date.now().toString(),
                };
                mockMap.set("reply:"+reply.id, reply);
                let replyStats = mockMap.get("stats:"+arg.body.parent_id)
                if (replyStats) {
                    replyStats.replies_count++
                    mockMap.set("stats:"+arg.body.parent_id, replyStats)
                }
                return reply;
            }

            const tweetUid = generateUUID()
            let t = {
                id : tweetUid,
                root_id : tweetUid,
                user_id : arg.body.user_id || "",
                username : arg.body.username || "",
                text : arg.body.text || "",
                image_key : arg.body.image_key || "",
                image_keys : arg.body.image_keys || [],
                video_key : arg.body.video_key || undefined,
                poll : arg.body.poll || undefined,
                created_at : arg.body.created_at || Date.now().toString(),
                parent_id: null,
                retweeted_by: null,
                network: "warpnet",
                moderation: {is_ok: true},
            };

            mockMap.set("tweet:"+t.id, t)

            const timelineList = mockMap.get("timeline") || [];
            timelineList.push(t)
            mockMap.set("timeline", timelineList)

            let stats = newStats(t.id)
            mockMap.set("stats:"+t.id, stats)
            return t

        case PRIVATE_POST_USER:
            let editedUser = mockMap.get("user:"+arg.body.user_id);
            if (!editedUser) return {code:404, message:"User not found"};

            Object.assign(editedUser, arg);
            mockMap.set("user:"+arg.body.user_id, editedUser)
            return editedUser

        case PUBLIC_GET_USER:
            const gotUser = mockMap.get("user:"+arg.body.user_id)
            if (!gotUser) return {code:404, message:"User not found"};
            return gotUser;
        case PUBLIC_GET_TWEET_STATS:
            const st = mockMap.get("stats:"+arg.body.tweet_id)
            if (!st) return {code:404, message:"Stats not found"};
            return st;

        case PRIVATE_GET_STATS:
            return Object.fromEntries(mockMap);

        case PUBLIC_GET_TWEET:
            const gotTweet =  mockMap.get("tweet:"+arg.body.tweet_id)
            if (gotTweet) return gotTweet;
            // A reply carries its thread root_id; fall back to the thread store.
            const gotReplyTweet = mockMap.get("reply:"+arg.body.tweet_id)
            if (!gotReplyTweet) return {code:404, message:"Tweet not found"};
            return gotReplyTweet;

        case PRIVATE_GET_TIMELINE :
            const timelineTweets = mockMap.get("timeline") || [];
            return {cursor: "end", user_id: arg.body.user_id, tweets: timelineTweets}

        case PUBLIC_GET_TWEETS:
            // A root_id selects the thread branch: replies are tweets with a
            // parent, returned as a flat tweets list.
            if (arg.body.root_id) {
                const parentId = arg.body.parent_id || arg.body.root_id
                const threadReplies = [];
                for (const [key, value] of mockMap) {
                    if (key.startsWith("reply:") && value.parent_id === parentId && value.root_id === arg.body.root_id)
                        threadReplies.push(value);
                }
                return {cursor: "end", user_id: parentId, tweets: threadReplies}
            }
            let tweetsList = []
            for (const [key, value] of mockMap) {
                if (key.startsWith("tweet:")) {
                    tweetsList.push(value)
                }
            }
            return {cursor: "end", user_id: arg.body.user_id, tweets: tweetsList}

        case PUBLIC_GET_USERS:
            let usersList = []
            for (let i = 0; i < 5; i++)  {
                const nu = newUser()
                nu.username = ""+i
                usersList.push(nu)
                mockMap.set("user:"+nu.id, nu)
            }

            for (const [key, value] of mockMap) {
                if (key.startsWith("user:")) {
                    usersList.push(value)
                }
            }
            return {cursor: "end", user_id: arg.body.user_id, users: usersList}

        case PRIVATE_POST_UPLOAD_IMAGE:
            const imgResult = {};
            for (let i = 1; i <= 4; i++) {
                const img = arg.body["image" + i];
                if (img) {
                    const imageKey = "img_"+generateUUID();
                    mockMap.set("image:"+imageKey, img);
                    imgResult["key" + i] = imageKey;
                } else {
                    imgResult["key" + i] = "";
                }
            }
            return imgResult;

        case PUBLIC_GET_IMAGE:
            const gotImg = mockMap.get("image:"+arg.body.key);
            if (!gotImg) return {code:404, message:"Image not found"};
            return {file: gotImg};

        case PRIVATE_POST_UPLOAD_VIDEO:
            if (!arg.body.video) return {code:500, message:"a video must be provided"};
            const videoKey = "vid_"+generateUUID();
            mockMap.set("video:"+videoKey, arg.body.video);
            return {key: videoKey};

        case PUBLIC_GET_VIDEO:
            const gotVideo = mockMap.get("video:"+arg.body.key);
            if (!gotVideo) return {code:404, message:"Video not found"};
            if (arg.body.deferred) {
                return {file: "", size: gotVideo.length, deferred: true};
            }
            return {file: gotVideo, size: gotVideo.length};

        case PUBLIC_GET_WHOTOFOLLOW:
            const allUsers = [];
            for (const [key, value] of mockMap) {
                if (key.startsWith("user:")) {
                    const id = key.substring("user:".length)
                    if (id === arg.body.user_id) {
                        continue
                    }
                    // Check if already followed using composite key
                    const isFollowed = mockMap.has("follow:"+arg.body.user_id+":"+id)
                    if (isFollowed) {
                        continue
                    }
                    allUsers.push(value);
                }
            }
            return {users: allUsers.slice(0, 3)};

        case PUBLIC_POST_FOLLOW:
            const followKey = "follow:"+arg.body.followerId+":"+arg.body.followingId;
            if (mockMap.has(followKey)) return {code: 0, message: "Already following"};

            const followerUser = mockMap.get("user:"+arg.body.followerId)
            if (!followerUser) return {code:404, message:"User not found"};
            followerUser.followings_count++
            mockMap.set("user:"+arg.body.followerId, followerUser)

            const followedUser = mockMap.get("user:"+arg.body.followingId)
            if (followedUser) {
                followedUser.followers_count++
                mockMap.set("user:"+arg.body.followingId, followedUser)
            }

            mockMap.set(followKey, {
                followerId: arg.body.followerId,
                followingId: arg.body.followingId
            });
            return {code: 0, message: "Accepted"};

        case PUBLIC_POST_UNFOLLOW:
            const unfollowKey = "follow:"+arg.body.followerId+":"+arg.body.followingId;
            if (!mockMap.has(unfollowKey)) return {code: 0, message: "Not following"};

            const unfollowerUser = mockMap.get("user:"+arg.body.followerId)
            if (unfollowerUser) {
                unfollowerUser.followings_count = Math.max(0, unfollowerUser.followings_count - 1)
                mockMap.set("user:"+arg.body.followerId, unfollowerUser)
            }

            const unfollowedUser = mockMap.get("user:"+arg.body.followingId)
            if (unfollowedUser) {
                unfollowedUser.followers_count = Math.max(0, unfollowedUser.followers_count - 1)
                mockMap.set("user:"+arg.body.followingId, unfollowedUser)
            }

            mockMap.delete(unfollowKey)
            return {code: 0, message: "Accepted"};

        case PUBLIC_GET_FOLLOWERS:
            let followersList = []
            for (const [key, value] of mockMap) {
                if (key.startsWith("follow:") && value.followingId === arg.body.user_id) {
                    followersList.push(value.followerId)
                }
            }
            return {cursor: "end", followers: followersList, following_id: arg.body.user_id};
        case PUBLIC_GET_FOLLOWINGS:
            let followingsList = []
            for (const [key, value] of mockMap) {
                if (key.startsWith("follow:") && value.followerId === arg.body.user_id) {
                    followingsList.push(value.followingId)
                }
            }
            return {cursor: "end", followings: followingsList, follower_id: arg.body.user_id};

        case PUBLIC_POST_REACT: {
            // A user holds one reaction per tweet: switching emoji moves the
            // per-emoji tallies and leaves the total alone, like the node does.
            const reactStats = mockMap.get("stats:"+arg.body.tweet_id)
            const emoji = arg.body.emoji || DEFAULT_REACTION
            const previous = reactStats.my_reaction
            if (previous !== emoji) {
                if (previous) {
                    reactStats.reactions[previous]--
                    if (reactStats.reactions[previous] <= 0) delete reactStats.reactions[previous]
                } else {
                    reactStats.reactions_count++
                }
                reactStats.reactions[emoji] = (reactStats.reactions[emoji] || 0) + 1
                reactStats.my_reaction = emoji
            }
            mockMap.set("stats:"+arg.body.tweet_id, reactStats)
            return {count: reactStats.reactions_count, reactions: {...reactStats.reactions}};
        }

        case PUBLIC_POST_UNREACT: {
            const unreactStats = mockMap.get("stats:"+arg.body.tweet_id)
            const held = unreactStats.my_reaction
            if (held) {
                unreactStats.reactions_count--
                unreactStats.reactions[held]--
                if (unreactStats.reactions[held] <= 0) delete unreactStats.reactions[held]
                unreactStats.my_reaction = ""
            }
            mockMap.set("stats:"+arg.body.tweet_id, unreactStats)
            return {count: unreactStats.reactions_count, reactions: {...unreactStats.reactions}};
        }

        case PUBLIC_POST_POLL_VOTE: {
            const pollKey = "poll:"+arg.body.tweet_id
            const tally = mockMap.get(pollKey) || {votes: new Array(arg.body.options_num || 0).fill(0), voters: {}}
            if (!(arg.body.owner_id in tally.voters)) {
                tally.voters[arg.body.owner_id] = arg.body.option
                tally.votes[arg.body.option] = (tally.votes[arg.body.option] || 0) + 1
                mockMap.set(pollKey, tally)
            }
            return pollResults(tally, arg.body.owner_id);
        }

        case PUBLIC_GET_POLL: {
            const tally = mockMap.get("poll:"+arg.body.tweet_id)
            if (!tally) return {tweet_id: arg.body.tweet_id, votes: new Array(arg.body.options_num || 0).fill(0), total_votes: 0};
            return pollResults(tally, arg.body.owner_id);
        }

        case PUBLIC_POST_VIEW: {
            // NOTE: this mock uses an "infinite" dedup window — once a viewer
            // has been seen for a tweet, the count never re-increments for
            // that pair. The real backend uses a TTL (database.ViewDedupTTL),
            // so re-views beyond the window WILL count there.
            const viewStats = mockMap.get("stats:"+arg.body.tweet_id)
            if (!viewStats) return {count: 0};
            if (arg.body.viewer_id === arg.body.user_id) {
                return {count: viewStats.views_count};
            }
            const dedupKey = "view:"+arg.body.tweet_id+":"+arg.body.viewer_id;
            if (mockMap.has(dedupKey)) {
                return {count: viewStats.views_count};
            }
            mockMap.set(dedupKey, true);
            viewStats.views_count++;
            mockMap.set("stats:"+arg.body.tweet_id, viewStats);
            return {count: viewStats.views_count};
        }

        case PUBLIC_POST_RETWEET:
            const rtId = arg.body.id || arg.body.tweet_id
            let retweetStats = mockMap.get("stats:"+rtId)
            if (retweetStats) {
                retweetStats.retweets_count++
                mockMap.set("stats:"+rtId, retweetStats)
            }

            const retweetedTweet = mockMap.get("tweet:"+rtId)
            if (retweetedTweet) {
                retweetedTweet.retweeted_by = arg.body.retweeted_by
                mockMap.set("tweet:"+retweetedTweet.id, retweetedTweet)
            }
            return retweetedTweet || arg.body

        case PUBLIC_POST_UNRETWEET:
            let unretweetStats = mockMap.get("stats:"+arg.body.tweet_id)
            unretweetStats.retweets_count--
            mockMap.set("stats:"+arg.body.tweet_id, unretweetStats)
            return {code:0, message:"Accepted"};

        case PRIVATE_DELETE_TWEET:
            // A reply carries its thread root_id; delete it from the thread
            // store and decrement its parent's reply count.
            const replyToDelete = mockMap.get("reply:"+arg.body.tweet_id);
            if (replyToDelete) {
                const parentStats = mockMap.get("stats:"+replyToDelete.parent_id)
                if (parentStats) {
                    parentStats.replies_count--
                    mockMap.set("stats:"+replyToDelete.parent_id, parentStats)
                }
                mockMap.delete("reply:"+arg.body.tweet_id);
                return {code:0, message:"Accepted"};
            }
            mockMap.delete("stats:"+arg.body.tweet_id);
            mockMap.delete("tweet:"+arg.body.tweet_id);
            const tl = mockMap.get("timeline") || [];
            mockMap.set("timeline", tl.filter(tw => tw.id !== arg.body.tweet_id));
            return {code:0, message:"Accepted"};

        case PUBLIC_POST_CHAT:
            const chatId = generateUUID();
            const newChat = {
                id: chatId,
                owner_id: arg.body.owner_id,
                other_user_id: arg.body.other_user_id,
                last_message: "",
                created_at: new Date().toISOString(),
                updated_at: new Date().toISOString(),
                messages: [],
            };
            mockMap.set("chat:"+chatId, newChat);
            return newChat;

        case PRIVATE_GET_CHATS:
            const chats = [];
            for (const [key, value] of mockMap) {
                if (key.startsWith("chat:")) chats.push(value);
            }
            return {chats: chats, cursor: "end", user_id: arg.body.user_id};

        case PRIVATE_GET_CHAT:
            const gotChat = mockMap.get("chat:"+arg.body.chat_id);
            if (!gotChat) return {code:404, message:"Chat not found"};
            return gotChat;

        case PRIVATE_GET_MESSAGES:
            const chat = mockMap.get("chat:"+arg.body.chat_id);
            return chat
                ? {chat_id: arg.body.chat_id, cursor: "end", messages: chat.messages}
                : {chat_id: arg.body.chat_id, cursor: "end", messages: []};

        case PUBLIC_POST_MESSAGE:
            const msgId = generateUUID();
            const message = {
                id: msgId,
                chat_id: arg.body.chat_id,
                sender_id: arg.body.sender_id,
                receiver_id: arg.body.receiver_id,
                text: arg.body.text,
                image_keys: arg.body.image_keys || [],
                video_key: arg.body.video_key || "",
                created_at: new Date().toISOString(),
            };
            const targetChat = mockMap.get("chat:"+arg.body.chat_id);
            if (targetChat) {
                targetChat.messages.push(message);
                targetChat.last_message = message.text;
                targetChat.updated_at = message.created_at;
            }
            mockMap.set("message:"+msgId, message);
            return message;

        case PRIVATE_GET_MESSAGE:
            const gotMsg =  mockMap.get("message:"+arg.body.message_id);
            if (!gotMsg) return {code:404, message:"Message not found"};
            return gotMsg;

        case PRIVATE_DELETE_MESSAGE:
            mockMap.delete("message:"+arg.body.message_id);
            return {code:0,message:"Accepted"};

        case PRIVATE_DELETE_CHAT:
            mockMap.delete("chat:"+arg.body.chat_id);
            return {code:0,message:"Accepted"};

        case PRIVATE_GET_NOTIFICATIONS:
            return {cursor: "end", unread_count: 0, notifications: []};

        default:
            return {code:0,message:"Accepted"};
    }
}

function newUser() {
    return {
        avatar_key: "", // MIME + base64
        background_image_key: "",
        bio: "",
        created_at: Date.now().toString(),
        id: generateUUID(),
        isOffline: false,
        node_id: "",
        network: "warpnet",
        username: "Missing!",
        website: "https://warp-net.github.io/",
        moderation: {is_ok: true},
        birthdate: "",
        updated_at: "",
        followings_count: 0,
        followers_count: 0,
        latency: 0,
        tweets_count: 0,
        metadata: {},
    }
}

function pollResults(tally, ownerId) {
    const voted = tally.voters[ownerId];
    return {
        votes: tally.votes,
        total_votes: tally.votes.reduce((sum, n) => sum + n, 0),
        voted_option: voted === undefined ? undefined : voted,
    }
}

function newStats(id) {
    return {
        tweet_id: id,
        retweets_count: 0,
        reactions_count: 0,
        replies_count: 0,
        views_count: 0,
        reactions: {},
        my_reaction: "",
    }
}