/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

// Reactive connection state for the browser dashboard's single WebSocket to
// its node. transport.js updates it from the socket lifecycle; App.vue renders
// a banner from it so the user always knows when the node is unreachable.
//
// Status values: "online" | "connecting" | "offline". Under Wails (desktop
// member node) there is no WebSocket, so the state simply stays "online".
import { reactive } from "vue";

export const connection = reactive({ status: "online" });

export function setConnectionStatus(status) {
  if (connection.status !== status) {
    connection.status = status;
  }
}
