/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

import { EMOJI_CATEGORIES } from "@/lib/emoji-data";

export { EMOJI_CATEGORIES };

// The backend counts runes (Go's utf8.RuneCountInString), so the UI has to
// count code points too. String.length would count UTF-16 units instead and
// charge 2 for every emoji outside the BMP, cutting people off at half the
// limit the node actually accepts.
export function runeLength(text) {
  return text ? [...text].length : 0;
}

// clampRunes trims to a rune budget without splitting a surrogate pair, which
// String.prototype.slice would happily do (leaving a lone half that marshals
// into U+FFFD server-side).
export function clampRunes(text, limit) {
  if (!text) return "";
  const runes = [...text];
  return runes.length <= limit ? text : runes.slice(0, limit).join("");
}

// DEFAULT_REACTION mirrors domain.DefaultReaction: the emoji a like
// carries when none was named, and what every pre-reactions like reads
// back as.
export const DEFAULT_REACTION = "❤️";

// QUICK_REACTIONS is the row offered on long-press, Telegram-style. The
// full picker sits behind the "more" button next to it, so this list only
// has to cover the common cases. Kept in sync with warpdroid's
// TweetReactions.kt.
export const QUICK_REACTIONS = ["❤️", "👍", "👎", "🔥", "🎉", "😁", "😢", "🤔"];

export const SKIN_TONES = [
  { id: 0, modifier: "", label: "Default", swatch: "✋" },
  { id: 1, modifier: "\u{1F3FB}", label: "Light", swatch: "✋\u{1F3FB}" },
  { id: 2, modifier: "\u{1F3FC}", label: "Medium light", swatch: "✋\u{1F3FC}" },
  { id: 3, modifier: "\u{1F3FD}", label: "Medium", swatch: "✋\u{1F3FD}" },
  { id: 4, modifier: "\u{1F3FE}", label: "Medium dark", swatch: "✋\u{1F3FE}" },
  { id: 5, modifier: "\u{1F3FF}", label: "Dark", swatch: "✋\u{1F3FF}" },
];

// A skin tone modifier replaces the emoji variation selector rather than
// following it: U+270C U+1F3FB is a light-skinned victory hand, while
// U+270C U+FE0F U+1F3FB does not compose and renders as two glyphs.
export function applyTone(emoji, tone, supportsTone) {
  if (!tone || !supportsTone) return emoji;
  return emoji.replace(/\uFE0F$/, "") + tone;
}

const RECENT_KEY = "warpnet.emoji.recent";
const TONE_KEY = "warpnet.emoji.tone";
const RECENT_MAX = 32;

function readStore(key, fallback) {
  try {
    const raw = window.localStorage.getItem(key);
    return raw === null ? fallback : JSON.parse(raw);
  } catch (err) {
    // Private mode / disabled storage: recents are a convenience, never fatal.
    return fallback;
  }
}

function writeStore(key, value) {
  try {
    window.localStorage.setItem(key, JSON.stringify(value));
  } catch (err) {
    /* ignore */
  }
}

// Recents are stored in the same [character, keywords] shape the categories
// use, so the picker can render them through one code path.
export function loadRecent() {
  const list = readStore(RECENT_KEY, []);
  if (!Array.isArray(list)) return [];
  return list.filter((e) => Array.isArray(e) && typeof e[0] === "string" && e[0] !== "");
}

export function pushRecent(entry) {
  const rest = loadRecent().filter((e) => e[0] !== entry[0]);
  const next = [entry, ...rest].slice(0, RECENT_MAX);
  writeStore(RECENT_KEY, next);
  return next;
}

export function loadTone() {
  const id = readStore(TONE_KEY, 0);
  return SKIN_TONES.some((t) => t.id === id) ? id : 0;
}

export function saveTone(id) {
  writeStore(TONE_KEY, id);
}

const ALL_EMOJIS = EMOJI_CATEGORIES.flatMap((c) => c.emojis);

export function searchEmojis(query) {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const terms = q.split(/\s+/);
  return ALL_EMOJIS.filter(([, keywords]) => terms.every((t) => keywords.includes(t)));
}

export function findEmoji(char) {
  return ALL_EMOJIS.find(([c]) => c === char);
}

// insertEmoji splices an emoji into `text` at the field's caret (replacing any
// selection) and reports where the caret should land afterwards. Returns null
// when the insert would blow the rune budget, so the caller can leave the text
// untouched rather than silently dropping characters off the end.
export function insertEmoji({ text, emoji, field, limit }) {
  const value = text || "";
  const hasCaret = field && typeof field.selectionStart === "number";
  const start = hasCaret ? field.selectionStart : value.length;
  const end = hasCaret ? field.selectionEnd : value.length;

  const next = value.slice(0, start) + emoji + value.slice(end);
  if (limit && runeLength(next) > limit) return null;

  return { text: next, caret: start + emoji.length };
}

// focusCaret restores focus to the composer after a picker click and puts the
// caret back where the text was inserted, so typing continues inline.
export function focusCaret(field, caret) {
  if (!field) return;
  field.focus();
  if (typeof field.setSelectionRange === "function") {
    try {
      field.setSelectionRange(caret, caret);
    } catch (err) {
      // Some input types (email, number) refuse setSelectionRange.
    }
  }
}
