/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

// dismissable is a mixin factory giving every overlay the same Escape-to-close
// behaviour. Pass the event name the component emits on close (default
// "close"); the handler emits it when Escape is pressed. Components that guard
// against unsaved changes should instead pass a handler name and implement it.
//
//   mixins: [dismissable("cancel")]
//
// or, to run custom logic (e.g. a discard confirmation):
//
//   mixins: [dismissable({ handler: "onEscape" })]
export function dismissable(opts = "close") {
  const config = typeof opts === "string" ? { emit: opts } : opts;
  return {
    mounted() {
      this.__escHandler = (e) => {
        if (e.key !== "Escape") return;
        if (config.handler && typeof this[config.handler] === "function") {
          this[config.handler](e);
        } else {
          this.$emit(config.emit || "close");
        }
      };
      document.addEventListener("keydown", this.__escHandler);
    },
    beforeUnmount() {
      if (this.__escHandler) {
        document.removeEventListener("keydown", this.__escHandler);
        this.__escHandler = null;
      }
    },
  };
}
