/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

// Warpnet user ids are ULIDs (26 chars, Crockford base32); bridged Mastodon
// accounts use fediverse handles like "user@instance" instead.
const ULID_RE = /^[0-9A-HJKMNP-TV-Z]{26}$/i;

const WARPNET_NETWORKS = ['warpnet', 'testnet', 'mainnet'];

// A user belongs to the Mastodon block when the backend tagged it with a
// foreign network, or — for older cached entries without the tag — when its
// id is not a ULID.
export function isMastodonUser(user) {
    if (!user) {
        return false;
    }
    if (user.network) {
        return !WARPNET_NETWORKS.includes(user.network);
    }
    return !ULID_RE.test(user.id || '');
}
