/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

import { x25519 } from "@noble/curves/ed25519";
import { chacha20poly1305 } from "@noble/ciphers/chacha";
import { sha256 } from "@noble/hashes/sha256";
import { hmac } from "@noble/hashes/hmac";

const PROTOCOL_NAME = "Noise_NX_25519_ChaChaPoly_SHA256";
const DHLEN = 32;
const TAGLEN = 16;
const EMPTY = new Uint8Array(0);

function concat(...arrays) {
  const total = arrays.reduce((n, a) => n + a.length, 0);
  const out = new Uint8Array(total);
  let off = 0;
  for (const a of arrays) {
    out.set(a, off);
    off += a.length;
  }
  return out;
}

function hkdf2(chainingKey, ikm) {
  const temp = hmac(sha256, chainingKey, ikm);
  const out1 = hmac(sha256, temp, Uint8Array.of(1));
  const out2 = hmac(sha256, temp, concat(out1, Uint8Array.of(2)));
  return [out1, out2];
}

function nonceFor(n) {
  const b = new Uint8Array(12);
  new DataView(b.buffer).setBigUint64(4, BigInt(n), true);
  return b;
}

class CipherState {
  constructor(key) {
    this.key = key;
    this.n = 0;
  }

  encryptWithAd(ad, plaintext) {
    if (!this.key) return plaintext;
    const ct = chacha20poly1305(this.key, nonceFor(this.n), ad).encrypt(plaintext);
    this.n++;
    return ct;
  }

  decryptWithAd(ad, ciphertext) {
    if (!this.key) return ciphertext;
    const pt = chacha20poly1305(this.key, nonceFor(this.n), ad).decrypt(ciphertext);
    this.n++;
    return pt;
  }
}

class SymmetricState {
  constructor() {
    this.h = new TextEncoder().encode(PROTOCOL_NAME);
    this.ck = this.h;
    this.cs = new CipherState(null);
    this.mixHash(EMPTY);
  }

  mixHash(data) {
    this.h = sha256(concat(this.h, data));
  }

  mixKey(ikm) {
    const [ck, tempK] = hkdf2(this.ck, ikm);
    this.ck = ck;
    this.cs = new CipherState(tempK);
  }

  encryptAndHash(plaintext) {
    const ct = this.cs.encryptWithAd(this.h, plaintext);
    this.mixHash(ct);
    return ct;
  }

  decryptAndHash(ciphertext) {
    const pt = this.cs.decryptWithAd(this.h, ciphertext);
    this.mixHash(ciphertext);
    return pt;
  }

  split() {
    const [k1, k2] = hkdf2(this.ck, EMPTY);
    return [new CipherState(k1), new CipherState(k2)];
  }
}

export class NoiseSession {
  constructor(send, recv, remoteStatic, handshakeHash) {
    this._send = send;
    this._recv = recv;
    this.remoteStatic = remoteStatic;
    this.handshakeHash = handshakeHash;
  }

  encrypt(plaintext) {
    return this._send.encryptWithAd(EMPTY, plaintext);
  }

  decrypt(frame) {
    return this._recv.decryptWithAd(EMPTY, frame);
  }
}

export class NoiseInitiator {
  constructor(ephemeralPriv) {
    this.ss = new SymmetricState();
    this.ePriv = ephemeralPriv || x25519.utils.randomPrivateKey();
    this.ePub = x25519.getPublicKey(this.ePriv);
  }

  writeMessageA() {
    this.ss.mixHash(this.ePub);
    const payload = this.ss.encryptAndHash(EMPTY);
    return concat(this.ePub, payload);
  }

  readMessageB(msg) {
    if (msg.length < DHLEN + DHLEN + TAGLEN + TAGLEN) {
      throw new Error("noise: handshake response is too short");
    }
    const re = msg.slice(0, DHLEN);
    this.ss.mixHash(re);
    this.ss.mixKey(x25519.getSharedSecret(this.ePriv, re));

    const sealedStatic = msg.slice(DHLEN, DHLEN + DHLEN + TAGLEN);
    const rs = this.ss.decryptAndHash(sealedStatic);
    this.ss.mixKey(x25519.getSharedSecret(this.ePriv, rs));

    this.ss.decryptAndHash(msg.slice(DHLEN + DHLEN + TAGLEN));

    const [send, recv] = this.ss.split();
    return new NoiseSession(send, recv, rs, this.ss.h);
  }
}

export function fingerprint(pub) {
  return Array.from(sha256(pub), (b) => b.toString(16).padStart(2, "0")).join("");
}
