/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

// Waits for the network to confirm a sponsored-tweet payment so the reader
// doesn't have to: each check asks the reader's own node, which re-claims the
// order from the author, and the first answer carrying the tweet ends the wait.
import { warpnetService } from "@/service/service";
import { toast } from "@/lib/toast";

const firstCheckMs = 5000;
const maxCheckMs = 60000;

const waiting = new Map();

export function watchOrder(tweetId, userId, onUnlocked) {
  let order = waiting.get(tweetId);
  if (!order) {
    order = { userId, delay: firstCheckMs, listeners: new Set() };
    waiting.set(tweetId, order);
    setTimeout(() => check(tweetId, order), order.delay);
  }
  order.listeners.add(onUnlocked);
  return () => order.listeners.delete(onUnlocked);
}

async function check(tweetId, order) {
  let tweet = null;
  try {
    tweet = await warpnetService.getSponsoredTweet({ tweetId, userId: order.userId });
  } catch (err) {
    console.warn(`order worker: checking tweet [${tweetId}]`, err);
  }
  if (tweet && !tweet.pending) {
    waiting.delete(tweetId);
    if (order.listeners.size === 0) {
      toast.success("Payment confirmed. The sponsored tweet is unlocked.");
    }
    order.listeners.forEach((onUnlocked) => onUnlocked(tweet));
    return;
  }
  order.delay = Math.min(Math.round(order.delay * 1.5), maxCheckMs);
  setTimeout(() => check(tweetId, order), order.delay);
}
