/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

import { Buffer } from "buffer";

// brotli's compress entrypoint immediately loads an asm.js encoder which
// throws under jsdom (it expects a `Browser` global). Lazy-load it so the
// rest of the service module can be imported in unit tests that don't
// exercise the QR pipeline.
let _compress;
async function getBrotli() {
  if (!_compress) {
    _compress = (await import("brotli/compress")).default;
  }
  return _compress;
}

// Base45 alphabet per RFC 9285. The alphabet is a strict subset of the QR
// alphanumeric mode set, which packs 5.5 bits/char vs. byte mode's 8 — i.e.
// the same compressed bytes occupy ~1.85x fewer QR modules.
const BASE45_ALPHABET =
  "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ $%*+-./:";

function base45Encode(bytes) {
  if (!bytes || bytes.length === 0) return "";
  let out = "";
  let i = 0;
  for (; i + 1 < bytes.length; i += 2) {
    const v = (bytes[i] << 8) | bytes[i + 1];
    const e = Math.floor(v / 2025);
    const r = v % 2025;
    const d = Math.floor(r / 45);
    const c = r % 45;
    out += BASE45_ALPHABET[c] + BASE45_ALPHABET[d] + BASE45_ALPHABET[e];
  }
  if (i < bytes.length) {
    const v = bytes[i];
    const d = Math.floor(v / 45);
    const c = v % 45;
    out += BASE45_ALPHABET[c] + BASE45_ALPHABET[d];
  }
  return out;
}

/**
 * Encode the full AuthNodeInfo for QR pairing: Brotli-compress the UTF-8
 * JSON at maximum quality, then Base45-encode (RFC 9285) the bytes so the
 * result fits in a QR alphanumeric segment. The Android client decodes
 * this payload via `QrPayloadCodec` (`brotli/dec` + Base45) before
 * round-tripping the JSON back to the fat node for the pair handshake.
 */
export async function encodeQRPayload(jsonString) {
  const brotli = await getBrotli();
  const raw = Buffer.from(jsonString, "utf8");
  const compressed = brotli(raw, { mode: 1, quality: 11 });
  if (!compressed) {
    throw new Error("brotli compression failed");
  }
  return base45Encode(compressed);
}

// Exported for unit tests.
export const __test = { base45Encode };
