/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.
 
 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

import QRCode from "qrcode";

// Max payload (byte mode) for QR version 40 at error correction level 'L'.
export const QR_BYTE_MODE_CAPACITY = 2953;

const qrOptions = {
    // 'L' maximises payload capacity (~2953 bytes in byte mode); the pairing
    // envelope is large enough that the default 'M' level overflows and the
    // library throws "data is too big".
    errorCorrectionLevel: "L",
    color: {
        dark: "#c5007f",
        light: "#ffffff",
    },
};

export async function buildQRCode(data) {
    let qrCodeURL
    try {
        qrCodeURL = await QRCode.toDataURL(data, qrOptions);
    } catch (err) {
        console.error("Error generating QR code:", err);
    }
    return qrCodeURL || ""
}
