/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.
 
 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

import QRCode from "qrcode";

const qrOptions = {
    // The pairing payload is Base45 (RFC 9285), whose alphabet is a strict
    // subset of QR alphanumeric mode (~1.85x denser than byte mode). 'M'
    // leaves headroom for the full envelope without dropping below the
    // recommended error-correction floor.
    errorCorrectionLevel: "M",
    // Render the underlying PNG at a higher resolution than the default
    // (~200px) so the modal can display the QR at ~384px without bilinear
    // upscaling blur. 768px gives a clean 2x for the displayed w-96 box.
    width: 768,
    margin: 2,
    color: {
        dark: "#c5007f",
        light: "#ffffff",
    },
};

export async function buildQRCode(data) {
    let qrCodeURL
    try {
        qrCodeURL = await QRCode.toDataURL(data, qrOptions);
    } catch (err) {
        console.error("Error generating QR code:", err);
    }
    return qrCodeURL || ""
}
