/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

// Global toast primitive. One reactive queue shared across the app so any
// component or service can surface an error/success without prop plumbing.
// ToastHost.vue (mounted once in App.vue) renders this queue.
import { reactive } from "vue";

let seq = 0;
export const toastState = reactive({ items: [] });

export function dismissToast(id) {
  const i = toastState.items.findIndex((t) => t.id === id);
  if (i !== -1) toastState.items.splice(i, 1);
}

function push(type, message, opts = {}) {
  if (!message) return -1;
  const id = ++seq;
  toastState.items.push({ id, type, message, action: opts.action || null });
  // Errors linger a little longer so the user can read them; success/info are
  // transient. A non-positive duration keeps the toast until dismissed.
  const ttl = opts.duration != null ? opts.duration : type === "error" ? 6000 : 3500;
  if (ttl > 0) {
    setTimeout(() => dismissToast(id), ttl);
  }
  return id;
}

export const toast = {
  error: (message, opts) => push("error", message, opts),
  success: (message, opts) => push("success", message, opts),
  info: (message, opts) => push("info", message, opts),
  // action: a toast carrying a single button (e.g. "Undo"). onClick runs and
  // the toast is dismissed. Defaults to a longer window so it isn't missed.
  action: (message, label, onClick, opts = {}) =>
    push(opts.type || "success", message, {
      duration: opts.duration != null ? opts.duration : 6000,
      action: { label, onClick },
    }),
};
