/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

// transport bridges the frontend to its node, keeping the exact signatures the
// service layer already calls. Under Wails (desktop/member) it delegates to the
// bound Go App. Otherwise — the remote node's browser dashboard — it speaks a
// single WebSocket: login, logout, is-first-run and every node call ride one
// connection. Each connection starts with a Noise NX handshake (lib/noise.js):
// the browser is anonymous, the node authenticates with its static key, which
// is pinned here on first contact (TOFU) and checked on every reconnect. Every
// frame after the handshake is sealed with per-connection session keys; no
// preshared secret is involved, the login credentials ride inside the
// encrypted channel.
import * as Wails from "../../wailsjs/go/main/App";
import * as WailsRuntime from "../../wailsjs/runtime/runtime";
import {generateUUID} from "@/lib/uuid";
import { NoiseInitiator, fingerprint } from "@/lib/noise";
import { setConnectionStatus } from "@/lib/connection";

// nodeError builds an Error whose message is safe to show a user verbatim
// (every component surfaces error.message) while carrying a machine-readable
// .code for callers that need to branch.
function nodeError(code, message) {
  const e = new Error(message);
  e.code = code;
  return e;
}

const IS_FIRST_RUN_PATH = "is-first-run";
const REQUEST_TIMEOUT_MS = 30000;

function hasWails() {
  return (
    typeof window !== "undefined" &&
    window.go &&
    window.go.main &&
    window.go.main.App &&
    typeof window.go.main.App.Call === "function"
  );
}

// hasWailsRuntime reports whether the Wails event runtime is injected. It is a
// separate global from the Go bindings (window.runtime vs window.go), so the
// runtime-event wrappers below check it independently.
function hasWailsRuntime() {
  return (
    typeof window !== "undefined" &&
    window.runtime &&
    typeof window.runtime.EventsOnMultiple === "function"
  );
}

// EventsOn / EventsOff bridge the Wails event runtime (used for the
// deeplink:open handoff). The browser dashboard has no OS deep links and no
// Wails runtime, so they no-op there instead of dereferencing window.runtime.
export function EventsOn(eventName, callback) {
  if (hasWailsRuntime()) {
    return WailsRuntime.EventsOn(eventName, callback);
  }
  return () => {};
}

export function EventsOff(eventName, ...additional) {
  if (hasWailsRuntime()) {
    WailsRuntime.EventsOff(eventName, ...additional);
  }
}

let socket = null;
let connecting = null;
// session: the Noise transport channel of the current connection. Session keys
// are ephemeral — a reconnect or page reload simply handshakes again — so
// nothing secret is ever persisted. What IS persisted is the node's static
// public key fingerprint: the TOFU pin that detects an impostor node.
const NODE_KEY_STORAGE = "warpnet.node.key";
let session = null;
const pending = new Map(); // message_id -> { resolve, reject, timer }

function pinnedNodeKey() {
  try {
    return localStorage.getItem(NODE_KEY_STORAGE);
  } catch (_) {
    return null;
  }
}

function pinNodeKey(fp) {
  try {
    localStorage.setItem(NODE_KEY_STORAGE, fp);
  } catch (_) {}
}

function wsURL() {
  const scheme = window.location.protocol === "https:" ? "wss" : "ws";
  return `${scheme}://${window.location.host}/ws`;
}

function failPending(err) {
  for (const [, p] of pending) {
    clearTimeout(p.timer);
    p.reject(err);
  }
  pending.clear();
}

function connect() {
  if (socket && socket.readyState === WebSocket.OPEN && session) {
    return Promise.resolve();
  }
  if (connecting) {
    return connecting;
  }
  setConnectionStatus("connecting");
  connecting = new Promise((resolve, reject) => {
    const sock = new WebSocket(wsURL());
    sock.binaryType = "arraybuffer";
    const initiator = new NoiseInitiator();
    let settled = false;
    const fail = (err) => {
      if (!settled) {
        settled = true;
        connecting = null;
        setConnectionStatus("offline");
        reject(err);
      }
      try { sock.close(); } catch (_) {}
    };
    sock.onopen = () => {
      // Handshake message 1: the browser's ephemeral key. The connection is
      // usable only after the node's response authenticates it below.
      sock.send(initiator.writeMessageA());
    };
    sock.onerror = () => {
      fail(nodeError(
        "ERR_NODE_UNREACHABLE",
        "Can't reach your Warpnet node. Make sure it's running, then try again."
      ));
    };
    sock.onclose = () => {
      socket = null;
      session = null;
      connecting = null;
      setConnectionStatus("offline");
      fail(nodeError(
        "ERR_NODE_UNREACHABLE",
        "Connection to your Warpnet node was lost."
      ));
      failPending(nodeError(
        "ERR_NODE_UNREACHABLE",
        "Connection to your Warpnet node was lost."
      ));
    };
    sock.onmessage = (ev) => {
      if (session && socket === sock) {
        onMessage(ev.data);
        return;
      }
      // Handshake message 2: authenticate the node and pin its key (TOFU).
      let established;
      try {
        established = initiator.readMessageB(new Uint8Array(ev.data));
      } catch (e) {
        console.error("ws handshake failed:", e);
        fail(nodeError(
          "ERR_NODE_HANDSHAKE",
          "Could not establish a secure channel to your Warpnet node."
        ));
        return;
      }
      const fp = fingerprint(established.remoteStatic);
      const pinned = pinnedNodeKey();
      if (pinned && pinned !== fp) {
        fail(nodeError(
          "ERR_NODE_KEY_CHANGED",
          `This node's identity key changed (expected ${pinned.slice(0, 16)}…, ` +
          `got ${fp.slice(0, 16)}…). If you reinstalled the node, clear this ` +
          `site's data and reconnect; otherwise someone may be impersonating it.`
        ));
        return;
      }
      if (!pinned) {
        pinNodeKey(fp);
      }
      session = established;
      socket = sock;
      settled = true;
      connecting = null;
      setConnectionStatus("online");
      resolve();
    };
  });
  return connecting;
}

function onMessage(data) {
  let text;
  try {
    text = new TextDecoder().decode(session.decrypt(new Uint8Array(data)));
  } catch (e) {
    // A frame that fails authentication desyncs the channel's counters —
    // drop the connection; the next call reconnects and handshakes anew.
    console.error("ws decrypt failed:", e);
    try { socket.close(); } catch (_) {}
    return;
  }
  let msg;
  try {
    msg = JSON.parse(text);
  } catch (e) {
    console.error("ws parse failed:", e);
    return;
  }
  const p = pending.get(msg.message_id);
  if (!p) {
    return;
  }
  pending.delete(msg.message_id);
  clearTimeout(p.timer);
  p.resolve(msg);
}

async function send(request) {
  await connect();
  if (!request.message_id) {
    request.message_id = generateUUID();
  }
  const id = request.message_id;

  const payload = session.encrypt(new TextEncoder().encode(JSON.stringify(request)));

  // Archive import processes thousands of tweets server-side and can run
  // well past the default budget; give /import/ routes a long window.
  const timeoutMs = (typeof request.path === "string" && request.path.includes("/import/"))
    ? 10 * 60 * 1000
    : REQUEST_TIMEOUT_MS;
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      pending.delete(id);
      console.debug("request timed out:", id);
      reject(nodeError(
        "ERR_TIMEOUT",
        "The request took too long. Your node may be busy or unreachable."
      ));
    }, timeoutMs);
    pending.set(id, { resolve, reject, timer });
    try {
      socket.send(payload);
    } catch (e) {
      pending.delete(id);
      clearTimeout(timer);
      reject(e);
    }
  });
}

// Call sends a Wails envelope { path, body, message_id, node_id, timestamp }
// and resolves to the response envelope (with .body), matching the Wails
// binding exactly.
//
// Every frame — including login and is-first-run — already rides the
// Noise-encrypted channel established by connect(), so the account
// credentials never depend on any channel secret and nothing special
// happens here for login or logout.
export async function Call(request) {
  if (hasWails()) {
    return Wails.Call(request);
  }
  return send(request);
}

export async function IsFirstRun() {
  if (hasWails()) {
    return Wails.IsFirstRun();
  }
  // Propagate the failure (node unreachable) so the caller can offer a retry
  // instead of silently defaulting to the login screen — a brand-new user
  // would otherwise have no path to sign up.
  const resp = await send({ path: IS_FIRST_RUN_PATH, body: {} });
  return Boolean(resp && resp.body);
}

// First-launch network choice; the app relaunches itself on it (Wails only —
// a remote node's network is pinned by its flags).
export async function SelectNetwork(network) {
  if (hasWails()) {
    return Wails.SelectNetwork(network);
  }
}

export async function Network() {
  if (hasWails()) {
    return Wails.Network();
  }
  return "warpnet";
}

// ConsumePendingDeepLink only has meaning under Wails (OS deep-link handoff);
// the browser dashboard has no pending link, so it resolves to "".
export async function ConsumePendingDeepLink() {
  if (hasWails()) {
    return Wails.ConsumePendingDeepLink();
  }
  return "";
}

// IsDesktop reports whether the Wails desktop runtime is present (member
// node). The browser dashboard (remote node) returns false and must upload
// the archive via an <input type=file> instead of the native dialog.
export function IsDesktop() {
  return hasWails();
}

