/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

// transport bridges the frontend to its node, keeping the exact signatures the
// service layer already calls. Under Wails (desktop/member) it delegates to the
// bound Go App. Otherwise — the business node's browser dashboard — it speaks a
// single WebSocket: login, logout, is-first-run and every node call ride one
// connection. The connection carries its own auth (a successful login
// authenticates the socket), and every frame after login is AES-256-GCM sealed
// with sha256(password); login and is-first-run precede the key, so they go in
// cleartext.
import * as Wails from "../../wailsjs/go/main/App";
import * as WailsRuntime from "../../wailsjs/runtime/runtime";
import {generateUUID} from "@/lib/uuid";
import { gcm } from "@noble/ciphers/aes";
import { sha256 } from "@noble/hashes/sha256";

const LOGIN_PATH = "/private/post/login/0.0.0";
const LOGOUT_PATH = "/private/post/logout/0.0.0";
const IS_FIRST_RUN_PATH = "is-first-run";
const REQUEST_TIMEOUT_MS = 30000;

function hasWails() {
  return (
    typeof window !== "undefined" &&
    window.go &&
    window.go.main &&
    window.go.main.App &&
    typeof window.go.main.App.Call === "function"
  );
}

// hasWailsRuntime reports whether the Wails event runtime is injected. It is a
// separate global from the Go bindings (window.runtime vs window.go), so the
// runtime-event wrappers below check it independently.
function hasWailsRuntime() {
  return (
    typeof window !== "undefined" &&
    window.runtime &&
    typeof window.runtime.EventsOnMultiple === "function"
  );
}

// EventsOn / EventsOff bridge the Wails event runtime (used for the
// deeplink:open handoff). The browser dashboard has no OS deep links and no
// Wails runtime, so they no-op there instead of dereferencing window.runtime.
export function EventsOn(eventName, callback) {
  if (hasWailsRuntime()) {
    return WailsRuntime.EventsOn(eventName, callback);
  }
  return () => {};
}

export function EventsOff(eventName, ...additional) {
  if (hasWailsRuntime()) {
    WailsRuntime.EventsOff(eventName, ...additional);
  }
}

let socket = null;
let connecting = null;
// aesKey: raw 32-byte channel key (SHA-256 of the password). Persisted to
// localStorage so reopening the tab or reloading the page resumes the
// already-authenticated node's session (restoring the key here) instead of
// bouncing to the login screen; cleared on logout.
const CHANNEL_KEY_STORAGE = "warpnet.channel.key";
let aesKey = restoreChannelKey();
const pending = new Map(); // message_id -> { resolve, reject, timer }

function restoreChannelKey() {
  try {
    const saved = localStorage.getItem(CHANNEL_KEY_STORAGE);
    return saved ? base64ToBytes(saved) : null;
  } catch (_) {
    return null;
  }
}

function saveChannelKey() {
  try {
    if (aesKey) localStorage.setItem(CHANNEL_KEY_STORAGE, bytesToBase64(aesKey));
  } catch (_) {}
}

function clearChannelKey() {
  aesKey = null;
  try {
    localStorage.removeItem(CHANNEL_KEY_STORAGE);
  } catch (_) {}
}

function wsURL() {
  const scheme = window.location.protocol === "https:" ? "wss" : "ws";
  return `${scheme}://${window.location.host}/ws`;
}

function failPending(err) {
  for (const [, p] of pending) {
    clearTimeout(p.timer);
    p.reject(err);
  }
  pending.clear();
}

function connect() {
  if (socket && socket.readyState === WebSocket.OPEN) {
    return Promise.resolve();
  }
  if (connecting) {
    return connecting;
  }
  connecting = new Promise((resolve, reject) => {
    const sock = new WebSocket(wsURL());
    sock.onopen = () => {
      socket = sock;
      connecting = null;
      resolve();
    };
    sock.onerror = () => {
      connecting = null;
      reject(new Error("ws connect failed"));
    };
    sock.onclose = () => {
      socket = null;
      connecting = null;
      aesKey = null;
      failPending(new Error("ws closed"));
    };
    sock.onmessage = (ev) => { onMessage(ev.data); };
  });
  return connecting;
}

async function onMessage(data) {
  let text = data;
  if (aesKey) {
    try {
      text = await aesDecrypt(aesKey, data);
    } catch (e) {
      console.error("ws decrypt failed:", e);
      return;
    }
  }
  let msg;
  try {
    msg = JSON.parse(text);
  } catch (e) {
    console.error("ws parse failed:", e);
    return;
  }
  const p = pending.get(msg.message_id);
  if (!p) {
    return;
  }
  pending.delete(msg.message_id);
  clearTimeout(p.timer);
  p.resolve(msg);
}

async function send(request) {
  await connect();
  if (!request.message_id) {
    request.message_id = generateUUID();
  }
  const id = request.message_id;

  let payload = JSON.stringify(request);
  if (aesKey) {
    payload = await aesEncrypt(aesKey, payload);
  }

  // Archive import processes thousands of tweets server-side and can run
  // well past the default budget; give /import/ routes a long window.
  const timeoutMs = (typeof request.path === "string" && request.path.includes("/import/"))
    ? 10 * 60 * 1000
    : REQUEST_TIMEOUT_MS;
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      pending.delete(id);
      reject(new Error(`request ${id} timed out`));
    }, timeoutMs);
    pending.set(id, { resolve, reject, timer });
    try {
      socket.send(payload);
    } catch (e) {
      pending.delete(id);
      clearTimeout(timer);
      reject(e);
    }
  });
}

// Call sends a Wails envelope { path, body, message_id, node_id, timestamp }
// and resolves to the response envelope (with .body), matching the Wails
// binding exactly.
//
// The dashboard channel is AES-256-GCM with the password as the preshared key
// (the same secret the server is launched with). is-first-run precedes the
// password and goes in cleartext; the login frame is the first encrypted one,
// so the key is derived from the entered password *before* sending it. A
// rejected or failed login clears the key so the user can retry.
export async function Call(request) {
  if (hasWails()) {
    return Wails.Call(request);
  }
  if (request.path === LOGIN_PATH) {
    aesKey = await importKey(request.body && request.body.password);
    try {
      const resp = await send(request);
      if (resp && resp.body && resp.body.code) {
        clearChannelKey(); // login rejected
      } else {
        saveChannelKey(); // persist so a page reload resumes the session
      }
      return resp;
    } catch (e) {
      clearChannelKey(); // wrong password / timeout — allow another attempt
      throw e;
    }
  }
  const resp = await send(request);
  if (request.path === LOGOUT_PATH) {
    clearChannelKey();
  }
  return resp;
}

// IsFirstRun reports whether the given network has no account on this device
// yet. The network is a login-page input, so it is forwarded to the node: the
// first-run state is tracked per network (each lives in its own database dir).
export async function IsFirstRun(network) {
  if (hasWails()) {
    return Wails.IsFirstRun(network || "");
  }
  try {
    const resp = await send({ path: IS_FIRST_RUN_PATH, body: { network: network || "" } });
    return Boolean(resp && resp.body);
  } catch (e) {
    console.error("is-first-run failed:", e);
    return false;
  }
}

// ConsumePendingDeepLink only has meaning under Wails (OS deep-link handoff);
// the browser dashboard has no pending link, so it resolves to "".
export async function ConsumePendingDeepLink() {
  if (hasWails()) {
    return Wails.ConsumePendingDeepLink();
  }
  return "";
}

// IsDesktop reports whether the Wails desktop runtime is present (member
// node). The browser dashboard (business node) returns false and must upload
// the archive via an <input type=file> instead of the native dialog.
export function IsDesktop() {
  return hasWails();
}

// --- AES-256-GCM via @noble (pure JS — works over plain http:// where
// crypto.subtle is unavailable). Wire-compatible with Go's security.AESCodec:
// key = SHA-256(password); frame = base64( nonce(12) || ciphertext||tag(16) ).

// importKey returns the raw 32-byte channel key, SHA-256(password), matching
// Go's security.AESKeyFromPassword.
function importKey(password) {
  return sha256(new TextEncoder().encode(password || ""));
}

function aesEncrypt(key, plaintext) {
  const nonce = crypto.getRandomValues(new Uint8Array(12));
  const ct = gcm(key, nonce).encrypt(new TextEncoder().encode(plaintext));
  const frame = new Uint8Array(nonce.length + ct.length);
  frame.set(nonce, 0);
  frame.set(ct, nonce.length);
  return bytesToBase64(frame);
}

function aesDecrypt(key, b64) {
  const frame = base64ToBytes(b64);
  const nonce = frame.slice(0, 12);
  const ct = frame.slice(12);
  return new TextDecoder().decode(gcm(key, nonce).decrypt(ct));
}

function bytesToBase64(bytes) {
  // Encode in 32 KB chunks: a per-byte string build is O(n) garbage and a
  // multi-MB import frame (tweet + photos) would otherwise stall the tab.
  let s = "";
  const chunk = 0x8000;
  for (let i = 0; i < bytes.length; i += chunk) {
    s += String.fromCharCode.apply(null, bytes.subarray(i, i + chunk));
  }
  return btoa(s);
}

function base64ToBytes(b64) {
  const s = atob(b64);
  const bytes = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) {
    bytes[i] = s.charCodeAt(i);
  }
  return bytes;
}
