/* License generated by licensor(https://github.com/Marvin9/licensor).

 Warpnet - Decentralized Social Network
 Copyright (C) 2025 Vadim Filin, https://github.com/Warp-net,
 <github.com.mecdy@passmail.net>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

WarpNet is provided “as is” without warranty of any kind, either expressed or implied.
Use at your own risk. The maintainers shall not be liable for any damages or data loss
resulting from the use or misuse of this software.
*/

import { reactive } from "vue";
import { warpnetService } from "@/service/service";

const checkEveryMs = 30000;

const statuses = reactive(new Map());
const checks = new Map();

export function userStatus(userId) {
  return statuses.get(userId);
}

export function watchUserStatus(userId) {
  let c = checks.get(userId);
  if (!c) {
    c = { watchers: 0, timer: null, inFlight: false, checkedAt: 0 };
    checks.set(userId, c);
  }
  c.watchers++;
  const age = Date.now() - c.checkedAt;
  if (c.watchers === 1 && age >= checkEveryMs) {
    statuses.delete(userId);
  }
  if (c.watchers === 1 && !c.inFlight) {
    c.timer = setTimeout(() => check(userId, c), Math.max(checkEveryMs - age, 0));
  }
  return () => {
    c.watchers--;
    if (c.watchers === 0) {
      clearTimeout(c.timer);
      c.timer = null;
    }
  };
}

async function check(userId, c) {
  c.timer = null;
  c.inFlight = true;
  let status = null;
  try {
    status = await warpnetService.getUserStatus(userId);
  } catch (err) {
    console.warn(`user status: checking [${userId}]`, err);
  }
  c.inFlight = false;
  c.checkedAt = Date.now();
  if (typeof status?.is_online === "boolean") {
    statuses.set(userId, { online: status.is_online, lastSeen: status.last_seen || "" });
  } else {
    statuses.delete(userId);
  }
  if (c.watchers > 0) {
    c.timer = setTimeout(() => check(userId, c), checkEveryMs);
  }
}
