name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-bootstrap:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
          cache-dependency-path: godep/go.sum

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Bootstrap Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/warp-net/warpnet-bootstrap:latest
          build-args: --dns 8.8.8.8

  build-member:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
          cache-dependency-path: godep/go.sum

      - name: Test
        run: CGO_ENABLED=0 go test -count=1 -short ./...

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Member Docker image
        id: docker_build_member
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/warp-net/warpnet-member:latest
          build-args: |
            NODE_TYPE=member

  build-moderator:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
          cache-dependency-path: godep/go.sum

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Moderator Docker image
        id: docker_build_moderator
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.moderator
          push: true
          tags: ghcr.io/warp-net/warpnet-moderator:latest


