name: Build & Deploy Testnet

on:
  # push:
  #   branches:
  #     - develop
  workflow_dispatch:

jobs:
  build-bootstrap:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.26
          cache-dependency-path: godep/go.sum

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Bootstrap Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.bootstrap
          push: true
          tags: ghcr.io/warp-net/warpnet-bootstrap:latest
          build-args: --dns 8.8.8.8

  build-moderator:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.26
          cache-dependency-path: godep/go.sum

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Moderator Docker image
        id: docker_build_moderator
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.moderator
          push: true
          tags: ghcr.io/warp-net/warpnet-moderator:latest
          build-args: --dns 8.8.8.8

  build-echo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.26
          cache-dependency-path: godep/go.sum

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Echo Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.echo
          push: true
          tags: ghcr.io/warp-net/warpnet-echo:latest
          build-args: --dns 8.8.8.8

  deploy:
    runs-on: ubuntu-latest
    needs: [ build-bootstrap, build-moderator ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H 207.154.221.44 >> ~/.ssh/known_hosts
          ssh-keyscan -H 130.94.88.38 >> ~/.ssh/known_hosts

      - name: Deploy to Testnet DO Droplet
        run: |
          scp ./deploy/deploy.sh root@207.154.221.44:/root
          scp ./deploy/docker-compose-testnet.yml root@207.154.221.44:/root/docker-compose-testnet.yml
          ssh root@207.154.221.44 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} MAINNET=false bash /root/deploy.sh'

      - name: Deploy to Testnet Lightnode Droplet
        run: |
          scp ./deploy/deploy.sh root@130.94.88.38:/root
          scp ./deploy/docker-compose-testnet-ru.yml root@130.94.88.38:/root/docker-compose-testnet.yml
          ssh root@130.94.88.38 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} MAINNET=false bash /root/deploy.sh'




