name: Member Node Release

on:
  workflow_dispatch:

env:
  GO_VERSION: '1.24'

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt update &&
          sudo apt install -y libwebkit2gtk-4.1-dev &&
          go install github.com/wailsapp/wails/v2/cmd/wails@v2.10.2

      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "latest"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

