name: Member Node Release

on:
  workflow_dispatch:

env:
  GO_VERSION: '1.24'

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            releaser: release/goreleaser.linux.yml
          - os: macos-latest
            releaser: release/goreleaser.darwin.yml
          - os: windows-latest
            releaser: release/goreleaser.windows.yml
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Linux system dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt update &&
          sudo apt install -y libwebkit2gtk-4.1-dev

      - name: Install Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@v2.10.2

      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "v2"
          args: release --clean --config ${{ matrix.releaser }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

