name: Member Node Release

on:
  workflow_dispatch:

env:
  GO_VERSION: '1.24'
  GOFLAGS: -tags=webkit2_41

jobs:
  linux:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libgtk-3-dev libwebkit2gtk-4.0-dev libglib2.0-dev pkg-config \
            libnss3 libx11-xcb-dev libxcomposite-dev libxdamage-dev libxrandr-dev \
            libasound2-dev libatk1.0-dev libcups2-dev libdbus-1-dev libdrm-dev \
            libxext-dev libxfixes-dev libxkbcommon-dev libxrender-dev libxcb1-dev libxtst-dev

      - run: GOPROXY=off GOSUMDB=off go install github.com/wailsapp/wails/v2/cmd/wails
      - run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "latest"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  macos:
#    runs-on: macos-14
#    permissions:
#      packages: write
#      contents: write
#      pull-requests: write
#      repository-projects: write
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#          fetch-tags: true
#
#      - uses: actions/setup-go@v5
#        with:
#          go-version: ${{ env.GO_VERSION }}
#
#      - run: brew install gtk+3 webkit2gtk pkg-config
#      - run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.10.2
#      - run: echo "$HOME/go/bin" >> $GITHUB_PATH
#
#      - uses: goreleaser/goreleaser-action@v6
#        with:
#          distribution: goreleaser
#          version: "latest"
#          args: release --clean --id=member-macos --single-target
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#  windows:
#    runs-on: windows-2022
#    permissions:
#      packages: write
#      contents: write
#      pull-requests: write
#      repository-projects: write
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#          fetch-tags: true
#
#      - uses: actions/setup-go@v5
#        with:
#          go-version: ${{ env.GO_VERSION }}
#
#      - run: echo "$env:USERPROFILE\\go\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
#
#      - name: Install Wails CLI
#        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.10.2
#
#      - name: Download GTK runtime
#        run: |
#          curl -L -o gtk.zip https://github.com/wailsapp/wails/releases/download/v2.6.0/gtk-runtime-windows.zip
#          mkdir gtk
#          tar -xf gtk.zip -C gtk
#
#      - name: Set GTK env
#        run: |
#          echo "GTK_BASEPATH=${{ github.workspace }}\\gtk" >> $env:GITHUB_ENV
#          echo "${{ github.workspace }}\\gtk\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
#
#      - uses: goreleaser/goreleaser-action@v6
#        with:
#          distribution: goreleaser
#          version: "latest"
#          args: release --clean --id=member-windows --single-target
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
